### ISSUE TITLE
[discussion] radix-ui added tailwindcss for all primitive examples, now what?

### ISSUE THREAD

**Issue by mkandan** [shadcn/ui#140]
radix-ui announced about a month ago they had added TailwindCSS support for all their primitives' examples on [Twitter](https://twitter.com/radix_ui/status/1626219141647728641). Checked it out, and yep it's true and works well.

Wondering how this stacks up against just using this project. Any advice? I know picking "one over the other" isn't really encompassing in this case, since this repo is built around radix-ui's primitives...

**Comment by florisbosch** [comment]
I see this package more like an extension on radix-ui with the examples from the docs you can easily create re-usable components with variants using CVA and tailwind-merge. 

This way when you use your pre-defined components you have a clean usage in your views and you'll still be able to extend/override it with tailwind.

**Comment by shadcn** [comment]
@mkandan I'm going to close this issue. Feel free to reopen if you have any other question. Thank you.
