### ISSUE TITLE
Website is laggy 

### ISSUE THREAD

**Issue by sravanpant** [shadcn/ui#142]
whenever you select a new component the website gets refreshed and the scroll bar of the side bar reaches the top again and you have to scroll down again after selecting another component. It could be fixed by adding the classname overflow-auto in the div tag using tailwind

**Comment by shadcn** [comment]
>  It could be fixed by adding the classname overflow-auto in the div tag using tailwind

Which div?

**Comment by shadcn** [comment]
Fixed.
