### ISSUE TITLE
Unable to edit input fields inside Sheet component

### ISSUE THREAD

**Issue by suryatmodulus** [shadcn/ui#153]
Link : https://ui.shadcn.com/docs/primitives/sheet

**Comment by suryatmodulus** [comment]
Oh Okayy

**Comment by d4vidsha** [comment]
> Link : https://ui.shadcn.com/docs/primitives/sheet

I think the example on this page misleads us into thinking we can edit the page. It's a sheet describing as if you could edit the fields, but you can't.
<img width="1672" alt="image" src="https://github.com/shadcn-ui/ui/assets/70577814/407a58b4-88e8-4cf1-a791-47acd5314c13">
