### ISSUE TITLE
Add an option in CLI to choose package managers (such as npm, yarn, pnpm) for installing dependencies

### ISSUE THREAD

**Issue by ryadav96** [shadcn/ui#190]

**Comment by shadcn** [comment]
This should be automatic. The CLI will detect which package manager the project is using and use that. Let me know if this is not working.

**Comment by makyfj** [comment]
I'm using yarn for my project and when I use `npx shadcn-ui init` and `npx shadcn-ui add button`, it creates a package-lock.json.
![image](https://user-images.githubusercontent.com/65879341/232941975-9b1cadb1-40a0-4add-87fa-e71894ba1005.png)

**Comment by ryadav96** [comment]
@shadcn Its not working. I am using `pnpm`

**Comment by shadcn** [comment]
@ryadav96 `pnpx shadcn-ui add button`?

**Comment by Rawnly** [comment]
I think you have to use:

-  `npx` for `npm`
- `yarn dlx` for `yarn`
- `pnpx` or `pnpm dlx` for `pnpm`

in order to solve this. The package manager is inherited by the shell not by current files :)

**Comment by migsdeving** [comment]
I'm not being able to install it. Tried it first with pnpm, not working, getting code error 1 from a package called three sitters. Also the code it copies from pnpm on your docs is with `pnpx` which does not work anymore on pnpm, you should change it to `pnpm dlx`.
Getting all the same errors with normal npm, and can't run the equivalent npx command for yarn which would be `yarn create` or `yarn dlx`

**Comment by mhaidarhanif** [comment]
@migsdeving Yes, using pnpm should be with `pnpm dlx`. Source: https://pnpm.io/cli/dlx

**Comment by Hanney-Ali** [comment]
I used " pnpm dlx shadcn-ui@latest init" - copied directly from the documentation and got the following error: " ERROR  Command failed with exit code 1: shadcn-ui init".  I tried using "pnpx  shadcn-ui@latest init" as well and I got the same error " ERROR  Command failed with exit code 1: shadcn-ui init". npm gives me proxy errors when installing react.js and next.js so I switched to pnpm, which is giving me the above errors.

**Comment by vincaslt** [comment]
I've tried both `pnpm dlx` and `pnpx`: `pnpm dlx shadcn-ui@latest add "dropdown-menu"`

And with both I'm getting the same error. It seems shadcn is trying to use npm:

```
 Installing dropdown-menu...Command failed with exit code 1: npm install @radix-ui/react-dropdown-menu
```

**Comment by oddiz** [comment]
I had the similar error while using pnpm. Turns out I had a setting in my package.json that states:

``"packageManager": "npm@9.6.3"``

Removing it fixed the issue

**Comment by andrewmartin** [comment]
Thanks @oddiz that worked to fix my issue as well.
