### ISSUE TITLE
Bad character escape sequence error after next 13.3 update

### ISSUE THREAD

**Issue by kratos-respawned** [shadcn/ui#194]
I am getting this error after the latest next13 update

```
./components/ui/alert-dialog.tsx
Module parse failed: Bad character escape sequence (2:67)
| import { createProxy } from "next/dist/build/webpack/loaders/next-flight-loader/module-proxy"
> const proxy = createProxy("C:\Users\sbhan\Desktop\dhun\components\ui\alert-dialog.tsx")
| 
| // Accessing the __esModule property and exporting $$typeof are required here.
```

**Comment by hemantwasthere** [comment]
Is there any way to resolve this issue?
I am also getting the same error, I created the next app using canary and the moment I used 'use client' I got this error

**Comment by kratos-respawned** [comment]
> Is there any way to resolve this issue? I am also getting the same error, I created the next app using canary and the moment I used 'use client' I got this error

I am using turbopack as a temporary workaround

**Comment by hemantwasthere** [comment]
> > Is there any way to resolve this issue? I am also getting the same error, I created the next app using canary and the moment I used 'use client' I got this error
> 
> I am using turbopack as a temporary workaround

What is turbopack, Can you please share any resources regarding that.

**Comment by joaoalcdev** [comment]
I'm also having this problem, as soon as I solve it, I'll give you feedback.

**Comment by kratos-respawned** [comment]
> > > Is there any way to resolve this issue? I am also getting the same error, I created the next app using canary and the moment I used 'use client' I got this error
> > 
> > 
> > I am using turbopack as a temporary workaround
> 
> What is turbopack, Can you please share any resources regarding that.

Use npm or pnpm dev with --turbo flag , for more info checkout  https://turbo.build/pack

**Comment by aranlucas** [comment]
Updating to latest release https://github.com/vercel/next.js/releases/tag/v13.3.1 should fix this

**Comment by kratos-respawned** [comment]
fixed with the latest version of next  💕
