### ISSUE TITLE
Feature Request: Table Component

### ISSUE THREAD

**Issue by skonky** [shadcn/ui#229]

**Comment by stormynight9** [comment]
Check the typography page, there is a table in there.

**Comment by mhaidarhanif** [comment]
While it's true there is a table "example" in the [Typography](https://ui.shadcn.com/docs/components/typography#table) that looks like this:

```tsx
export function TypographyTable() {
  return (
    <div className="my-6 w-full overflow-y-auto">
      <table className="w-full">
        <thead>
          <tr className="m-0 border-t p-0 even:bg-muted">
            <th className="border px-4 py-2 text-left font-bold [&[align=center]]:text-center [&[align=right]]:text-right">
              King's Treasury
            </th>
            <th className="border px-4 py-2 text-left font-bold [&[align=center]]:text-center [&[align=right]]:text-right">
              People's happiness
            </th>
          </tr>
        </thead>
        <tbody>
          <tr className="m-0 border-t p-0 even:bg-muted">
            <td className="border px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
              Empty
            </td>
            <td className="border px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
              Overflowing
            </td>
          </tr>
          <tr className="m-0 border-t p-0 even:bg-muted">
            <td className="border px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
              Modest
            </td>
            <td className="border px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
              Satisfied
            </td>
          </tr>
          <tr className="m-0 border-t p-0 even:bg-muted">
            <td className="border px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
              Full
            </td>
            <td className="border px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
              Ecstatic
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  )
}
```

But probably if meant to be a "ready to use component", it will be like this:

```tsx
export function TableExample() {
  return (
    <div>
      <Table>
        <TableHead>
          <TableRow>
            <TableHead>King's Treasury</TableHead>
            <TableHead>People's happiness</TableHead>
          </TableRow>
        </Thead>
        <Tbody>
          <TableRow>
            <TableData>Empty</TableData>
            <TableData>Overflowing</TableData>
          </TableRow>
          <TableRow>
            <TableData>Modest</TableData>
            <TableData>Satisfied</TableData>
          </TableRow>
          <TableRow>
            <TableData>Full</TableData>
            <TableData>Ecstatic</TableData>
          </TableRow>
        </Tbody>
      </Table>
    </div>
  );
}
```

**Comment by tcortega** [comment]
> While it's true there is a table "example" in the [Typography](https://ui.shadcn.com/docs/components/typography#table) that looks like this:
> 
> ```tsx
> export function TypographyTable() {
>   return (
>     <div className="my-6 w-full overflow-y-auto">
>       <table className="w-full">
>         <thead>
>           <tr className="m-0 border-t p-0 even:bg-muted">
>             <th className="border px-4 py-2 text-left font-bold [&[align=center]]:text-center [&[align=right]]:text-right">
>               King's Treasury
>             </th>
>             <th className="border px-4 py-2 text-left font-bold [&[align=center]]:text-center [&[align=right]]:text-right">
>               People's happiness
>             </th>
>           </tr>
>         </thead>
>         <tbody>
>           <tr className="m-0 border-t p-0 even:bg-muted">
>             <td className="border px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
>               Empty
>             </td>
>             <td className="border px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
>               Overflowing
>             </td>
>           </tr>
>           <tr className="m-0 border-t p-0 even:bg-muted">
>             <td className="border px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
>               Modest
>             </td>
>             <td className="border px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
>               Satisfied
>             </td>
>           </tr>
>           <tr className="m-0 border-t p-0 even:bg-muted">
>             <td className="border px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
>               Full
>             </td>
>             <td className="border px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
>               Ecstatic
>             </td>
>           </tr>
>         </tbody>
>       </table>
>     </div>
>   )
> }
> ```
> 
> But probably if meant to be a "ready to use component", it will be like this:
> 
> ```tsx
> export function TableExample() {
>   return (
>     <div>
>       <Table>
>         <TableHeader>
>           <TableRow>
>             <TableHead>King's Treasury</TableHead>
>             <TableHead>People's happiness</TableHead>
>           </TableRow>
>         </TableHeader>
>         <TableBody>
>           <TableRow>
>             <TableData>Empty</TableData>
>             <TableData>Overflowing</TableData>
>           </TableRow>
>           <TableRow>
>             <TableData>Modest</TableData>
>             <TableData>Satisfied</TableData>
>           </TableRow>
>           <TableRow>
>             <TableData>Full</TableData>
>             <TableData>Ecstatic</TableData>
>           </TableRow>
>         </TableBody>
>       </Table>
>     </div>
>   );
> }
> ```

Indeed, a Table component offers more advanced features such as column sorting, pagination, and possibly the ability to use custom Row/Column Templates with the items passed as parameters, making it distinct from the simple table example in the docs.

+1

**Comment by mhaidarhanif** [comment]
@tcortega It can also starts simple with styling first, without any particular feature. Like what Flowbite has here: https://flowbite.com/docs/components/tables

If need more functionality (not just a styling) then will need to integrate with existing table library such as TanStack Table: https://tanstack.com/table/v8

**Comment by tcortega** [comment]
> @tcortega It can also starts simple with only the styling first, without any particular interactive feature. Like what Flowbite has here: https://flowbite.com/docs/components/tables
> 
> If need more functionality (not just a styling) then will need to integrate with existing table library such as TanStack Table: https://tanstack.com/table/v8

I'll use TanStack Table in the meanwhile, didn't know about it, thankssssssss

**Comment by mhaidarhanif** [comment]
@tcortega Sure thing, you're welcooome

**Comment by kirk-admin** [comment]
Hey there! If you're searching for something a bit more advanced, you might enjoy exploring Material UI Data Grid: https://mui.com/x/react-data-grid/ this is what i use for now but having a hard time customizing it to fit the UI design, It would be fantastic to see it integrated as a feature in the future! 😊

**Comment by freshtechs** [comment]
+1 a table component that would allow filtering/pagination/sorting would be very useful

**Comment by valerius21** [comment]
I'd love to see that too! 

I've already combined some of the table styles from the typography page with tanstack table. 

Has anyone some ideas, which parts of the tanstack table api a component should cover? I'd PR one.

**Comment by tcortega** [comment]
> I'd love to see that too!
> 
> I've already combined some of the table styles from the typography page with tanstack table.
> 
> Has anyone some ideas, which parts of the tanstack table api a component should cover? I'd PR one.

I think this ends up being a pretty personal answer, but, I'd pretty much just use filtering support (global/custom filtering, not filtering per column), column sorting, pagination and that's pretty much I guess?

**Comment by mhaidarhanif** [comment]
There is a PR for this: https://github.com/shadcn/ui/pull/248

**Comment by tcortega** [comment]
> There is a PR for this: #248 feat(Table): Add Table component

I'd say that this table is pretty solid but also too simple

**Comment by mhaidarhanif** [comment]
| I'd say that this table is pretty solid but also too simple

Yeah, [@shadcn said](https://github.com/shadcn/ui/pull/248#issuecomment-1522890928):

| This looks great. I've been testing tanstack-table integration. I'll give this a try with this component and report back.

**Comment by multiwebinc** [comment]
As an alternative to Tanstack, I would also like to recommend Adobe's [React Aria](https://react-spectrum.adobe.com/react-aria/useTable.html), which has an accessibility-first philosophy and would probably be a better fit for Radix.

**Comment by mhaidarhanif** [comment]
> As an alternative, I would also like to recommend Adobe's [React Aria](https://react-spectrum.adobe.com/react-aria/useTable.html), which has an accessibility-first philosophy and would probably be a better fit for Radix.

Just realized this is much nicer.

Probably:

- Simple table -> upcoming shadcn UI Table, MUI Table
- More featured table -> React Aria useTable
- Full featured complex table -> TanStack Table

**Comment by tcortega** [comment]
> > As an alternative, I would also like to recommend Adobe's [React Aria](https://react-spectrum.adobe.com/react-aria/useTable.html), which has an accessibility-first philosophy and would probably be a better fit for Radix.
> 
> Just realized this is also nice.
> 
> Probably:
> 
> * Simple table -> upcoming shadcn UI Table, MUI Table
> * More featured table -> React Aria useTable, MUI DataGrid
> * Full featured complex table -> TanStack Table

To be honest, I don't see the necessity of using intermediate tables like React Aria's or MUI's. TanStack already offers accessibility and is extremely user-friendly. It provides optional features that work seamlessly across various browsers. I've built and tested it using the same style as shadcn.

Typically, there are two scenarios: displaying a small amount of data in a tabular format, or displaying a small or large dataset with filtering, sorting, and pagination capabilities for users. Given that React Aria's table lacks pagination, I find the middle option redundant.

**Comment by mhaidarhanif** [comment]
> To be honest, I don't see the necessity of using intermediate tables like React Aria's or MUI's. TanStack already offers accessibility and is extremely user-friendly. It provides optional features that work seamlessly across various browsers. I've built and tested it using the same style as shadcn.
> 
> Typically, there are two scenarios: displaying a small amount of data in a tabular format, or displaying a small or large dataset with filtering, sorting, and pagination capabilities for users. Given that React Aria's table lacks pagination, I find the middle option redundant.

@tcortega Yes, you're corret. To clarify, actually I was not specifically talking about Table in shadcn UI. But rather some options people can choose at the moment. Therefore, the necessity will depends on the person needing the components.

**Comment by multiwebinc** [comment]
> TanStack already offers accessibility and is extremely user-friendly

@tcortega Actually TanStack [does not offer accessibility](https://github.com/TanStack/table/issues/1143#issuecomment-464186246) (straight from its author), so if we want to follow the same philosophy as Radix, we would need to code accessibility ourselves. I have no idea what that would entail, if it's just a few lines of code, or hundreds.

**Comment by mhaidarhanif** [comment]
Whoa and what just shipped is also the Data Table with TanStack Table

https://ui.shadcn.com/examples/tasks
https://ui.shadcn.com/docs/components/data-table
