### ISSUE TITLE
Feature Request: Multiselect component / multiselect support on select component

### ISSUE THREAD

**Issue by serzhan181** [shadcn/ui#233]
I think it's moderately common component. At some point or another you will need multi-select option. I experimented with how i can it make shadcnui-ish, and come up with something like this. What do you think?
![изображение](https://user-images.githubusercontent.com/67381256/233795994-94ec8732-601a-4c5e-846b-3e94341c3562.png)
![изображение](https://user-images.githubusercontent.com/67381256/233796011-0c6b2332-08db-40ca-bdc6-f5368683d074.png)
![изображение](https://user-images.githubusercontent.com/67381256/233796095-40876baf-d685-4202-acd4-f1e23e7aefb7.png)

**Comment by its-monotype** [comment]
#66

**Comment by serzhan181** [comment]
https://github.com/shadcn/ui/issues/66
