### ISSUE TITLE
[CLI]: Remember path 

### ISSUE THREAD

**Issue by Rawnly** [shadcn/ui#236]
It would be nice if the default prompt option when asking for the components path could be the last one used in the current project. this could be achieved via `conf` or any other similar package, just by keeping a hashmap of `cwd` and chosen path.

I'm available to open a PR for this if it's appreciated :)

**Comment by shadcn** [comment]
Definitely interesting in a PR. I'm looking into this as well but it'd be great to see other solutions as well. Go for it.

**Comment by Rawnly** [comment]
I recently implemented a similar feature in [another tool](https://github.com/rawnly/gh-linear) so I’m kinda fresh on this topic 😅
