### ISSUE TITLE
Use with Sveltekit and Vite

### ISSUE THREAD

**Issue by addi00000** [shadcn/ui#254]
Example usage for Sveltekit and tailwind please?

**Comment by puneet-sarhali** [comment]
You cannot use it with svelte kit because it uses Radix Primitives under the hood, which are only for React.

**Comment by addi00000** [comment]
Understood. Thanks.

**Comment by breadadams** [comment]
I've yet to try it, but it _might_ be possible to use this with Svelte via the following port of Radix: https://github.com/TGlide/radix-svelte

**Comment by addi00000** [comment]
> Edit: Now possible via https://github.com/huntabyte/shadcn-svelte

I love you  <3
