### ISSUE TITLE
Undocumented crash on Server component using 'asChild' prop

### ISSUE THREAD

**Issue by greidinger-reis** [shadcn/ui#263]
When using `<Button/>` `asChild` prop inside a server component, a error is thrown, because it uses a ref.
Would be nice to have a disclaimer that using this prop needs a "use client" in the docs: https://ui.shadcn.com/docs/components/button#link

Alternatively add  "use client" to `<Button/>` component.

**Comment by emrosenf** [comment]
This was recently fixed upstream: https://github.com/radix-ui/primitives/pull/2116

You can update your `slot` dependency to the release candidate
