### ISSUE TITLE
Where is the license file?

### ISSUE THREAD

**Issue by hamza512b** [shadcn/ui#28]
In readme it says `Licensed under the MIT license`. But there is no license in place. Is this project even open source?

**Comment by baddhidurgarao** [comment]
[Buy Github Followers](https://baddhi.shop/product/buy-github-followers/) or [Buy Github Stars](https://baddhi.shop/product/buy-github-followers/) from Baddhi Shop

**Comment by drupov** [comment]
> [Buy Github Followers](https://baddhi.shop/product/buy-github-followers/) or [Buy Github Stars](https://baddhi.shop/product/buy-github-followers/) from Baddhi Shop

LOL!

**Comment by baddhidurgarao** [comment]
We're providing great services at lowest price, our services are not from bots, so kindly check it now.

**Comment by drupov** [comment]
Appreciate your efforts, but how is that relevant to the current "Where is the license file"-issue in https://github.com/shadcn/ui?

**Comment by baddhidurgarao** [comment]
nope but we're trying to share our products to github users and developers.

**Comment by shadcn** [comment]
@baddhidurgarao Don't spam please or we will have to report you. Thank you.

**Comment by baddhidurgarao** [comment]
Sorry, please share our product on your community, thank you for your support.

**Comment by baddhidurgarao** [comment]
I appreciate you @shadcn
