### ISSUE TITLE
Create a separate Combobox (Autocomplete) component or make it searchable

### ISSUE THREAD

**Issue by dev-SR** [shadcn/ui#280]
Currently, the `Combobox` component can only be found under the `Command ` component documentation. It would be better if the Combobox component had its own separate documentation page or, at the very least, was searchable.

Alternatively, if it is not feasible to create a separate page, it would be helpful to make the Combobox component searchable (as it can't be found by searching) within the existing documentation.

**Comment by shadcn** [comment]
Agreed. On it.

**Comment by shadcn** [comment]
@dev-SR Ready for review:

Combobox: https://ui-git-docs-combobox-datepicker-shadcn-pro.vercel.app/docs/components/combobox

I've also moved the date picker while at it: https://ui-git-docs-combobox-datepicker-shadcn-pro.vercel.app/docs/components/date-picker

**Comment by dev-SR** [comment]
Great❤, still the current implementation of the Combobox component is not as reusable as it could be, and there is a need for more control over the `width `of the `PopoverContent`

**Comment by shadcn** [comment]
You can set the width using `<PopoverContent className="w-[400px]" />`.

See my comment [here](https://github.com/shadcn/ui/pull/283#issuecomment-1532887942) on making a resubale combobox.
