### ISSUE TITLE
Module not found: Can't resolve '@radix-ui/react-slot'

### ISSUE THREAD

**Issue by Satindar31** [shadcn/ui#288]
I'm getting the error `Module not found: Can't resolve '@radix-ui/react-slot'` when using the Button provided.
![image](https://user-images.githubusercontent.com/73517520/235979206-be0314ec-6581-488b-ae34-6bbec18af071.png)
![image](https://user-images.githubusercontent.com/73517520/235979292-23f7226a-05dc-450f-b4cf-99da53642f10.png)

**Comment by its-monotype** [comment]
#259

**Comment by softmarshmallow** [comment]
Still having this issue with CLI ?

**Comment by gpietro** [comment]
experiencing same issue
