### ISSUE TITLE
Scroll does not reset when changing component view

### ISSUE THREAD

**Issue by JuaniSilva** [shadcn/ui#3]
When going from one component to another the scroll does not reset to the top.
![brave_bpjDWTNSH8](https://user-images.githubusercontent.com/69092286/214375074-bec9e317-e7fd-4fe8-9f58-0b385ce9777f.gif)

**Comment by mertcanaltin** [comment]
many thanks for your feedback @JuaniSilva 
this seems like a normal flow, shall we do some improvement here? @shadcn

**Comment by mertcanaltin** [comment]
![Alt Text](https://s3.gifyu.com/images/chrome-capture-2023-0-24.gif)

**Comment by mertcanaltin** [comment]
> It looks like this is a known issue in Next.js 13 app dir. Let's keep an eye on https://github.com/vercel/next.js/issues/42492
> 
> 
> 
> @mertcanaltin I'll check the PR.

ok i will follow it ❤️🚀

**Comment by JuaniSilva** [comment]
Update: now everything goes to the top even if the content didn't change 
![brave_Vxn0AWfgfJ](https://user-images.githubusercontent.com/69092286/222931229-fcc30c77-1ea3-4fd9-b50b-1cd9ce611a81.gif)

**Comment by shadcn** [comment]
This is fixed. Thanks everyone.
