### ISSUE TITLE
react + vite 

### ISSUE THREAD

**Issue by ahmedRSA** [shadcn/ui#301]
how can i use this with reactjs ??

**Comment by stimw** [comment]
just follow the installation docs

**Comment by F-PTS** [comment]
Yes, there's absolutely no problem with using it with react and vite.

You can close the issue

**Comment by puneet-sarhali** [comment]
Also don't forget to follow Tailwind CSS guide after initial vite setup:
https://tailwindcss.com/docs/guides/vite

Path aliasing did not work for me as described in the manual docs, and had to manually change the file imports to "../.." syntax.

Also modify tailwind.config.js for react instead of next.js
```diff
export default {
  content: [
-     "app/**/*.{ts,tsx}", 
-     "components/**/*.{ts,tsx}"
+    "./index.html",
+.   "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {},
  plugins: [],
}
```

**Comment by ahmedRSA** [comment]
> Also don't forget to follow Tailwind CSS guide after initial vite setup: https://tailwindcss.com/docs/guides/vite
> 
> Path aliasing did not work for me as described in the manual docs, and had to manually change the file imports to "../.." syntax.
> 
> Also modify tailwind.config.js for react instead of next.js
> 
> ```diff
> export default {
>   content: [
> -     "app/**/*.{ts,tsx}", 
> -     "components/**/*.{ts,tsx}"
> +    "./index.html",
> +.   "./src/**/*.{js,ts,jsx,tsx}",
>   ],
>   theme: {},
>   plugins: [],
> }
> ```

Thanks, i beat up my head for hours setting up path alias did u found any solution?

**Comment by tuminzee** [comment]
I think your issue was resolved @ahmedRSA 
if so can you please close the issue 👼🏼

**Comment by Rawnly** [comment]
> Path aliasing did not work for me as described in the manual docs, and had to manually change the file imports to "../.." syntax.

Hey @puneet-sarhali you might find this useful: https://github.com/aleclarson/vite-tsconfig-paths

**Comment by tcortega** [comment]
There is a repository created by shadcn for it, although it is not updated.
https://github.com/shadcn/vite-template

It is somewhat broken, and I have a fork that actually works for you to use out of the box:
https://github.com/tcortega/vite-template

Last time I checked it worked out.

**Comment by ahmedRSA** [comment]
> There is a repository created by shadcn for it, although it is not updated. https://github.com/shadcn/vite-template
> 
> It is somewhat broken, and I have a fork that actually works for you to use out of the box: https://github.com/tcortega/vite-template
> 
> Last time I checked it worked out.

thanks for this.

**Comment by CyrusZei** [comment]
> There is a repository created by shadcn for it, although it is not updated. https://github.com/shadcn/vite-template
> 
> It is somewhat broken, and I have a fork that actually works for you to use out of the box: https://github.com/tcortega/vite-template
> 
> Last time I checked it worked out.

ofc he did!! love it that he did thought of this, True developer

**Comment by Znoy108x** [comment]
> Yes, although shadcn UI was created with next.js in mind, there's absolutely no issues when using it with react and vite.
> 
> follow setup guides from vite: https://vitejs.dev/guide/
> 
> and then follow the Manual Installation from the shadcn/ui kit: https://ui.shadcn.com/docs/installation
> 
> if you have any questions go ahead, if not please close the issue :)

if followed all the steps mentioned by docs but still @ folder is creating outside src, how can i create that inside src??
<img width="171" alt="image" src="https://github.com/shadcn-ui/ui/assets/75539409/813d9b56-a97b-4bf8-8e31-794083b4c267">

<img width="388" alt="image" src="https://github.com/shadcn-ui/ui/assets/75539409/27ca5a03-5397-4b4c-82ab-f3cf55a62263">

<img width="360" alt="image" src="https://github.com/shadcn-ui/ui/assets/75539409/2a0499ab-ca0f-4421-8a3e-4213f3b63daa">

**Comment by jagadeesh-k-ti** [comment]
> > Yes, although shadcn UI was created with next.js in mind, there's absolutely no issues when using it with react and vite.
> > follow setup guides from vite: https://vitejs.dev/guide/
> > and then follow the Manual Installation from the shadcn/ui kit: https://ui.shadcn.com/docs/installation
> > if you have any questions go ahead, if not please close the issue :)
> 
> if followed all the steps mentioned by docs but still @ folder is creating outside src, how can i create that inside src?? <img alt="image" width="171" src="https://private-user-images.githubusercontent.com/75539409/280508655-813d9b56-a97b-4bf8-8e31-794083b4c267.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MDkxODQsIm5iZiI6MTcwMzYwODg4NCwicGF0aCI6Ii83NTUzOTQwOS8yODA1MDg2NTUtODEzZDliNTYtYTk3Yi00YmY4LThlMzEtNzk0MDgzYjRjMjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE2NDEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwY2EwMDhkZGYzYjgyMDViZDA3MmRjMzc2ZWNiYjcxMDdkZGYyMTg2M2E0MzY2MzljODNkYmI5Zjk2NzQxOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cnowSbtLBi7sXyV57sYIcSzDkzpMhjf9vq_ixnPbZOA">
> <img alt="image" width="388" src="https://private-user-images.githubusercontent.com/75539409/280508664-27ca5a03-5397-4b4c-82ab-f3cf55a62263.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MDkxODQsIm5iZiI6MTcwMzYwODg4NCwicGF0aCI6Ii83NTUzOTQwOS8yODA1MDg2NjQtMjdjYTVhMDMtNTM5Ny00YjRjLTgyYWItZjNjZjU1YTYyMjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE2NDEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiODg5YmRkNWE2YjU5OTM4MGRmYTkxMmM4YWQyMjVlYWFjMTZmY2M5YjYyYmFmM2NmMjE2MGY1NTMxOWQ2NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JgJBmkidYQLwZZ2t6hrfDk_Yr8QTiTOPR-8tL2_PdCM"> <img alt="image" width="360" src="https://private-user-images.githubusercontent.com/75539409/280508666-2a0499ab-ca0f-4421-8a3e-4213f3b63daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MDkxODQsIm5iZiI6MTcwMzYwODg4NCwicGF0aCI6Ii83NTUzOTQwOS8yODA1MDg2NjYtMmEwNDk5YWItY2EwZi00NDIxLThhM2UtNDIxM2YzYjYzZGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE2NDEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZWQ3NDMzNWU1MmVjNmJlMTg4ZDZjNTUwZDA4ZmYxYWJkMGMyOWZjYjFiZGRlODUyMDQ3YTIyNmNhMDNlNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VZqqjJPjkQzZOKLc_Ju_7_swKf6BWm_XS6jUAr8x4cM">

same thing

to fix (idk if we are even supposed to fix this "bug"), you can replace `./src` with `./@/*` in both your `vite.config.js` and `tsconfig.json`

**Comment by Lxdovic** [comment]
> if followed all the steps mentioned by docs but still @ folder is creating outside src, how can i create that inside src?? 

Dont know if that would help since you posted this a few months ago but your tsconfig.json is wrong but that's an easy mistake to make, baseUrl and path are supposed to be in compilerOptions here's my tsconfig.json

```json
{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,

    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",

    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    
    /* here */
    "baseUrl": ".",
    "paths": {
      "@/*": [
        "./src/*"
      ]
    }
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }],
}
```

**Comment by lalitx17** [comment]
It took me a while to figure out how to use Shadcn with react and vite, even with the documentation. Here is what worked for me. 

components.json
`{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "src/index.css",
    "baseColor": "slate",
    "cssVariables": false,
    "prefix": ""
  },
  "aliases": {
    "components": "src/components",
    "utils": "src/lib/utils"
  }
}`


vite.config.ts
`import path from "path"
import react from "@vitejs/plugin-react"
import { defineConfig } from "vite"

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
})`


adding the bit to tsconfig.json
`"baseUrl": ".",
    "paths": {
      "@/*": [
        "./src/*"
      ]
    },`

Folder Structure
![image](https://github.com/shadcn-ui/ui/assets/98456811/02e60585-b41e-460f-aa80-3b6dd5ce92ab)

React function imports
![image](https://github.com/shadcn-ui/ui/assets/98456811/f17513a5-16e9-4817-b2cc-4bdbc62057ee)

**Comment by bluedusk** [comment]
The document is very misleading,  it has to be 

```
   "components": "src/components",
    "utils": "src/lib/utils"
```
