### ISSUE TITLE
the website is error

### ISSUE THREAD

**Issue by DroganC** [shadcn/ui#302]
the website is error

**Comment by giordifungula** [comment]
are you running the https://github.com/shadcn/next-template template?
Im also creating a template now and running the server, it seems to give an error and is not clear where its coming from.
The most readable error im getting is "ReferenceError: AbortSignal is not defined" which when I search for AbortSignal its not defined anywhere? @DroganC Is this the same for you?

**Comment by dimitrisnl** [comment]
I think he's referring to the website. I visit it with safari and get
```
e.at is not a function
```
