### ISSUE TITLE
Toast documentation **Out of date**

### ISSUE THREAD

**Issue by strat-ileris** [shadcn/ui#307]
The toast documentation is out of date.

**Comment by Natchii59** [comment]
Can you describe what is obsolete?

**Comment by kevenleone** [comment]
@Natchii59 I've been trying to use and notice the same

Documentation say 

> Add the``` <Toaster /> ``` component to your app.

> The <Toaster /> component is where your toasts are displayed. You can place it anywhere in your app, but it's recommended to place it at the root of your app.



```
import { Toaster } from "@/components/ui/toaster"

export default function App({ Component, pageProps }) {
  return (
    <>
      <Component {...pageProps} />
      <Toaster />
    </>
  )
}
```

But the command `npx shadcn-ui add toast` does not adds the Toaster Component

**Comment by kevenleone** [comment]
Probably it's related to absence of Toaster component, if so, there's already those issues opened 

https://github.com/shadcn/ui/issues/238
https://github.com/shadcn/ui/issues/234

And the fix was sent here: https://github.com/shadcn/ui/pull/243
