### ISSUE TITLE
 use shadcn ui in jsx

### ISSUE THREAD

**Issue by Ebibeck** [shadcn/ui#308]
cant use shadcn in jsx

**Comment by abhinav-anshul** [comment]
Shadcn can be used with jsx. What problems are you facing?

**Comment by Ebibeck** [comment]
Sorry about that... My import alias was the problem... Fixed it ... Thanks👍

**Comment by Crymfox** [comment]
How did you fix your alias problem?

**Comment by Ebibeck** [comment]
> How did you fix your alias problem?

Easy update your shadcn package and it will work out of the box... at least that's is how I did it ... you can just import it straight to your jsx
