### ISSUE TITLE
Accordion: When the text in the AccordionTrigger is long, it causes the icon to become very small 

### ISSUE THREAD

**Issue by jocarrd** [shadcn/ui#316]
When the text in the AccordionTrigger is long, it causes the icon to become very small 

![image](https://user-images.githubusercontent.com/55456507/236794383-f0d089c4-d118-46b5-9b8c-807e24147d08.png)

**Comment by its-monotype** [comment]
Probably just need to add shrink-0 class to icon

**Comment by jocarrd** [comment]
> Probably just need to add shrink-0 class to icon
You are right, it works! They should add it so that more users don't experience the same issue! Thank you.

**Comment by MohamedMujtaba** [comment]
I made a pull  request to fix this issue

**Comment by tuminzee** [comment]
I sort of saw this and was going to work on this 
good work @MohamedMujtaba 🔥

**Comment by MohamedMujtaba** [comment]
@tuminzee thank you 💖

**Comment by jocarrd** [comment]
@shadcn
