### ISSUE TITLE
Typo: DataTable

### ISSUE THREAD

**Issue by cnrstvns** [shadcn/ui#323]
https://ui.shadcn.com/docs/components/data-table#pagination

Under step 2 of pagination, `Reusable` is mis-spelled `Resusable`. Happy to open a PR :)

<img width="501" alt="image" src="https://github.com/shadcn/ui/assets/25255502/55e287de-2aad-41aa-bd06-34315a4e0bdb">

Cheers

**Comment by shadcn** [comment]
I believe this was fixed in #324. Closing...

Thanks @cnrstvns
