### ISSUE TITLE
Bug: Filter in DataTable

### ISSUE THREAD

**Issue by Natchii59** [shadcn/ui#325]
Filter badges do not display on the sample tasks page.

<img width="621" alt="image" src="https://github.com/shadcn/ui/assets/96394660/da647231-3af3-4955-bf5f-1c56b794b632">

**Comment by Natchii59** [comment]
https://github.com/shadcn/ui/assets/96394660/a5baf515-71d5-48e9-957d-8871b67498c3

@shadcn In Arc Browser, it's a responsive problem.

**Comment by shadcn** [comment]
Fixed it. Thank you.

**Comment by JayBox325** [comment]
I'm looking at implementing this style of filtering in my project, it would be great to see examples for dropdown and toggle filters as per the tasks example in the docs.

**Comment by neos04** [comment]
> I'm looking at implementing this style of filtering in my project, it would be great to see examples for dropdown and toggle filters as per the tasks example in the docs.

Same, i tried using the github code but for some reason, the statuses are unclickable and i don't know why....

![image](https://github.com/shadcn-ui/ui/assets/101072035/3ca2d7c0-dec1-4dc7-9a90-ab10cb104223)

**Comment by digitaltim-de** [comment]
I think its bugged because of next server and client side update.

**Comment by laduniestu** [comment]
> > I'm looking at implementing this style of filtering in my project, it would be great to see examples for dropdown and toggle filters as per the tasks example in the docs.
> 
> Same, i tried using the github code but for some reason, the statuses are unclickable and i don't know why....
> 
> ![image](https://private-user-images.githubusercontent.com/101072035/312530251-3ca2d7c0-dec1-4dc7-9a90-ab10cb104223.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTAzMTAsIm5iZiI6MTcxMDgxMDAxMCwicGF0aCI6Ii8xMDEwNzIwMzUvMzEyNTMwMjUxLTNjYTJkN2MwLWRlYzEtNGRjNy05YTkwLWFiMTBjYjEwNDIyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwMTAwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZWNkM2Y0ZDk0MDI0ZjdlMjQwMjRiMGU0YTBjZmI5MTk5MzQyZGM3NjQ5YzRkZTIyN2UwYjM4N2E4NTE5M2Q0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aSuQvn1vPkH_UlBVbeHpkR8H3fETlFb_VC_LiwhGZkI)

I also experienced the same thing
![Screenshot 2024-03-19 at 09 02 06](https://github.com/shadcn-ui/ui/assets/44757637/5c672649-bd0f-4896-9afc-662f1d3d4c42)

**Comment by florianmascaro** [comment]
I've found a solution here https://github.com/shadcn-ui/ui/issues/3024

**Comment by neos04** [comment]
> I've found a solution here #3024

You're a life saver G 🙏🏽. It works.
