### ISSUE TITLE
Dialog box aligns differently on different screens, also modal is aligned using items start initially

### ISSUE THREAD

**Issue by kshitijmohan15** [shadcn/ui#35]
## This is how the dialog box looks on small screens 
![image](https://user-images.githubusercontent.com/92985242/215319920-b4cab138-a88f-4679-9b56-8685506f9f99.png)

The dialog box does not seem to be aligned to 'flex-start' on the small screens and nor are the corners rounded

It works better, in my opinion, on making the following changes:
![image](https://user-images.githubusercontent.com/92985242/215320395-ed4c540e-66e3-48ce-91e3-93c263e67c36.png)
![image](https://user-images.githubusercontent.com/92985242/215320404-ae23b8cd-7db2-4d6a-88d2-9dbe3cd0f85e.png)

After the changes suggested above, this is the result:
![image](https://user-images.githubusercontent.com/92985242/215320445-89a4fb9c-0f6a-4a34-a8ce-589c0f06554f.png)

I would like to congratulate you on this library, especially because I have started actively using this in my projects. 

Reach out to me on twitter: @KshitijMohan14

**Comment by shadcn** [comment]
@kshitijmohan15 So the reason I did that is to allow space for the mobile keyboard. Check out the screenshot below. The keyboard takes the lower space while the dialog is moved to the top.

<img src="https://user-images.githubusercontent.com/124599/215320886-8b222573-79a2-4dbd-8ab6-d0f0fdb421af.png" width="340" />

**Comment by kshitijmohan15** [comment]
Makes sense
