### ISSUE TITLE
Bug: Using toast with data table cause a weird behaviour

### ISSUE THREAD

**Issue by jacksonnadar** [shadcn/ui#365]
https://github.com/shadcn/ui/assets/49579140/55d82edf-25d4-44cf-81e4-396f40a2a94d

I was following the guide from official [shadcn's ](https://ui.shadcn.com/docs/components/toast#toaster) website. 

And after I implemented datatable I wanted to try out toast. But when I try to call toas() the toast did not work and instead it rearranges rows in datatable. I have attached a video showing that.

I tried moving toast calls to entirely different part of the code base e.g App.tsx but still found the same behaviour.  

Here is a link for the code [sandbox](https://codesandbox.io/p/github/jacksonnadar/shadcn-codesandbox/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clhqh8fvj000a3b6kkoedb0h6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clhqh8fvj000c3b6kl6a3tqrn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B19.225584861642147%252C80.77441513835785%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clhqh8fvj000a3b6kkoedb0h6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clhqh8fvj00093b6k7akysw3o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clhqh8fvj000a3b6kkoedb0h6%2522%252C%2522activeTabId%2522%253A%2522clhqh8fvj00093b6k7akysw3o%2522%257D%252C%2522clhqh8fvj000c3b6kl6a3tqrn%2522%253A%257B%2522id%2522%253A%2522clhqh8fvj000c3b6kl6a3tqrn%2522%252C%2522activeTabId%2522%253A%2522clhqh8t0800ai3b6kdicvga9u%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clhqh8qsj005n3b6k91sbkgvs%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A4000%252C%2522id%2522%253A%2522clhqh8t0800ai3b6kdicvga9u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%252C%2522actionBarPosition%2522%253A%2522docked%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

Thank You everyone

**Comment by LucasHang** [comment]
I also had a strange time when trying to call `toast()` inside a setState function. Something like that:
```typescript
setCounter(state => {
    toast('Some toast message');
    
    return state + 1;
});
```

In my situation it caused a reender and the toast got called twice. I'm almost sure it is just some state bug I caused myself, but since you also had some bug with the hook, I decided to share my experience.

**Comment by jacksonnadar** [comment]
@LucasHang But I am not event setting the state.

**Comment by LucasHang** [comment]
> @LucasHang But I am not event setting the state.

I understand it may not be the same problem, but the effect caused seems the same. Perhaps toast() causes a complete reender making your table change.

Now, looking your code sandbox I failed to notice the `<Toaster />` provider in your App.tsx. If your main code is in the same way, that is must certainly the problem.

Take a look on the shadcn-ui docs about the Toast, to see about the Toaster you have to expand the "manual installation" accordion: https://ui.shadcn.com/docs/components/toast

**Comment by LucasHang** [comment]
Right. Now we have another thing.

In your `App.tsx` there is a line calling `const { toast } = useToast();`. Whenever `toast()` is called, components (and its children) that reference it will be revalidated and/or reendered, and that seems to be happening with App.tsx component, making the DataTable component generate a new set or random 10 rows every time you trigger `toast()`.

One way to validate that behavior is, in Transactions.tsx component, to move the part of the code that generates the rows outside the component function, or put it inside a `useEffect` (there is a lot of ways actually).

But the problem itself I think lies on that App.tsx line `const { toast } = useToast();`, it is not used so could be removed.

**Comment by LucasHang** [comment]
To further undestand that situation in React, I suggest taking a look about [React Context](https://react.dev/reference/react/createContext) and a bit of how [React revalidation and reender works](https://javascript.plainenglish.io/how-react-works-under-the-hood-277356c95e3d).

The approach used by shadcn in `useToast` is very interesting and a bit different from what I have seen, but this two subjects I mentioned should help you to understand it more deeply.

**Comment by jacksonnadar** [comment]
@LucasHang You are so right. Thank You so much. I moved the row generation code outside the component function and it worked fine.

So now do I close the issue?

**Comment by LucasHang** [comment]
I'm glad that I could help
