### ISSUE TITLE
Add config.ts to let the CLI know about components path

### ISSUE THREAD

**Issue by ahkhanjani** [shadcn/ui#369]
It's kind of painful to type the path on every component install. Sometimes the path is too long or there's a typo etc. A config file in the root directory could solve this issue. Something like this:

```ts
// shadcnui.config.ts

export default {
	components: "./src/components/ui/shadcn"
};
```

If the file exists the CLI shouldn't ask for a path.

**Comment by shadcn** [comment]
@ahkhanjani Yep we're looking into it in #245

**Comment by albbus-stack** [comment]
It should be a pretty straightforward change at the bottom of the cli index.ts:

```typescript
async function promptForDestinationDir() {
  if (!fs.existsSync('./shadcnui.config.ts')) {
    const { dir } = await prompts([
      {
        type: "text",
        name: "dir",
        message: "Where would you like to install the component(s)?",
        initial: "./components/ui",
      },
    ])
    
    return dir
  }

  const config = require('./shadcnui.config.ts')
  
  return config.componentsPath
}
```

I don't really know how to parse a .config.ts file, this is just an idea.
