### ISSUE TITLE
Current form setup re-registers fields multiple times

### ISSUE THREAD

**Issue by Moshyfawn** [shadcn/ui#382]
# Description

The `FormField` component renders the [`Controller`](https://react-hook-form.com/docs/usecontroller/controller) component from the React Hook Form library, which internally utilizes the [`useController`](https://react-hook-form.com/docs/usecontroller) hook. Additionally, the `useFormField` hook from the same library also utilizes the [`useController`](https://react-hook-form.com/docs/usecontroller) hook. However, when using the `FormField` component, the field with the same name passed to the [`Controller`](https://react-hook-form.com/docs/usecontroller/controller) component is re-registered by the `useFormField` hook, even though it is already registered. This practice is discouraged by React Hook Form because it can cause unwanted and unrelated re-renders of multiple components due to field value subscriptions. Furthermore, overriding fields is not supported by React Hook Form, leading to unpredictable behavior.

# Proposal

To avoid the issues described above, it is recommended to access form states such as values or validation states in a more granular manner using the [`useWatch`](https://react-hook-form.com/docs/usewatch) and [`useFormState`](https://react-hook-form.com/docs/useformstate) hooks. If there is a requirement to subscribe to the state of a specific field, the [`getFieldState`](https://react-hook-form.com/docs/useform/getfieldstate) method can be utilized to create a subscription.

I'm going to create a PR that implements the described solution.

_Disclaimer: I'm well aware that it's going to add +1 to the current 69 PRs (nice)_ 🤭
<img width="185" alt="image" src="https://github.com/shadcn/ui/assets/16290753/e73751dc-47c9-402f-bc63-dcbf50a77624">

**Comment by shadcn** [comment]
> To avoid the issues described above, it is recommended to access form states such as values or validation states in a more granular manner using the [useWatch](https://react-hook-form.com/docs/usewatch) and [useFormState](https://react-hook-form.com/docs/useformstate) hooks. If there is a requirement to subscribe to the state of a specific field, the [getFieldState](https://react-hook-form.com/docs/useform/getfieldstate) method can be utilized to create a subscription.

I did now know about this. Thanks @Moshyfawn
