### ISSUE TITLE
Navigation Menu broken in small screen

### ISSUE THREAD

**Issue by huangfulei** [shadcn/ui#40]
when changing the screen size to be smaller, the navigation content disappeared. see below:

![nav menu issue](https://user-images.githubusercontent.com/35687313/215463428-0344ee0b-e0c1-443c-9a26-7a0a850f7ab7.gif)

**Comment by shadcn** [comment]
I'll take a look at this. Thank you.

**Comment by krishraiturkar** [comment]
Just do less navigator margin left

**Comment by yazaldefilimonepinto** [comment]
@shadcn i resolved it in #59
