### ISSUE TITLE
How to set an accordion item always open by default

### ISSUE THREAD

**Issue by msp1123** [shadcn/ui#405]
I was using accordion in navigations and if the user selected menu is inside accordion I have to open the accordion with a condition. How to achieve this?

**Comment by Moshyfawn** [comment]
If you use uncontrolled [Accordion](https://www.radix-ui.com/docs/primitives/components/accordion#accordion), you can provide `defaultValue` based on the currently active link.

Something like

```jsx
const gettingStartedSectionLinks = ["introduction", "installation"]

function selectSectionByLink (link) {
  if (gettingStartedSectionLinks.include(link)) return "getting-started"
  if (...) return ...
  return ""
}

// INFO: use params is an imaginary hook that gets you the current route dynamic param value string
const { link } = useParams()

<Accordion defaultValue={selectSectionByLink(link)}>...</Accordion>
```

The logic for determining the current section or open accordion item can obviously be refactored. But, I hope this example conveys the overall concept.

**Comment by shadcn** [comment]
@msp1123 what @Moshyfawn said. Use the `defaultValue` prop.

**Comment by msp1123** [comment]
that helps. thanks a lot
