### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by huangfulei** [shadcn/ui#412]
anyone getting this in the Button component?

![Screenshot 2023-05-22 at 15 47 21](https://github.com/shadcn/ui/assets/35687313/71465984-7137-44c7-bd95-f5c5eabf3478)

TS2322: Type '{ disabled?: boolean | undefined; form?: string | undefined; formAction?: string | undefined; formEncType?: string | undefined; formMethod?: string | undefined; formNoValidate?: boolean | undefined; ... 265 more ...; ref: ForwardedRef<...>; }' is not assignable to type 'SlotProps'.   Types of property 'dangerouslySetInnerHTML' are incompatible.     Type '{ __html: string | TrustedHTML; } | undefined' is not assignable to type '{ __html: string; } | undefined'.       Type '{ __html: string | TrustedHTML; }' is not assignable to type '{ __html: string; }'.         Types of property '__html' are incompatible.           Type 'string | TrustedHTML' is not assignable to type 'string'.             Type 'TrustedHTML' is not assignable to type 'string'.

could be my custom lint rules, but I couldn't find out

**Comment by Nemestos** [comment]
Same error.

**Comment by OfficialCRUGG** [comment]
@huangfulei Why did you close this? Did you find a fix? If yes, please share it.

**Comment by huangfulei** [comment]
> @huangfulei Why did you close this? Did you find a fix? If yes, please share it.

I couldn't figure out what is the problem, could be one of my lint dependency version. I ended up creating a new repo using t3 stack cli and use their recommended configs

**Comment by jgdovin** [comment]
In case anyone else runs into this, I'm not sure of the exact cause, but I do have a workaround. I have no use for the asChild prop so I removed it... The new section from lines 36-51 look like this in my `components/ui/button.tsx`

`export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, ...props }, ref) => {
    return (
      <button
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    )
  }
)`

**Comment by rajarju** [comment]
This looks like an issue with Radix.
I managed to override it with  `string` to get past the error.
```tsx
export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
  VariantProps<typeof buttonVariants> {
  asChild?: boolean,
  dangerouslySetInnerHTML?: {
    __html: string;
  }
}
```
