### ISSUE TITLE
ScrollArea in PopoverContent

### ISSUE THREAD

**Issue by serzhan181** [shadcn/ui#415]
I want to have pretty scroll bar in my popover content
![изображение](https://github.com/shadcn/ui/assets/67381256/060480ad-1bf2-4dc4-b6fb-9b39f1be7afc)

but the scroll just doesnt show up. The code looks like this:

```tsx
...
<PopoverContent
className="relative p-0"
        sideOffset={16}
        align="end"
        asChild
>
    <ScrollArea className="rounded-sm w-96 min-h-[256px] max-h-[520px]">
        // lots of content
    </ScrollArea>
</PopoverContent>
...
```

**Comment by Danazumi** [comment]
if you need a scroll u could just add  ```overflow-y-auto``` to your tailwind styling, so when height of your items exceeds the height of the scroll area scroll bar appears, and also if you want to hide the scrollbar but maintain the scroll feature just  add
 ```@layer utilities {
    @variants responsive {
        .scrollbar-none::-webkit-scrollbar {
            display: none;
        }
    }
}```
to your globals.css and now include the scrollbar-none in your tailwind style, and you are good.

**Comment by Danazumi** [comment]
if you need a scroll u could just add ```overflow-y-auto```  to your tailwind styling, so when height of your items exceeds the height of the scroll area scroll bar appears, and also if you want to hide the scrollbar but maintain the scroll feature just add

```
   @variants responsive {
       .scrollbar-none::-webkit-scrollbar {
           display: none;
       }
   }
}
```

to your globals.css and now include the scrollbar-none in your tailwind style, and you are good.
