### ISSUE TITLE
TabsPrimitive.Trigger text unreadable in Dark Mode

### ISSUE THREAD

**Issue by eliamaino-fp** [shadcn/ui#42]
When dark mode is on, the text of the active Tabs Trigger is not readable. It is set to `text-slate-700` and in dark mode the bg is set to `dark:data-[state=active]:bg-slate-900`.

![Screenshot 2023-01-30 at 19 04 54](https://user-images.githubusercontent.com/25059869/215558828-4685371a-2278-46a0-ab20-7ea6d7ccb9b0.png)

**Comment by krishraiturkar** [comment]
Just change the color of font
