### ISSUE TITLE
Uncontrolled changing into controlled at an input in a react hook form.

### ISSUE THREAD

**Issue by thepeterkovacs** [shadcn/ui#427]
Using the input component in a react hook form triggers the error:

"A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component."

This happens, because the **field** object's value property turns from _undefined_ to an actual value once the input is used.

**Comment by shadcn** [comment]
@thepeterkovacs You have to set a defaultValue. See my comment here: https://github.com/shadcn/ui/issues/410#issuecomment-1556705052

**Comment by thepeterkovacs** [comment]
Wow, thanks for the quick answer! Cheers!
