### ISSUE TITLE
DropDownMenuSubContent text color mismatch

### ISSUE THREAD

**Issue by kevinmitch14** [shadcn/ui#44]
Colors for `DropDownMenuSubContent` does not match colors for `DropDownMenuContent`.

SubContent has darker text in 'light mode', and lighter text in 'dark mode'.

<img width="372" alt="Screenshot 2023-01-30 at 20 27 32" src="https://user-images.githubusercontent.com/55989505/215619924-5dec4497-fd5b-45aa-86ce-b5d73ee01909.png">
<img width="409" alt="Screenshot 2023-01-30 at 20 28 06" src="https://user-images.githubusercontent.com/55989505/215619998-3f40ff53-9bde-44c0-8453-7891c433363a.png">

**Comment by kevinmitch14** [comment]
Closes #45

**Comment by angadvirk** [comment]
Ran into a similar issue today... fixed by changing 'text-on-popover' to 'text-popover-foreground' in `DropdownMenuSubContent` inside `dropdown-menu.tsx`
