### ISSUE TITLE
Installed components uses kebab-casing for file names?

### ISSUE THREAD

**Issue by tedawf** [shadcn/ui#440]
Sorry if this seems like a non-issue, but is there a reason behind the kebab-casing for installed components? Most react components adopt the PascalCasing naming convention for both class names and file names. 

Just curious behind this approach.

**Comment by its-monotype** [comment]
@shadcn Also it's a great approach because you will never need to deal with issues with case mismatches on git

**Comment by tedawf** [comment]
I see. Anyways, it's not a big deal to rename them as the components are copy-pasted. Thanks, this satisfied my curiosity.

**Comment by syntaxlexx** [comment]
With the new `components.json` file, can we have an option to opt into PascalCase? The `components.json` file is pretty dope.
