### ISSUE TITLE
React-hook-form ComboBox dropdown doesn't Scroll

### ISSUE THREAD

**Issue by tdugan-vbtech** [shadcn/ui#444]
I'm trying to use a ComboBox in a react-hook-form to allow a user to select a state (50 values). The type to search portion works great but a user isn't able to scroll to the bottom of the list manually.

Screenshot:
![image](https://github.com/shadcn/ui/assets/131622321/a4f13a52-297c-48a8-83d5-fcbdb034c6dd)

Code snippet:
`{/* Example state array */}
export const stateAbbreviations = [
  {
    value: 'al',
    label: 'Alabama',
  },
...
 ] as const;

{/* State */}
                  <FormField
                    control={form.control}
                    name="permAddressState"
                    render={({ field }) => (
                      <FormItem className="flex flex-col">
                        <FormLabel>State</FormLabel>
                        <Popover>
                          <PopoverTrigger asChild>
                            <FormControl>
                              <Button
                                variant="outline"
                                role="combobox"
                                className={cn(
                                  "w-[184px] justify-between",
                                  !field.value && "text-muted-foreground"
                                )}
                              >
                                {field.value
                                  ? stateAbbreviations.find(
                                      (stateAbbreviation) =>
                                        stateAbbreviation.label +
                                          " - " +
                                          stateAbbreviation.value ===
                                        stateAbbreviation.label +
                                          " - " +
                                          field.value
                                    )?.label
                                  : "Select state"}
                                <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                              </Button>
                            </FormControl>
                          </PopoverTrigger>
                          <PopoverContent className="w-[184px] p-0">
                            <Command>
                              <CommandInput placeholder="Search states..." />
                              <CommandEmpty>No state found.</CommandEmpty>
                              <CommandGroup>
                                {stateAbbreviations.map((stateAbbreviation) => (
                                  <CommandItem
                                    value={stateAbbreviation.value}
                                    key={stateAbbreviation.value}
                                    onSelect={(value) => {
                                      form.setValue("permAddressState", value);
                                    }}
                                  >
                                    <Check
                                      className={cn(
                                        "mr-2 h-4 w-4",
                                        stateAbbreviation.value === field.value
                                          ? "opacity-100"
                                          : "opacity-0"
                                      )}
                                    />
                                    {stateAbbreviation.label}
                                  </CommandItem>
                                ))}
                              </CommandGroup>
                            </Command>
                          </PopoverContent>
                        </Popover>
                        <FormMessage />
                      </FormItem>
                    )}
                  />`

**Comment by uncvrd** [comment]
Is this form in a dialog by chance? I had to use the `container` prop on the `Portal` element to reference the Dialog the form element is in (it defaults to `document.body`). Maybe that helps get you on the right track?

**Comment by olsio** [comment]
You can simply wrap your `CommandItems` list entries in a `<ScrollArea />`

**Comment by tdugan-vbtech** [comment]
> You can simply wrap your `CommandItems` list entries in a `<ScrollArea />`

@olsio Thank you, that worked perfectly! I'm mad I didn't think of that myself. I guess I was overthinking it...

**Comment by max-programming** [comment]
@uncvrd What did you do can you please explain in detail?
I am having issues with `Command` inside `Dialog`

**Comment by SweydManaf** [comment]
> Is this form in a dialog by chance? I had to use the `container` prop on the `Portal` element to reference the Dialog the form element is in (it defaults to `document.body`). Maybe that helps get you on the right track?

can u explain better?

**Comment by BeyramTaglietti** [comment]
Found an easy [solution](https://github.com/shadcn-ui/ui/issues/1511#issuecomment-1810682366) on #1511
