### ISSUE TITLE
Found Bug on alert icon(docs page)

### ISSUE THREAD

**Issue by febriaricandra** [shadcn/ui#449]
<img width="784" alt="gambar" src="https://github.com/shadcn/ui/assets/52602319/276e7a7f-1a3c-4965-b541-b9325a35071d">
holla, can you fix alert icon in the docs page? thank you :)

**Comment by Moshyfawn** [comment]
Next time, please provide a URL to the documentation and information about your reproduction environment. It would greatly help us troubleshoot the issue.

It seems that this issue is reproducible in Firefox 114, which I assume is due to a lack of support for the CSS `:has()` selector.
