### ISSUE TITLE
Adding an icon while using the Button component will result in the following error. I have not found a solution yet. Is this a bug

### ISSUE THREAD

**Issue by LRboyz** [shadcn/ui#450]
![image](https://github.com/shadcn/ui/assets/48092353/c7c80c57-7dbf-402c-aca7-45ad50b6ae69)

**Comment by shadcn** [comment]
Hmm where is `Icon` imported from?

**Comment by LRboyz** [comment]
lucide-react， I follow the same approach as the Taxonomy project. If I remove the icon, it will not report this error
