### ISSUE TITLE
Find a replacement for cmdk in Combobox

### ISSUE THREAD

**Issue by olsio** [shadcn/ui#460]
The combobox is a nice addition but the cmdk usage adds some unexpected behaviors and makes it overall not the best solution.

- cmdk trims and lowercases values which requires workarounds to knowledge of this behavior
- cmdk only searches values not labels

I don't know if there are any accessible and stylable components to replace cmdk but the current combobox has lots of caveats as is.

**Comment by austinm911** [comment]
@olsio What about downshift? I do know other people have had issues trying to integrate it  with Radix. I wish there was a multi select combobox with this library

**Comment by olsio** [comment]
Downshift looks good but I think comboboxes are quite complicated and would require a bigger effort. There is a reason why radix doesn't have it. I personally opted to use https://react-select.com/home and just tried to copy the styles as much as possible. So maybe this is also your solution.

**Comment by mariomeissner** [comment]
Cmdk also lacks 'creatable' support, which IMO is quite important.
