### ISSUE TITLE
Issue with HSL color conversion in styles.css

### ISSUE THREAD

**Issue by SahilMahadwar** [shadcn/ui#469]
I encountered an issue while trying to update the primary color of a button in the `styles.css` file using HSL values. Here's the process I followed:

1. I selected the hex color `#9333EA`, which corresponds to "Purple 600" in the default Tailwind theme.
2. To convert it to HSL, I used an [online converter](https://htmlcolors.com/hex-to-hsl) and it returned this hsl values `hsl(271, 81%, 56%)`.
3. I updated the `--primary` CSS variable in `styles.css` to `--primary: 271, 81%, 56% ;`.

Initially, the color appeared as expected. However, upon hovering over the button, it went completely blank.

I repeated this process with different colors from tailwind theme and encountered the same issue consistently.

Please let me know if any further information is needed to resolve this issue. Thank you!

default
![image](https://github.com/shadcn/ui/assets/37921525/131f942b-54d5-45a7-8db0-8d008b58d6b9)

on hover
![image](https://github.com/shadcn/ui/assets/37921525/5d0159a8-36bd-4a29-b568-1688ee803d69)

**Comment by ridafkih** [comment]
This is because the `Button` element supplied by `shadcn-ui` has a `hover:bg-accent` utility class on it, so if you don't override this value or set it to the colour you want, it will become the HSL value provided to the `--accent` CSS variable.

You should modify `--accent` in `globals.css` in order to mitigate this issue.

**Comment by SahilMahadwar** [comment]
@ridafkih hey I tried it, but it didn't work, and the default variant doesn't seem to be using the hover accent color.

```js
    variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90",
        destructive:
          "bg-destructive text-destructive-foreground hover:bg-destructive/90",
        outline:
          "border border-input hover:bg-accent hover:text-accent-foreground",
        secondary:
          "bg-secondary text-secondary-foreground hover:bg-secondary/80",
        ghost: "hover:bg-accent hover:text-accent-foreground",
        link: "underline-offset-4 hover:underline text-primary",
      },
```

**Comment by mikeeggertsen** [comment]
@SahilMahadwar Made the same mistake as you...
You just need to remove the commas -> ```--primary: 271 81% 56%;```

**Comment by SahilMahadwar** [comment]
@mikeeggertsen Yup that was it i feel so dumb now stupid commas

Thank you :)
