### ISSUE TITLE
Dynamic Dialog error infinite loop

### ISSUE THREAD

**Issue by Dave-Patsy** [shadcn/ui#476]
"next": "^13.3.0",
"react": "^18.2.0",
Node.js v18.14.1

I want to create a dynamic modal/dialog to display a list of exercises for a routine. However, the way I tried creates an infinite loop of api call/rerenders.

I have a dialog with the async function called  inside the content.
 ```
<DialogContent>
       <GetRoutine id={id}/>
 </DialogContent>
```

```function GetRoutine({ id }: props): Promise<JSX.Element>```
```
'use client'

import { getRoutineCircuits } from "@/utils/api/client/exercise"

type props = {
    id:string
}
export default async function GetRoutine({id}:props) {

  const routine = await getRoutineCircuits(id)
  return (
    <>
        {routine.map((ele,idx)=>(
            <div key={idx}>
                {ele.type}
            </div>
        ))}
    
    </>
  )
}
```

is there a way to do this with shadcn?

**Comment by Moshyfawn** [comment]
I don't think you can call async components with the `"use client";` directive
