### ISSUE TITLE
Button asChild example directs to a broken link

### ISSUE THREAD

**Issue by kevinmitch14** [shadcn/ui#477]
The [asChild button example](https://ui.shadcn.com/docs/components/button#as-child) links to https://ui.shadcn.com/login which is a broken link.

This leads to poor UX and can also be detrimental for SEO, broken links indicate outdated content and lead to crawling/indexing issues.

PR incoming

**Comment by jakhsu** [comment]
Hi,
The asChild button is still directing to a broken link. Any news on the PR?
