### ISSUE TITLE
select component bubble problem in mobile device

### ISSUE THREAD

**Issue by hevi1991** [shadcn/ui#486]
I have encountered an issue with the select component.

Reproduction steps:
Simulate a click on a mobile device in browser developer mode.
After clicking on the select component, its pop-up layer will appear. When I select an option from it, it triggers another component that is covered by the pop-up layer.

This is most likely caused by event bubbling, but I do not know how to modify it.

This issue also exists in radix ui.

**Comment by hevi1991** [comment]
```
import React from "react";
import * as Select from "@radix-ui/react-select";
import classnames from "classnames";
import {
  CheckIcon,
  ChevronDownIcon,
  ChevronUpIcon,
} from "@radix-ui/react-icons";

const SelectDemo = () => {
  const [open, setOpen] = React.useState(true);

  return (
    <div>
      <Select.Root>
        <Select.Trigger
          className="inline-flex items-center justify-center rounded px-[15px] text-[13px] leading-none h-[35px] gap-[5px] bg-white text-violet11 shadow-[0_2px_10px] shadow-black/10 hover:bg-mauve3 focus:shadow-[0_0_0_2px] focus:shadow-black data-[placeholder]:text-violet9 outline-none"
          aria-label="Food"
        >
          <Select.Value placeholder="Select a fruit…" />
          <Select.Icon className="text-violet11">
            <ChevronDownIcon />
          </Select.Icon>
        </Select.Trigger>
        <Select.Portal>
          <Select.Content className="overflow-hidden bg-white rounded-md shadow-[0px_10px_38px_-10px_rgba(22,_23,_24,_0.35),0px_10px_20px_-15px_rgba(22,_23,_24,_0.2)]">
            <Select.ScrollUpButton className="flex items-center justify-center h-[25px] bg-white text-violet11 cursor-default">
              <ChevronUpIcon />
            </Select.ScrollUpButton>
            <Select.Viewport className="p-[5px]">
              <Select.Group>
                <Select.Label className="px-[25px] text-xs leading-[25px] text-mauve11">
                  Fruits
                </Select.Label>
                <SelectItem asChild>
                  <div value="apple" onTouchEnd={(e) => console.log(e)}>
                    Apple
                  </div>
                </SelectItem>
              </Select.Group>
            </Select.Viewport>
            <Select.ScrollDownButton className="flex items-center justify-center h-[25px] bg-white text-violet11 cursor-default">
              <ChevronDownIcon />
            </Select.ScrollDownButton>
          </Select.Content>
        </Select.Portal>
      </Select.Root>

      <div className="flex flex-col">
        {Array(50)
          .fill(null)
          .map((_, i) => (
            <button onClick={(e) => alert(i)} key={i}>
              {i + 1}XXXXXXXXXXXXX
            </button>
          ))}
      </div>
    </div>
  );
};

const SelectItem = React.forwardRef(
  ({ children, className, ...props }, forwardedRef) => {
    return (
      <Select.Item
        className={classnames(
          "text-[13px] leading-none text-violet11 rounded-[3px] flex items-center h-[25px] pr-[35px] pl-[25px] relative select-none data-[disabled]:text-mauve8 data-[disabled]:pointer-events-none data-[highlighted]:outline-none data-[highlighted]:bg-violet9 data-[highlighted]:text-violet1",
          className
        )}
        {...props}
        ref={forwardedRef}
      >
        <Select.ItemText>{children}</Select.ItemText>
        <Select.ItemIndicator className="absolute left-0 w-[25px] inline-flex items-center justify-center">
          <CheckIcon />
        </Select.ItemIndicator>
      </Select.Item>
    );
  }
);

export default SelectDemo;
```

**Comment by ssatriya** [comment]
Did you manage to fix that problem?

**Comment by nativedone** [comment]
The code below did work for me. Thanks @hevi1991 

A similar solution could be backed in @shadcn?

My use case was a Select with a clickable link nearby. When the user selected an option, the mobile event bubbled up to the nearby link causing unintentional navigation. 

>   let elRef = useRef(null);
>   if (ref !== null) {
>     elRef = ref as typeof elRef;
>   }
> 
>   useEffect(() => {
>     if (elRef.current === null) {
>       return;
>     }
>     (elRef.current as HTMLElement).ontouchend = (e: any) => {
>       e.preventDefault();
>     };
>   }, []);

**Comment by ssatriya** [comment]
> The code below did work for me. Thanks @hevi1991
> 
> A similar solution could be backed in @shadcn?
> 
> My use case was a Select with a clickable link nearby. When the user selected an option, the mobile event bubbled up to the nearby link causing unintentional navigation.
> 
> > let elRef = useRef(null);
> > if (ref !== null) {
> > elRef = ref as typeof elRef;
> > }
> > useEffect(() => {
> > if (elRef.current === null) {
> > return;
> > }
> > (elRef.current as HTMLElement).ontouchend = (e: any) => {
> > e.preventDefault();
> > };
> > }, []);

I added the code below and it fix my problem. Found it somewhere

`<SelectContent
                        ref={(ref) => {
                          if (!ref) return;
                          ref.ontouchstart = (e) => {
                            e.preventDefault();
                          };
                        }}
                      >`

**Comment by KunalSin9h** [comment]
@ssatriya thanks, worked for me

![image](https://github.com/shadcn-ui/ui/assets/82411321/e7ccee3a-add5-4b01-ad08-37e9c338ace5)

**Comment by ssatriya** [comment]
> @ssatriya thanks, worked for me
> 
> ![image](https://user-images.githubusercontent.com/82411321/260084498-e7ccee3a-add5-4b01-ad08-37e9c338ace5.png)

Nice, glad to hear that.

**Comment by maykon-oliveira** [comment]
Thanks 💫

**Comment by psygo** [comment]
Please merge a PR based on this.

**Comment by heygwangjin** [comment]
Thanks

**Comment by nk1tz** [comment]
Took @ssatriya hotfix and slapped it inside SelectContent like this:
```tsx
const SelectContent = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Content>
>(({ className, children, position = 'popper', ...props }, forwardedRef) => (
  <SelectPrimitive.Portal>
    <SelectPrimitive.Content
      ref={(instance) => {
        if (typeof forwardedRef === 'function') {
          forwardedRef(instance)
        } else if (forwardedRef) {
          forwardedRef.current = instance
        }
        if (!instance) return
        // THIS IS A HACK
        instance.ontouchstart = (e) => {
          e.preventDefault()
        }
      }}
      className={cn(
        'relative z-50 max-h-96 min-w-[8rem] overflow-hidden rounded-md border bg-popover text-popover-foreground shadow-md data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2',
        position === 'popper' &&
          'data-[side=bottom]:translate-y-1 data-[side=left]:-translate-x-1 data-[side=right]:translate-x-1 data-[side=top]:-translate-y-1',
        className,
      )}
      position={position}
      {...props}
    >
      <SelectScrollUpButton />
      <SelectPrimitive.Viewport
        className={cn(
          'p-1',
          position === 'popper' &&
            'h-[var(--radix-select-trigger-height)] w-full min-w-[var(--radix-select-trigger-width)]',
        )}
      >
        {children}
      </SelectPrimitive.Viewport>
      <SelectScrollDownButton />
    </SelectPrimitive.Content>
  </SelectPrimitive.Portal>
))
```

**Comment by rohithroshan-pss** [comment]
const SelectTrigger = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Trigger>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Trigger> &
    CustomSelectTriggerProps
>(({ className, children, isClear, onClear, ...props }, ref) => (
  <SelectPrimitive.Trigger
    ref={ref}
    className={cn(
      "border-input bg-background ring-offset-background placeholder:text-muted-foreground focus:ring-ring flex h-10 w-full items-center justify-between rounded-md border px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50",
      className,
    )}
    {...props}
  >
    {children}

    {isClear ? (
      <div className='flex items-center pl-2'>
        <CircleX
          onClick={(e) => {
            e.stopPropagation()
            onClear && onClear()
          }}
          className='h-4 w-4 cursor-pointer text-red-500'
        />
      </div>
    ) : (
      <SelectPrimitive.Icon asChild>
        <ChevronDown className='h-4 w-4 opacity-50' />
      </SelectPrimitive.Icon>
    )}
  </SelectPrimitive.Trigger>
))

SelectTrigger.displayName = SelectPrimitive.Trigger.displayName


the onClick is not working please anyone share a solution
