### ISSUE TITLE
Hydration error when using the Authentication example code

### ISSUE THREAD

**Issue by nickdotht** [shadcn/ui#492]
I like the Authentication example on the home page and decided to use it to go quicker with the authentication part of my app. But I'm getting the following error after setting it up:

![Screenshot from 2023-05-29 12-16-12](https://github.com/shadcn/ui/assets/3984265/272bcdb1-2fdb-44c3-9397-fa02f97af122)

I haven't modified the code and here you can see what line 22 looks like in `user-auth-form.tsx`:

![Screenshot from 2023-05-29 12-18-19](https://github.com/shadcn/ui/assets/3984265/a729dec0-38c8-43b7-8297-a727e30419c6)

## How to reproduce

1. Check out the [Authentication code example](https://github.com/shadcn/ui/tree/main/apps/www/app/examples/authentication)
2. Create an `auth` directory under `app` with a `page.tsx` file with the content of the `page.tsx` file from the example code
3. Create a `user-auth-form.tsx` file under `components` with the content of the `./components/user-auth-form.tsx` file from the example code
4. If you don't have them yet, add the Input and Label UI components
5. Set up the `spinner` icon with the Loader2 component from `lucide-react` in the `components/icons.tsx` file

**Comment by nickdotht** [comment]
@dan5py Ah, wow. That was indeed the issue. I've been banging my head on the table since, thinking I did something wrong. I use the LastPass Chrome extension.

Thanks a lot for taking the time to reply and helping me figure this out.

**Comment by NixBiks** [comment]
@nickdotht did you find a way to disable LastPass on localhost? I've got the same issue and don't want to switch browser for it really.

**Comment by NixBiks** [comment]
@dan5py nit sufficient unfortunately - LastPass still running in Firefox. 

Sorry for using this thread for a LastPass extension issue really. But others might have the same issue here of course.
