### ISSUE TITLE
Problem with setting dark mode in dropdown menu

### ISSUE THREAD

**Issue by sandheep45** [shadcn/ui#522]
I am using shadcn ui in a blitz js project which is working fine with other components but the class "dark:bg-[#1e1e2d] dark:text-gray-500" is getting applied to `DropdownMenu` component

```
<DropdownMenu>
      <DropdownMenuTrigger asChild className="mx-5">
        <Button>Action</Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent className="dark:bg-[#1e1e2d] dark:text-gray-500">
        <DropdownMenuItem>Edit</DropdownMenuItem>
        <DropdownMenuItem>Delete</DropdownMenuItem>
      </DropdownMenuContent>
 </DropdownMenu>
```

**Comment by ahmad1702** [comment]
This seems to be working as expected. I made a <a href="https://codesandbox.io/p/github/ahmad1702/dropdown-shadcn-test/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clifgt01x000b3b6o0fxnk41u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clifgt01x000d3b6o2chdw1s6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clifgt01x000b3b6o0fxnk41u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clifgt01x000a3b6onakd5kny%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clifgt01x000b3b6o0fxnk41u%2522%252C%2522activeTabId%2522%253A%2522clifgt01x000a3b6onakd5kny%2522%257D%252C%2522clifgt01x000d3b6o2chdw1s6%2522%253A%257B%2522id%2522%253A%2522clifgt01x000d3b6o2chdw1s6%2522%252C%2522activeTabId%2522%253A%2522clifgtje400d43b6o6okqpvqk%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clifgtgw700823b6ooais50wi%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clifgtje400d43b6o6okqpvqk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D">sandbox example here</a>. Adding a className to the `DropdownMenuContent` component changes the style of the wrapper of the popup. You can check out [radix-ui's content api reference](https://www.radix-ui.com/docs/primitives/components/dropdown-menu#content) for more. If the class name is really not rendering on the right html element, I would recommend opening an issue for radix-ui using [this link](https://github.com/radix-ui/primitives/issues/new?assignees=&labels=&projects=&template=Bug_report.md).

**Comment by sandheep45** [comment]
I guess the problem in my case is I am using manual installation process. Could you please let me know what point I am missing @ahmad1702. [Here](https://github.com/sandheep45/shopnest-admin) is the github link of my project

**Comment by sandheep45** [comment]
I found the solution. I was not using `next-themes` package along with shadcn-ui. After I installed the package and did required changes, the app is supporting dark and light theme now

**Comment by sboagy** [comment]
@sandheep45 I have this same problem, only when the NavigationMenuContent is over a data table ("@/components/ui/table").  For the life of me, I can't figure out how to make it non-transparent for the data table elements.  Just letting you know, and in case other's are seeing a similar problem.
