### ISSUE TITLE
Property 'displayName' does not exist on type '...'

### ISSUE THREAD

**Issue by hoandt** [shadcn/ui#536]
It seems that the displayName property is not directly assignable to the component in this case:

const Table = React.forwardRef<
  HTMLTableElement,
  React.HTMLAttributes<HTMLTableElement>
>(({ className, ...props }, ref) => (
  <div className="w-full overflow-auto">
    <table
      ref={ref}
      className={cn("w-full caption-bottom text-sm", className)}
      {...props}
    />
  </div>
))
Table. displayName = "Table"

Property 'displayName' does not exist on type '(props: HTMLAttributes<HTMLTableElement> & RefAttributes<HTMLTableElement>) => ReactElement<any, string | JSXElementConstructor<...>> | null'.ts(2339)

Please guide me...

**Comment by hoandt** [comment]
I think it conflicts with ESLink or something. But I'm not sure how to fix it.

**Comment by hoandt** [comment]
I don't know, but I use this, it's fixed:

export const A = forwardRef(function A(props, ref) {
  return <>....</>
});

**Comment by brooksa-chemtest** [comment]
This issue has just popped up for me on all of my components.

I have no idea what I might have done to cause this.

Has anyone else encountered this and know how to fix?

**Comment by brandnholl** [comment]
This issue also just popped up for me

**Comment by brandnholl** [comment]
Fixed by adding semi-colons to the end of each display name declaration.
`MyComponent.displayName = 'MyComponent';`

**Comment by hoandt** [comment]
No ideas. I leave them there.

> Fixed by adding semi-colons to the end of each display name declaration. `MyComponent.displayName = 'MyComponent';`

Nice, but not working for me :(

**Comment by hoandt** [comment]
NO, I was stupid. I redeclared the forwardRef in global.d.types. Remove it and things will work again.... Man.. I'm crying

import * as React from "react";

declare module "react" {
  function forwardRef<T, P = {}>(
    render: (props: P, ref: React.Ref<T>) => React.ReactElement | null
  ): (props: P & React.RefAttributes<T>) => React.ReactElement | null;
}

**Comment by hoandt** [comment]
Closed.

**Comment by liuhe2020** [comment]
I had this issue, then I updated all my packages and the errors were gone, super strange.

**Comment by usmanashrf** [comment]
> NO, I was stupid. I redeclared the forwardRef in global.d.types. Remove it and things will work again.... Man.. I'm crying
> 
> import * as React from "react";
> 
> declare module "react" { function forwardRef<T, P = {}>( render: (props: P, ref: React.Ref) => React.ReactElement | null ): (props: P & React.RefAttributes) => React.ReactElement | null; }

@hoandt  Didn't get it can you explain how you solve it?
 I'm facing the same issue related "displayName" and I'm not able to deploy it on Vercel

**Comment by hoandt** [comment]
Can you try to find this in your entire project?
```
declare module "react" {
```
function forwardRef
```

**Comment by johnLamberts** [comment]
> NO, I was stupid. I redeclared the forwardRef in global.d.types. Remove it and things will work again.... Man.. I'm crying
> 
> import * as React from "react";
> 
> declare module "react" { function forwardRef<T, P = {}>( render: (props: P, ref: React.Ref) => React.ReactElement | null ): (props: P & React.RefAttributes) => React.ReactElement | null; }

This is not working though, I already declare a module for this to override the forwardRef, but it was still getting me type error.

**Comment by ashkanrastin** [comment]
why is this closed? whats the solution if you do want to have a redeclaration for forward ref?

**Comment by kikienelsone** [comment]
I fixed it with "const App: React.FC"
