### ISSUE TITLE
Inputs doesn't respond to interactions

### ISSUE THREAD

**Issue by Mahmoudgalalz** [shadcn/ui#538]
I have in input inside the Dialog and I cannot write anything inside it

**Comment by Mahmoudgalalz** [comment]
it's not related to Dialog at all, its the input component if it does have a value, you cannot override this value which is not should to behave like that

**Comment by redac** [comment]
Could you please post the code snippet you're having a problem with?

**Comment by redac** [comment]
Well, that's normal. 

In React, if you're using a controlled component, you need to handle the onChange event and update the component's state to reflect the changes in the input field. (refer to this [react.dev docs article](https://react.dev/reference/react-dom/components/input#controlling-an-input-with-a-state-variable))

```jsx
<input type="text" value={value} onChange={handleChange} />
```

**Comment by Mahmoudgalalz** [comment]
I'm write some React for just get the things done
so that's why I asked is that the expected behavior or not

Thanks @redac
