### ISSUE TITLE
Accordion content open on default

### ISSUE THREAD

**Issue by itaim18** [shadcn/ui#540]
I have created an accordion and I need the contents to be open on default.
Is there a way to implement it?

**Comment by schardev** [comment]
It's just radix-ui under the hood, check this out: https://www.radix-ui.com/docs/primitives/components/accordion#expanded-by-default

**Comment by itaim18** [comment]
Yeah I know.
 for some reason this didn't work for me.
But in trying, I manged to do it by passing down an array of the values of the accordion items to the `defaultValue` in the accordion(root) component.
This issue can be closed, as for me.

**Comment by itaim18** [comment]
Yeah I know.
 for some reason this didn't work for me.
But in trying, I manged to do it by passing down an array of the values of the accordion items to the `defaultValue` in the accordion(root) component.
This issue can be closed, as for me.

**Comment by DystopianDisco** [comment]
@marcelrzd - depending on your accordionItem values add the first value to your accordion 

I.e. <Accordion type="single" collapsible **defaultValue="item-1"**> 

the accordion content will now be open as default.

**Comment by RabiRoshan** [comment]
Adding my 2 cents:
If you're using "multiple" as the type for the <Accordion> component and wish to have all or several accordions open by default, you can supply an array of the default values to the <Accordion> parent.

**For instance:**
```
<Accordion type="multiple" defaultValue={["value-1", "value-2"]}>
    <AccordionItem value="value-1">...</AccordionItem>
    <AccordionItem value="value-2">...</AccordionItem>
    <AccordionItem value="value-3">...</AccordionItem>
</Accordion>
```

Happy coding! 🥳
Thanks to @itaim18 and @DystopianDisco !!

Although this is mentioned in the Radix UI Accordion documentation (https://www.radix-ui.com/primitives/docs/components/accordion#root), incorporating this detail in the Examples section would greatly enhance clarity.

![Screenshot 2023-12-29 at 4 17 40 PM](https://github.com/shadcn-ui/ui/assets/19388268/623ea652-908a-4440-b0a2-3c78e8c06d4b)

**Comment by KWodarczyk** [comment]
it would be much easier if we could just set property on AccordionItem  like isOpen={true} and don't need to do anything else
