### ISSUE TITLE
Cannot use Select in a table cell

### ISSUE THREAD

**Issue by pawelmisiura** [shadcn/ui#547]
Hey, I'm really enjoying using Shadcn but I've run into an issue. I cannot put a Select component inside a TableCell. Input  works fine. 

This works fine: 
`            <Table>
              <TableCaption>
                Add a PRICE and DURATION for each coat type and size combination you offer this
                service for
              </TableCaption>
              <TableHeader>
                <TableRow>
                  <TableHead></TableHead>
                  <TableHead className='text-center'>XS</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow className='min-h-96'>
                  <TableCell className='font-medium'>Wire</TableCell>
                  <TableCell>
                    <Input />
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
`
Select component does not show up in the table:
`
            <Table>
              <TableCaption>
                Add a PRICE and DURATION for each coat type and size combination you offer this
                service for
              </TableCaption>
              <TableHeader>
                <TableRow>
                  <TableHead></TableHead>
                  <TableHead className='text-center'>XS</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow className='min-h-96'>
                  <TableCell className='font-medium'>Wire</TableCell>
                  <TableCell>
                    <Select />
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
`
Does anyone know a work around for this issue? Thanks

**Comment by sammyhass** [comment]
You need to pass children to the Select component to specify a trigger and options to select:
```jsx
<Select>
  <SelectTrigger className="w-[180px]">
    <SelectValue placeholder="Select a fruit" />
  </SelectTrigger>
  <SelectContent>
    <SelectGroup>
      <SelectLabel>Fruits</SelectLabel>
      <SelectItem value="apple">Apple</SelectItem>
      <SelectItem value="banana">Banana</SelectItem>
      <SelectItem value="blueberry">Blueberry</SelectItem>
      <SelectItem value="grapes">Grapes</SelectItem>
      <SelectItem value="pineapple">Pineapple</SelectItem>
    </SelectGroup>
  </SelectContent>
</Select>
```

This should work fine in a table:
```jsx
<Table>
  <TableCaption>
    Add a PRICE and DURATION for each coat type and size combination you
    offer this service for
  </TableCaption>
  <TableHeader>
    <TableRow>
      <TableHead></TableHead>
      <TableHead className="text-center">XS</TableHead>
    </TableRow>
  </TableHeader>
  <TableBody>
    <TableRow className="min-h-96">
      <TableCell className="font-medium">Wire</TableCell>
      <TableCell>
        <Select>
          <SelectTrigger className="w-[180px]">
            <SelectValue placeholder="Select a fruit" />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              <SelectLabel>Fruits</SelectLabel>
              <SelectItem value="apple">Apple</SelectItem>
              <SelectItem value="banana">Banana</SelectItem>
              <SelectItem value="blueberry">Blueberry</SelectItem>
              <SelectItem value="grapes">Grapes</SelectItem>
              <SelectItem value="pineapple">Pineapple</SelectItem>
            </SelectGroup>
          </SelectContent>
        </Select>
      </TableCell>
    </TableRow>
  </TableBody>
</Table>
```

Hope this helps!

**Comment by pawelmisiura** [comment]
Hey @sammyhass, see where I was going wrong. Many thanks!
