### ISSUE TITLE
tailwind opacity issue 

### ISSUE THREAD

**Issue by areebbbb** [shadcn/ui#560]
The utilization of "bg-primary/10" is not feasible in this case as it necessitates the inclusion of opacity using a comma separator, which is not supported by the Tailwind CSS framework out of the box.

**Comment by its-monotype** [comment]
Can you explain or provide an example?

**Comment by its-monotype** [comment]
Did you read the section about CSS variables: https://tailwindcss.com/docs/customizing-colors

**Comment by areebbbb** [comment]
![image](https://github.com/shadcn/ui/assets/62776869/9376f25b-4786-4567-81f9-9693624a8e4a)
Alpha values are missing legacy way works with hsl

**Comment by dan5py** [comment]
I don't understand what seems to be the issue here, could you explain yourself a little better and maybe provide an example?

**Comment by areebbbb** [comment]
I have made pr for it you can check it out https://github.com/shadcn/ui/pull/561
the modern way is not working with tailwind css 
or guide me and help me out over here I would really appreciate it. 
It is my first PR for any open-source project 🚀
