### ISSUE TITLE
Combobox is not working inside `Sheet`

### ISSUE THREAD

**Issue by hisamafahri** [shadcn/ui#579]
Using the [default combobox](https://ui.shadcn.com/docs/components/combobox) code, I can't select and search the values in the combobox at all.

```tsx
    <SheetContent>
      <SheetHeader>
        <SheetTitle>Title</SheetTitle>
        <SheetDescription>Description</SheetDescription>
      </SheetHeader>
      <div className="mt-6">
        <ComboboxDemo />
      </div>
    </SheetContent>
```

However, when I put the combobox outside the `<SheetContent />` everything works well.

Any idea how to solve this?

**Comment by joaom00** [comment]
Seems to be working here https://codesandbox.io/p/sandbox/fervent-browser-49s77n

**Comment by hisamafahri** [comment]
I am not really sure how it fixed it, but updating my `react-dom` dependecy solves it.

Thank you for the comment @joaom00 👍
