### ISSUE TITLE
shadcn-uirc

### ISSUE THREAD

**Issue by mdugue** [shadcn/ui#585]
Hey, I found in https://github.com/shadcn/ui/blob/main/packages/cli/src/index.ts, that it should be possible to adjust the CLIs default directories. Unfortunately I wasn't able to make it run in my project. 

I tried the `package.json` (see screenshot), `.shadcn-uirc` & `.shadcn-uirc.json` configs, but running 

`npx shadcn-ui add dropdown-menu` 

kept asking me 

`? Where would you like to install the component(s)? › ./components/ui`

Is there anything I am missing or a way for me to get more detailled error information?

Thanks a lot in advance!

<img width="467" alt="image" src="https://github.com/shadcn/ui/assets/894149/9c60a0f6-9e69-4dfe-ac50-9057de4e3cc9">

**Comment by dan5py** [comment]
All of the methods you tried work in the main branch. 
The config discovery was introduced two weeks ago in #245, but the new version has not been published yet.

**Comment by mdugue** [comment]
oh I see… I missed checking if it was published at all. Can't wait for it! Thanks @dan5py
