### ISSUE TITLE
Error after importing the DataTable component

### ISSUE THREAD

**Issue by chromaticmoe** [shadcn/ui#606]
Hi,

I just installed the Data Table component and followed the instructions: https://ui.shadcn.com/docs/components/data-table

But I'm getting an error on the import of { cn } from "@/lib/utils"

"Cannot find module '@/lib/utils' or its corresponding type declarations.ts(2307)"

I mean, technically I don't have such folder in my project. I don't understand why the component didn't include it as well upon installation. Am I missing something here?

**Comment by dan5py** [comment]
The `utils.ts` file is created when you run the `init` command of the shadcn-ui cli. Did you run `npx shadcn-ui init`?
