### ISSUE TITLE
TypeScript error

### ISSUE THREAD

**Issue by Ghoral** [shadcn/ui#609]
Hi,
Getting this typescript error while using components:

`'Card' cannot be used as a JSX component.
  Its return type 'ReactNode' is not a valid JSX element.
    Type 'undefined' is not assignable to type 'Element | null'.ts(2786)
(alias) const Card: React.ForwardRefExoticComponent<React.HTMLAttributes<HTMLDivElement> & React.RefAttributes<HTMLDivElement>>
import Card`

this is the import

`import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";`

**Comment by dan5py** [comment]
Did you make any changes to the card.tsx file?

**Comment by Ghoral** [comment]
@dan5py No I used it outside of Theme Provider..if it is wrapped inside theme provider than it works fine.

**Comment by dan5py** [comment]
Awesome!

**Comment by Ghoral** [comment]
Yes but that is the issue..we have components that are defined outside of the Theme wrapper and that is giving the issue.

**Comment by dan5py** [comment]
Do you have an example that I can see?

**Comment by Ghoral** [comment]
for some reason after configuring the path in tsconfig the error is gone. I should close the pr

**Comment by Ghoral** [comment]
Hi,
I have found the issue.
Check this screen shot. This happens when I config my type script like this 

`{
  "extends": "tsconfig/react-library.json",
  "include": ["components"],
  "exclude": ["node_modules", "dist", "build"],
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["components/ui/*"]
    }
  }
}
`

while there is not error if I do this 

`{
  "extends": "tsconfig/react-library.json",
  "include": [".", "components"],
  "exclude": ["dist", "build", "node_modules"],
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["components/*"]
    }
  }
}
`
<img width="600" alt="Screenshot 2023-06-18 at 21 52 45" src="https://github.com/shadcn/ui/assets/49188349/ad4fca1b-e2e1-4869-9fa3-2d537a3657a4">

**Comment by dan5py** [comment]
I assume you're using turborepo. This is the `tsconfig.json` file that I use in [my turborepo template](https://github.com/dan5py/turborepo-shadcn-ui) for the `ui` package:

```javascript
{
  "extends": "tsconfig/react-library.json",
  "include": ["."],
  "exclude": ["dist", "build", "node_modules"],
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./*"]
    }
  }
}
``` 

Be careful with your solution because `"paths": { "@*": ["./*"] }` means that `@/components` and `@components` would both resolve to the same folder, and this could lead to errors.
