### ISSUE TITLE
react-hook-form webpack error & tailwind doesn't compile from external ui package - HELP

### ISSUE THREAD

**Issue by DavidIlie** [shadcn/ui#619]
I am posting this on the relevant repositories as I do not know what to do.

I have a project with NextJS that I've started to work on which has a `ui` package with `tsup` and that contains tailwind based components via shadcn and one of the components is form using `react-hook-form`.

## Problem 1 - `react-hook-form`
When I use the form component, I get this error, even though I have configured tsup to do "use client"; and also in the component itself I am using "use client";

```TypeError: Cannot destructure property 'getFieldState' of '(0 , react_hook_form__WEBPACK_IMPORTED_MODULE_5__.useFormContext)(...)' as it is null.```

## Problem 2 - tailwind compiler not working
This might be my configuration error, but I've replicated the configuration from a monorepo with the [same setup as me](https://github.com/juliusmarminge/acme-corp/tree/main) in the NextJS tailwind compiler content to go `"../../packages/ui/src/**/*.{ts,tsx}"`.

The way I am testing it is with a button component from the UI package being rendered on the page:

<img width="242" alt="image" src="https://github.com/egoist/tsup/assets/47594764/708d4c51-4f97-41b9-8b5f-bafcb3d9c81a">

You can see that there is no styling on the button.

Any help would be appreciated, or at least some steps to the right direction. [Here is my project](https://github.com/DavidIlie/laundrey)

Thank you!

**Comment by dukeofsoftware** [comment]
any solution for problem 1?

**Comment by DavidIlie** [comment]
Make sure you aren't importing `Form` from directly from `react-hook-form`
