### ISSUE TITLE
Can't find Manual Installation for components anymore

### ISSUE THREAD

**Issue by savicaleksa** [shadcn/ui#642]
I don't see the Manual Installation tab anywhere, was this feature removed?

**Comment by shadcn** [comment]
Hmm I removed it in favor of the CLI but I can totally add it back!

**Comment by shadcn** [comment]
Do you mean the manual initialization for project or manual installation (copy and paste) of components?

**Comment by riviellocorey** [comment]
For my use case copy and paste of components.

**Comment by PedroMarquesFr** [comment]
I think is copy and paste the component, it was usefull

**Comment by shadcn** [comment]
OK I'll prioritize and add this back.

**Comment by savicaleksa** [comment]
Oh i get it now, thanks.

Since using the CLI is the go to method now, are we able to add components without initializing with the `init` command? I'm asking because I've already used some of your components and modified the css file with your variables, and I wouldn't like them to be changed after initialization.

By the way, thank you for helping all of us with your work!

**Comment by JoaoVictor6** [comment]
Here, a received this error:
![image](https://github.com/shadcn/ui/assets/68869379/bdd562de-3887-4ec9-8e3c-2199db27d154)

To work around this issue I accessed the `api/components`  endpoint and copy the content

**Comment by unmonk** [comment]
> Here, a received this error: ![image](https://user-images.githubusercontent.com/68869379/248056253-bdd562de-3887-4ec9-8e3c-2199db27d154.png)
> 
> To work around this issue I accessed the `api/components` endpoint and copy the content

There was an update path buried way down in the changelog page saying that the components.json is needed to use the CLI going forward.

https://ui.shadcn.com/docs/changelog#updating-your-project

**Comment by nathanhettige** [comment]
The cli isn't accessible through corporate VPN due to SSL cert issues :( 

Please add the manual components back, I really like how I could use it as a reference project.

**Comment by stimw** [comment]
"Manual installation" is the most essential part of the project

**Comment by MeonisRP** [comment]
You should definitely bring it back! I have troubles setting up the aliases in components.json, since my project is CRA and it has some issues with paths resolving

**Comment by simonmares** [comment]
CLI is cool, but "Manual installation" is super flexible when quickly adding first components to new project and/or updating / diffing already copy-pasted components. Also it's nice to be able to just see the radix-ui implementation. 

You can find it in the source (e.g. [form](https://github.com/shadcn/ui/blob/main/apps/www/registry/default/ui/form.tsx) that I was looking for), but having it on the web is a bit nicer. 

Thanks 🙏

**Comment by shadcn** [comment]
Manual installation is back. Thanks everyone for the feedback.

**Comment by unmonk** [comment]
Thanks for the quick turn around.

Looks like its just missing the npm install command for the dependencies that was on the old docs. 
Easy enough to figure out from the imports though.

**Comment by redbaron76** [comment]
Sorry but I don't see it...
No Manual installation is present on the online version of the site.

**Comment by savicaleksa** [comment]
> Sorry but I don't see it...
> No Manual installation is present on the online version of the site.

It is on the Installation part of the component page under the Manual tab

![Screenshot_2023-06-26-17-19-54-704_com.vivaldi.browser.jpg](https://github.com/shadcn/ui/assets/62035747/4d0344f6-08f2-4b6f-bd75-c956cbb9bd5c)

**Comment by redbaron76** [comment]
Sorry for the misunderstanding, but I was looking for the manual installation of the Library itself, not the component one.
I see the installation procedure only for Next.js, not the manual one.

thanks

**Comment by bunnypaws** [comment]
> Sorry for the misunderstanding, but I was looking for the manual installation of the Library itself, not the component one. I see the installation procedure only for Next.js, not the manual one.
> 
> thanks

these instructions don’t seem to exist at the moment- you can figure out how to set it up manually by looking at the code, but it would definitely be helpful especially for those who haven’t tried the library before to have more clarity on the installation

as well, @shadcn i’d add the style switching dropdown to the manual installation tab somewhere as it’s not immediately super clear that the code changes when you change the style!

**Comment by bunnypaws** [comment]
doesn’t look like there’s manual install for the form components either: https://ui.shadcn.com/docs/components/form

**Comment by saad-nkurunziza** [comment]
> doesn’t look like there’s manual install for the form components either: https://ui.shadcn.com/docs/components/form

Yeah not all components have a manual installation.
You should consider using the cli now
