### ISSUE TITLE
Init with new cli in js project

### ISSUE THREAD

**Issue by unmonk** [shadcn/ui#652]
I am working on a standard react project in JS.

I was able to initialize everything fine with the previous CLI, then I could use the Manual Install of the components and pull out the typescript. 

With the new CLI, it appears to be searching for tsconfig. 

Does the new CLI only init in a typescript environment?

Also missing the manual install from docs now is a bummer as stated in #642 

![image](https://github.com/shadcn/ui/assets/8887802/df899d88-8fbe-458e-848d-1a183e78d1f0)

**Comment by dan5py** [comment]
https://github.com/shadcn/ui/issues/642#issuecomment-1604074845

**Comment by dan5py** [comment]
> Does the new CLI only init in a typescript environment?

Yes, you need a TypeScript project to use the cli since the components are written in TS.

p.s. : The manual installation is back. https://github.com/shadcn/ui/issues/642#issuecomment-1604074845

**Comment by unmonk** [comment]
With manual install back, this can probably be closed,
