### ISSUE TITLE
<Alert> broken on firefox

### ISSUE THREAD

**Issue by chronark** [shadcn/ui#688]
See https://github.com/chronark/unkey/issues/60
and I have manually verified it in your docs using firefox
<img width="819" alt="CleanShot 2023-06-24 at 00 42 26@2x" src="https://github.com/shadcn/ui/assets/18246773/a74dffd7-701e-4048-964e-a7c73f6820e8">

**Comment by dan5py** [comment]
Duplicate of #627

**Comment by chronark** [comment]
my bad, thanks
