### ISSUE TITLE
How can I change the base color configuration ?

### ISSUE THREAD

**Issue by TrySquadDF** [shadcn/ui#698]
**components.json**

How can I change the baseColor ? If I try to change it nothing happens

```json{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "app/globals.css",
    "baseColor": "gray",
    "cssVariables": true
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  }
}
```

**Comment by TrySquadDF** [comment]
P.S I changed **baseColor** in components.json

**Comment by dan5py** [comment]
The `baseColor` has two functions:
- when the `cssVariables` is set to `false` it's used to change the colors in the component's classNames
- when the `cssVariables` is set to `true` it's used to generate the css variables inside the `globals.css` file

If you don't use the `cssVariables` when you add a new component, its base color will be the same of the one inside the configuration file. So if you want to change the base color you could just reinstall all the components (remember to add the `--overwrite` option). 

Otherwise, if you need the css variables, you must change the css file manually or run the `init` command again.

**Comment by bm9avan** [comment]
Neutral
    Gray
    Zinc
    Stone
    Slate
    
How to add color's other than the options provided such as Green, Blue, Yellow, etc.., while installing or later

**Comment by Dari4sho** [comment]
@bm9avan inside your `components.json` file,  do you have `cssVariables: true` set?
If so, you need to adjust your main css file (with `@layer base { ...` inside). 

Then you go to https://ui.shadcn.com/themes and click "Customize" and select a color. Next to the customize button, click "Copy code" and replace it with the layer in your css file.

**Comment by brunobely** [comment]
Doesn't look like https://ui.shadcn.com/themes supports any other type of gray than zinc?

**Comment by dan5py** [comment]
Not for the moment at least. It the meantime you can try to use some tools other people built for example https://shadcncolors.com by @rawestmoreland.

**Comment by cemremengu** [comment]
@dan5py  it used to support them though. There were gray and slate as well but not sure why they were removed.

**Comment by dan5py** [comment]
> [@dan5py](https://github.com/dan5py) it used to support them though. There were gray and slate as well but not sure why they were removed.

Yeah! Seems like they are disabled but I'm not sure why.
```ts
  {baseColors
    .filter(
      (theme) =>
        !["slate", "stone", "gray", "neutral"].includes(theme.name)
    )
```
https://github.com/shadcn-ui/ui/blob/5f7957ab51c3d929f322937147269ef3bdfeb472/apps/www/components/theme-customizer.tsx#L124C13-L128C16

Those colors have all the CSS variables set in [`registry-base-color.ts`](https://github.com/shadcn-ui/ui/blob/5f7957ab51c3d929f322937147269ef3bdfeb472/apps/www/registry/registry-base-colors.ts)

**Comment by dan5py** [comment]
Those colors have been filtered out in this commit.
https://github.com/shadcn-ui/ui/blob/bed277c54d9f31c6289cfd4477bbdb0f20481b41/apps/www/components/theme-customizer.tsx
