### ISSUE TITLE
Having page not found and all api routes not found to after shadcn/ui been added to the existing project

### ISSUE THREAD

**Issue by nelsonmandeladev** [shadcn/ui#699]
Juste added [shadcn/ui](https://ui.shadcn.com/) to an existing nextjs 13.4.6 project and all pages, and API routes are now showing not found, is the anything that I'm mistaking, please does someone have an idea on how to get out of this?
This is my actual project structure.

![image](https://github.com/shadcn/ui/assets/69842489/47b56bcc-a12a-49a4-b467-8d57d0a29e41)

**Comment by mehrabmp** [comment]
there is a bug in cli that creates another app folder in the root directory

**Comment by usmanashrf** [comment]
@mehrabmp Exactly it's creating a new app directory

**Comment by usmanashrf** [comment]
if your project don't have **src** directory then it'll not create any additional **app** directory, but if project contains src then it'll create new one outside src

**Comment by usmanashrf** [comment]
**Issue resolved** for me, 
it's creating new app directory because of **globals.css**. Change the default globals.css path during installation when its asking for
Where is your global CSS file?
if you having src directory then make it src/app/globals.css

**Comment by nelsonmandeladev** [comment]
Hi, @usmanashrf the issue was exactly what  you described, I've just followed what you said and now it working
Thanks very much
![image](https://github.com/shadcn/ui/assets/69842489/2ff6ebb0-9d70-487d-847c-4981b057c418)
