### ISSUE TITLE
Potential typo in code of example for Aspect-Ratio component

### ISSUE THREAD

**Issue by USKhokhar** [shadcn/ui#713]
Apparently, the example code of the Aspect-Ratio component under the Usage section has a typo while defining the alt atribute.
 
 The current code is:
 
<img width="268" alt="image" src="https://github.com/shadcn/ui/assets/63156376/f53e1ce6-43bb-4daf-b6dc-0dde888ab44b">

While I think the code should be:

```JSX
<div className="w-[450px]">
  <AspectRatio ratio={16 / 9}>
    <Image
      src="..."
      alt="Image"
      className="rounded-md object-cover"
    />
  </AspectRatio>
</div>
```

**Comment by dan5py** [comment]
A PR for this has already been opened #578
