### ISSUE TITLE
Whenever I  start the server again after installing shadcn it says not found 404 page shown. How do I fix this ? Tell me which files you need to see ?

### ISSUE THREAD

**Issue by faisal975232** [shadcn/ui#716]

**Comment by shadcn** [comment]
Can you send me an example/code I can take a look at?

**Comment by faisal975232** [comment]
ya sure , just give me a minute.

**Comment by faisal975232** [comment]
https://github.com/faisal975232/shadcn-test

here is the code

**Comment by shadcn** [comment]
- You have both `app` and `src/app`. Remove `app`.
- Then update your tsconfig alias: https://github.com/faisal975232/shadcn-test/blob/96c3e2275ad1d854006cb47aa03920223e55a184/tsconfig.json#L19

```diff
- "@/*": ["./*"],
- "@/*": ["./src/*"],
```

**Comment by faisal975232** [comment]
is it because something i did when installing with cli ?

**Comment by faisal975232** [comment]
it Works Thanks . But now I am using your template , it is the best .

**Comment by faisal975232** [comment]
Thanks Shadcn
