### ISSUE TITLE
CLI - Failed to fetch tree from registry - ERR_SOCKET_CONNECTION_TIMEOUT

### ISSUE THREAD

**Issue by MattEagle95** [shadcn/ui#727]
I was following the documentation at https://ui.shadcn.com/docs/installation. After initializing the components.json with `npx shadcn-ui@latest init` I ran `npx shadcn-ui@latest add` and selected all components. It returns the error: **"Failed to fetch tree from registry." - ERR_SOCKET_CONNECTION_TIMEOUT**.

Using the command with a component `npx shadcn-ui@latest add avatar` **does only work for some components**, for others like "avatar", "command", "toggle" I get the same error.

I tried style: default and style: new-york.

Tried commands:
```
npx shadcn-ui@latest add (select all components)
npx shadcn-ui@latest add avatar
npx shadcn-ui@latest add avatar --overwrite
npx shadcn-ui@latest add avatar, ...
```

Error:
```
FetchError: request to https://ui.shadcn.com/registry/styles/new-york/avatar.json failed, reason: Socket connection timeout
    at ClientRequest.<anonymous> (file:///C:/Users/matteagle95/AppData/Local/npm-cache/_npx/125ee17d583c4e03/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:511:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:511:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ERR_SOCKET_CONNECTION_TIMEOUT',
  code: 'ERR_SOCKET_CONNECTION_TIMEOUT',
  erroredSysCall: undefined
}
Failed to fetch tree from registry.
```

OS/Project:
OS: Windows 10
NextJS: 13.4.1

**Comment by dan5py** [comment]
Can you please try with:
```bash
npx shadcn-ui@0.2.2
```

**Comment by MattEagle95** [comment]
Hey, thanks for answering!

Trying with `0.2.2` still returns the same error for me. It's weird, it only occurs for some components. Avatar doesn't work, Button does work.

**Comment by dan5py** [comment]
@MattEagle95 I tried to replicate the issue but without success.  Seems like a problem related to your connection.

**Comment by MattEagle95** [comment]
I tried today, it works now, I'm sorry I'm not sure what the issue was. "Connection Timeout" suggested a client error but since some components worked for me I wanted to try and search for error here :D

Thanks for your help!

**Comment by dan5py** [comment]
No problem. Here to help 😀

**Comment by amirhossein-ix** [comment]
mine still doesn't work, i hope it works when i try tomorrow

**Comment by yqz945** [comment]
I have the same problem. I clean the npx cache but not work.
FetchError: request to https://ui.shadcn.com/registry/index.json failed, reason: connect ETIMEDOUT 76.76.21.98:443
    at ClientRequest.<anonymous> (file:///C:/Users/Lenovo/AppData/Local/npm-cache/_npx/125ee17d583c4e03/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:517:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  erroredSysCall: 'connect'
}
Failed to fetch components from registry.

**Comment by Mecil9** [comment]
as same.how to fix it?

**Comment by Melrain** [comment]
same here, i'm using proxy

**Comment by chaocwu** [comment]
me too. 
![shadcnui](https://github.com/shadcn-ui/ui/assets/143390961/9a34a0a6-7b7b-4eb2-9dc3-836124709659)

**Comment by kangodyan** [comment]
How to solve it? I've been stuck here

**Comment by amirhossein-ix** [comment]
> How to solve it? I've been stuck here

not a fix but the only way i found was to manually install the packages.

**Comment by aliashraficrypto** [comment]
mine still doesn't work

**Comment by DrewIndeed** [comment]
I just tried my VPN (Singapore) and it just worked =)) this is weird as hell. Maybe the connection problem @dan5py said is real?? Idk

**Comment by Aleksandr-Karikov** [comment]
![image](https://github.com/shadcn-ui/ui/assets/80443743/13e480af-de09-4067-849d-3afeef6eb666)
same(

**Comment by rihanna57** [comment]
hi everybody,I also have the same bug, what is your suggestion for solving problem.

**Comment by amirhossein-ix** [comment]
you can either a vpn or change your vpn ( in my case windscribe worked ), or you can just install the packages manually, the instructions are on their documents.

**Comment by Cat-The-Developer** [comment]
I tried 2-3 times and it works on 2nd or 3rd try. I even know how but it works

**Comment by nepimentel** [comment]
npx shadcn-ui init      
FetchError: request to https://ui.shadcn.com/registry/styles/index.json failed, reason: self-signed certificate in certificate chain
    at ClientRequest.<anonymous>
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'SELF_SIGNED_CERT_IN_CHAIN',
  code: 'SELF_SIGNED_CERT_IN_CHAIN',
  erroredSysCall: undefined
}
Failed to fetch styles from registry.

**Comment by MhL5** [comment]
![image](https://github.com/shadcn-ui/ui/assets/135700087/cc13fae8-dfb1-4fee-8b26-da2a542aae0a)

>[!TIP]
> Incorrect System Date and Time can cause TLS handshake failures. 

I had the same issue; after syncing my system time, it works.

**Comment by renzonj** [comment]
Are you by any chance using ESET Antivirus?

https://forum.eset.com/topic/40702-eset-ssl-protection-produces-an-invalid-certificate-chain-for-nodejs-apps/

**Comment by MhL5** [comment]
I don't use any antivirus 
it's weird Sometimes it works, and sometimes it fails🤔

**Comment by kouroshey** [comment]
same here. Sometimes it works, and sometimes it fails

**Comment by wuqianrui** [comment]
> I was following the documentation at https://ui.shadcn.com/docs/installation. After initializing the components.json with `npx shadcn-ui@latest init` I ran `npx shadcn-ui@latest add` and selected all components. It returns the error: **"Failed to fetch tree from registry." - ERR_SOCKET_CONNECTION_TIMEOUT**.
> 
> Using the command with a component `npx shadcn-ui@latest add avatar` **does only work for some components**, for others like "avatar", "command", "toggle" I get the same error.
> 
> I tried style: default and style: new-york.
> 
> Tried commands:
> 
> ```
> npx shadcn-ui@latest add (select all components)
> npx shadcn-ui@latest add avatar
> npx shadcn-ui@latest add avatar --overwrite
> npx shadcn-ui@latest add avatar, ...
> ```
> 
> Error:
> 
> ```
> FetchError: request to https://ui.shadcn.com/registry/styles/new-york/avatar.json failed, reason: Socket connection timeout
>     at ClientRequest.<anonymous> (file:///C:/Users/matteagle95/AppData/Local/npm-cache/_npx/125ee17d583c4e03/node_modules/node-fetch/src/index.js:108:11)
>     at ClientRequest.emit (node:events:511:28)
>     at TLSSocket.socketErrorListener (node:_http_client:495:9)
>     at TLSSocket.emit (node:events:511:28)
>     at emitErrorNT (node:internal/streams/destroy:151:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
>   type: 'system',
>   errno: 'ERR_SOCKET_CONNECTION_TIMEOUT',
>   code: 'ERR_SOCKET_CONNECTION_TIMEOUT',
>   erroredSysCall: undefined
> }
> Failed to fetch tree from registry.
> ```
> 
> OS/Project: OS: Windows 10 NextJS: 13.4.1

我解决了

**Comment by wuqianrui** [comment]
My operating environment is Windows. I used Google to look up the IP address for `https://www.shadcn-vue.com/registry/styles/index.json` and found it to be `104.21.17.226` . and  I edited the hosts file on my Windows computer, adding the line:
```text
104.21.17.226 www.shadcn-vue.com
```
With this addition, the configuration takes effect locally for me; however, some Windows devices might require a restart for the changes in the hosts file to be applied.

Side note: As a Chinese person, dealing with these sorts of network issues can often be quite draining.

**Comment by Shazzad998** [comment]
I had the same issue.
I had to change my region on my windows machine to the correct one according to my location and that solved the error for me.

**Comment by girmafetene** [comment]
Upgrade Node Module

**Comment by RucksollyTech** [comment]
Keep retrying, it will eventually work. I got the same error I waited for a while and tried again and it worked.

**Comment by youwei997** [comment]
> My operating environment is Windows. I used Google to look up the IP address for `https://www.shadcn-vue.com/registry/styles/index.json` and found it to be `104.21.17.226` . and I edited the hosts file on my Windows computer, adding the line:
> 
> ```
> 104.21.17.226 www.shadcn-vue.com
> ```
> 
> With this addition, the configuration takes effect locally for me; however, some Windows devices might require a restart for the changes in the hosts file to be applied.
> 
> Side note: As a Chinese person, dealing with these sorts of network issues can often be quite draining.

Awesome! This UI library is really speechless.

**Comment by Pomelo1213** [comment]
i reboot my terminal, and open proxy ,it fixed!  i do not get the point.

**Comment by swapnil9898** [comment]
![issue](https://github.com/user-attachments/assets/1802476a-9464-450f-8794-99aa0e899e01)

**Comment by swapnil9898** [comment]
How to resolve this

**Comment by swapnil9898** [comment]
The issue was resolved by the system administrator, who granted me full access and added the necessary certificate. After that, the issue was resolved.

**Comment by jcortes0309** [comment]
> How to resolve this

I had the same issue and couldn't figure out what's going on.  I had to install components one by one (or in groups of 2 to 4 components) and that worked for me.  I know this doesn't address the issue, but it's better than being stuck trying to figure out how to fix it.

**Comment by youwei997** [comment]
Friends, I have a not-so-useful but solution to the problem, which is to use docker to start a nodejs development container, and then use vscode to remotely connect to this docker container, where you can use shadcn-ui normally. Don't use local Windows and wsl!

**Comment by Lagyu** [comment]
In the trace, I found something like this:
```
    at async file:///C:/Users/<UserName>/AppData/Local/npm-cache/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:2:4468
```

And I found this statement in the file:
```
await Promise.all(t.map(async o=>await(await Xe(`${ge}/registry/${o}`,{agent:Ze})).json())
```

So, I searched for `Ze` variable (name may vary with library version) in the file, and rewrote like this:
```diff
- Ze=process.env.https_proxy?new qe(process.env.https_proxy):void 0
+ Ze=(await import('https')).Agent({rejectUnauthorized: false})
```

Now I could add the components successfully, with `$Env:NODE_TLS_REJECT_UNAUTHORIZED = "0"` on powershell.
I hope this helps.

**Comment by krixon** [comment]
Similar to @Lagyu, I ran in to this due to my company proxy. Correct fix is of course to install the cert, but I can work around it by setting the env var without any need to edit the source:

```
NODE_TLS_REJECT_UNAUTHORIZED=0 npx shadcn@latest add sidebar
```

This will output some warnings, but it succeeds.
