### ISSUE TITLE
rewrite checkbox with standard html input

### ISSUE THREAD

**Issue by ozzyfromspace** [shadcn/ui#733]
The checkbox is currently based on the radix-ui checkbox primitive, which attempts to simulate a standard input of type "checkbox". The radix-ui implementation is based on an html button and doesn't account for certain important events. Thus, libraries like react-hook-form (rhf) can't work with it easily.

Goal: the shadcn checkbox should support the rhf register function with no hacks/tricks, and render properly even on older browsers. The new checkbox should be clear and straightforward for anyone to understand. Finally, in the spirit of rhf, the checkbox should render outside the react lifecycle.

I propose re-implementing the shadcn/ui checkbox component in a simpler way using a basic html input, so that everything "just works", preferably with no JS.

Shall I submit a PR for this?

**Comment by dan5py** [comment]
Most of the components of this project are built using Radix UI (`checkbox`, `radio`, `select`, etc.). I think that re-implementing just the checkbox wouldn't make much sense and re-creating all the components would comport too much effort and deflect the purpose of this project.
