### ISSUE TITLE
Card    ESLint: 'className' is missing in props validation(react/prop-types)

### ISSUE THREAD

**Issue by shifenhutu** [shadcn/ui#739]
shadcn version: latest

![image](https://github.com/shadcn/ui/assets/104620424/58e64b03-8c8d-4af9-b5af-68433942d6f0)
![image](https://github.com/shadcn/ui/assets/104620424/c835ba96-44b3-4e2e-aee6-4414b6f78fdc)

**Comment by dan5py** [comment]
It's a problem with `eslint-plugin-react` itself, not related to the library.

From `eslint-plugin-react` [docs](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/prop-types.md#as-for-exceptions):

> It would seem that some common properties such as props.children or props.className (and alike) need to be treated as exceptions.

As a workaround you can create a interface type for each component part, like this:

```ts
interface CardProps extends React.HTMLAttributes<HTMLDivElement> {
  className?: string
}

const Card = React.forwardRef<
  HTMLDivElement,
  CardProps
>(({ className, ...props }, ref) => (
```

**Comment by shifenhutu** [comment]
@dan5py  thank you very much
