### ISSUE TITLE
Compile error after running shadcn-ui init command

### ISSUE THREAD

**Issue by chongweiguan** [shadcn/ui#746]
There seems to be an issue with the shadcn-ui init command. 

When creating a new project using `npx create-next-app@latest my-app --typescript --tailwind --eslint`, and then running `npm run dev`. No issues so far, the page displayed is shown below.

<img width="1438" alt="Screenshot 2023-06-28 at 12 06 08 AM" src="https://github.com/shadcn/ui/assets/75872136/faea2a7d-797b-4e7e-870d-fe6cb38885cb">

Next, I ran `npx shadcn-ui@latest init` and chose the default settings, shown below
![Screenshot 2023-06-28 at 12 07 19 AM](https://github.com/shadcn/ui/assets/75872136/e6bd4675-359d-4d90-99fd-ae27d4d4a8eb)

However, after running `npm run dev` again, an error is shown
<img width="1170" alt="Screenshot 2023-06-28 at 12 08 08 AM" src="https://github.com/shadcn/ui/assets/75872136/ba0f1b19-4bd4-46bb-b007-fc8932173d1b">
![Screenshot 2023-06-28 at 12 08 21 AM](https://github.com/shadcn/ui/assets/75872136/6606713f-df49-4b22-ab59-fcf700ca6319)

I really enjoy using shadcn and I hope this can be fixed soon! This seems to be a similar issue faced by #745. Do let me know if you need me to provide other information for you

**Comment by dan5py** [comment]
Are you using the `src` folder?

**Comment by chongweiguan** [comment]
Hi! if you are asking if the src folder is my working directory when running `npm run dev` then yes I am

**Comment by dan5py** [comment]
The you must say it this prompt (`init`):
```diff
- Where is your global CSS file? › app/globals.css
+ Where is your global CSS file? › src/app/globals.css
```

Otherwise a new `app` folder is created, causing the not found error.

**Comment by dan5py** [comment]
If you already have the `components.json` file you can just edit the `tailwind.css` property in it and delete the wrong app folder.

**Comment by chongweiguan** [comment]
Oh ok it is working now! Thank you very much for the help!

**Comment by macgeargear** [comment]
can i see your components.json @chongweiguan

**Comment by chongweiguan** [comment]
@macgeargear 
![Screenshot 2023-06-28 at 12 40 28 AM](https://github.com/shadcn/ui/assets/75872136/00402aca-fdd0-4090-9288-9d33f1ebec17)

**Comment by dan5py** [comment]
@EugenePeter You don't have to delete the original app folder, just the one that the CLI created.

**Comment by dan5py** [comment]
Then you have two edit the path of the css in the `components.json` file:

```diff
- "css": "app/globals.css",
+ "css": "src/app/globals.css",
```

(Assuming that you're using the `src` folder)

**Comment by EugenePeter** [comment]
It's working as expected now .  Cheers @dan5py

**Comment by samadaman** [comment]
Still Not Working...& Showing 404 on browser.

**Comment by schmanat** [comment]
> Still Not Working...& Showing 404 on browser.

After updating the components.json file the error still exists. My solution was that I have to the delete the app/globals.css folder. In my project structure exists the globals.css twice.

```
app/globals.css
src/app/globals.css
```

After deleting the app/globals.css the app works as expected again.

**Comment by russkiih** [comment]
I fixed it by:
1) in layout.tsx make sure:
import "./globals.css"
2)   npm uninstall @shadcn/ui - becuse it gave conflict with  shadcn-ui
3)  npm install
4) npm audit fix --force
5) npx shadcn-ui init 

and it worked
