### ISSUE TITLE
"use client" removed from toaster component in recent update creating problems.

### ISSUE THREAD

**Issue by MATTIRG** [shadcn/ui#749]
I updated my toast and toaster components after one of the recent updates. But when starting my application I got the following error:

```
- error ./node_modules\@radix-ui\react-toast\dist\index.mjs
ReactServerComponentsError:

You're importing a component that needs useEffect. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.

   ,-[C:\Users\mathi\Documents\GitHub\project\node_modules\@radix-ui\react-toast\dist\index.mjs:1:1]
 1 | import $eyrYI$babelruntimehelpersesmextends from "@babel/runtime/helpers/esm/extends";
 2 | import {useState as $eyrYI$useState, useRef as $eyrYI$useRef, createElement as $eyrYI$createElement, useCallback as $eyrYI$useCallback, forwardRef as $eyrYI$forwardRef, useEffect as $eyrYI$useEffect, useMemo as $eyrYI$useMemo, Fragment as $eyrYI$Fragment} from "react";
   : 
  ^^^^^^^^^
 3 | import {createPortal as $eyrYI$createPortal} from "react-dom";
 4 | import {composeEventHandlers as $eyrYI$composeEventHandlers} from "@radix-ui/primitive";
 5 | import {useComposedRefs as $eyrYI$useComposedRefs} from "@radix-ui/react-compose-refs";
   `----

Maybe one of these should be marked as a client entry with "use client":
  ./node_modules\@radix-ui\react-toast\dist\index.mjs
  ./components\ui\toast.tsx
  ./components\ui\toaster.tsx
  ./app\layout.tsx
```

I checked the toaster component and compared it with the version from one of my old github commits. It seems that "use client" was removed from the component. Re-adding this to the toaster component seems to have fixed the issue.

**Comment by MATTIRG** [comment]
Nextjs 13 app directory btw

**Comment by dan5py** [comment]
The `"use client"` directive is still present on the `Toaster` component. Can you share you `components.json` file?

**Comment by MATTIRG** [comment]
Yes, you are correct, I looked through this repo to check, and it seems to still be there, so I don't know if what happened to me was just a one-off bug or something.
Here is my component.json:
```
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": false,
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "styles/globals.css",
    "baseColor": "slate",
    "cssVariables": true
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  }
}
```

**Comment by dan5py** [comment]
You set the React Server Components to `false` when you ran the `init` command.

**Comment by MATTIRG** [comment]
Thank you so much! Is there a way to just re-install every component, or do I just do it manually?

**Comment by MATTIRG** [comment]
Thank you!

**Comment by artafps** [comment]
> You set the React Server Components to `false` when you ran the `init` command. Just change `rsc` to `true` and re-add the component adding the `-o` option.

hello my bro 


my err 
:

Unhandled Runtime Error
Error: useEffect only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/react-client-hook-in-server-component

Call Stack
eval



and


./src/app/page.js
Error: 
  × You're importing a component that needs useEffect. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
  │ Learn more: https://nextjs.org/docs/getting-started/react-essentials
  │ 
  │ 
   ╭─[C:\Users\DATA RAYANEH SHOMAL\Desktop\lcs\lcs-project-algorithm\lcsproject\src\app\page.js:1:1]
 1 │ import {useEffect } from 'react';
   ·         ─────────
 2 │ import Image from "next/image";
 3 │ import { Separator } from "@/components/ui/separator"
 4 │ export default function Home() {
   ╰────
   
   
   and my componnets file : 
   

{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "new-york",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "apps/landing-page/tailwind.config.js",
    "css": "apps/landing-page/styles/global.css",
    "baseColor": "neutral",
    "cssVariables": true
  },
  "aliases": {
    "components": "@od/shadcn-ui/components",
    "utils": "@od/shadcn-ui/lib/utils"
  }
}

**Comment by mathiasrg** [comment]
@artafps 
Have you reinstalled the components, after setting rsc to true?

**Comment by artafps** [comment]
> use Client

My mistake was that I did not use "use Client"
