### ISSUE TITLE
Skeleton Component

### ISSUE THREAD

**Issue by itaim18** [shadcn/ui#758]
any way to change the skeleton's shade?
even tailwind class would help just in order to keep the animation with a different color pallete or to brighten/darken it?

**Comment by dan5py** [comment]
Yes you can style it by changing the `backgroud`. By default it's set to `bg-muted`, you can change the opacity to get the color you want (for example `bg-muted/50`).

**Comment by itaim18** [comment]
You R totally right. the REAL problem was that the `animate-pulse` wasn't imported from the skeleton component. not sure why but I added it when using it

**Comment by dushyantsolanki** [comment]
skeleton animate pulse not working
