### ISSUE TITLE
Request to Add Error State to Input Component

### ISSUE THREAD

**Issue by PACY2** [shadcn/ui#765]
The current input component is impressive, but it seems to lack an error state. I propose adding an error state similar to the following example:

```ts 
<Input placeholder="example@example.com" error={errors.email?.message} />
```

I am interested in contributing to the project and would be happy to implement this feature if it is deemed feasible.

**Comment by dan5py** [comment]
Hi @PACY2, I think that the `Input` component should be as close as possible to the native `<input>`.

Would the error state be used just for styling purposes, or do you have something else in mind?

**Comment by PACY2** [comment]
Hi @dan5py 

I've been thinking about simplifying the idea of handling input errors. Instead of creating a separate component to render the error, we can add it to the default component. This way, the input component would look like this:
```ts
import * as React from "react";

import { cn } from "@/lib/utils";

export interface InputProps
  extends React.InputHTMLAttributes<HTMLInputElement> {
  error?: string;
}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, type, error, ...props }, ref) => {
    return (
      <div className="flex flex-col gap-1" >
        <input
          type={type}
          className={cn(
            "flex h-9 w-full rounded-md border border-input bg-background px-3 py-1 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50",
            className
          )}
          ref={ref}
          {...props}
        />
        {
          error && (
            <p className="text-red-700 text-sm" >
              {error}
            </p>
          )
        }
      </div>
    );
  }
);
Input.displayName = "Input";

export { Input };
```

This simple modification can enhance the likability of the input.

**Comment by dan5py** [comment]
I'm not really into this idea. I'd like to hear the opinion of someone else.

**Comment by steveg152** [comment]
From a usage perspective, I think it's better to keep the input as close to the primitive as possible. This seems to be the pattern with the `<label>` component as well. The real strength of this library is the fact that you own this code, so after you add the component you can add this functionality yourself.

Errors can be very unique based on  the application. In my experience it's better to let the user create their own custom error state.

Every design team I have worked with has wanted different error styling.

**Comment by devandholmes** [comment]
For those who come across this as I have. Here is an elegant soluion

`import * as React from "react"

import { cn } from "@/lib/utils"

export interface InputProps
  extends React.InputHTMLAttributes<HTMLInputElement> {
  error?: string; // Add error property
}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, type, error, ...props }, ref) => { // Destructure error
    return (
      <div>
        <input
          type={type}
          className={cn(
            "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50",
            error && "border-red-500", // Add error border color
            className
          )}
          ref={ref}
          {...props}
        />
        {error && <p className="mt-1 text-sm text-red-500">{error}</p>} {/* Conditionally render error message */}
      </div>
    )
  }
)
Input.displayName = "Input"

export { Input }`

![image](https://github.com/user-attachments/assets/405020e7-7291-4e1e-8e9f-8b2d5352fd8d)
