### ISSUE TITLE
Textarea + Form not throwing validation errors

### ISSUE THREAD

**Issue by zeevo** [shadcn/ui#766]
Hello

I think the example on the [docs](https://ui.shadcn.com/docs/components/textarea) does not work as intended.

I would expect it to show an error when the typing a value that breaches the zod schema but it does not.

[Recreation sandbox here](https://codesandbox.io/p/github/zeevo/shadcn-textarea/main) 

Thanks for the all the great components

**Comment by dan5py** [comment]
Hi @zeevo, by default the `useForm` hook by react-hook-form has the `mode` set to `onSubmit`, this mean that the validation is applied only when the form is submitted. You can change it to `onChange` to get the behaviour you're expecting.

```tsx
const form = useForm<z.infer<typeof FormSchema>>({
    resolver: zodResolver(FormSchema),
    mode: `onChange`
  })
```


For further information check the [react-hook-form docs](https://www.react-hook-form.com/api/useform/#mode)

**Comment by zeevo** [comment]
Thanks for the tip @dan5py !
