### ISSUE TITLE
Remove the outline in input

### ISSUE THREAD

**Issue by Ghoral** [shadcn/ui#769]
Hi,
How can I remove the outline in input when focused? 

<img width="809" alt="Screenshot 2023-06-29 at 18 59 46" src="https://github.com/shadcn/ui/assets/49188349/2a146e19-729e-460b-a39a-af9c99024f24">

Thank you.

**Comment by dan5py** [comment]
Hi @Ghoral, you can add this classname to the `<Input>` component: `focus-visible:ring-0`. This will disable the focus ring just for a single instance.

If you want to remove it from all `Input` you can remove all the classnames that start with `focus-visible:` in the `input.tsx` file.

**Comment by Ghoral** [comment]
Thank you for quick response.

**Comment by 8blvck** [comment]
`focus-visible:ring-transparent` works better for me.

**Comment by lisaspotty** [comment]
> `focus-visible:ring-transparent` works better for me.

same solution as u 🍭

**Comment by MimmyJau** [comment]
Neither `focus-visible:ring-0 ` nor `focus-visible:ring-transparent` seem to be working for me. Anyone else?

**Comment by reinaldo-vombo** [comment]
`<Input type="email" className="bg-transparent border-0 border-b-2 border-gray-500 px-6 py-8 focus-visible:ring-offset-0 focus-visible:ring-0" placeholder="Email" />` do this

**Comment by abhishek61067** [comment]
You can remove the classname: focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 from input component provided by the shadn in components/ui/input.jsx.

**Comment by Jervx** [comment]
this works for me

```focus-visible:ring-0 focus-visible:ring-transparent focus-visible:ring-offset-0```

**Comment by tonyljx** [comment]
> focus-visible:ring-0 focus-visible:ring-transparent focus-visible:ring-offset-0

thank you ! it works!!!!!!

**Comment by Garvit1809** [comment]
how do we do this in select component. Tried many things but none is working ;(

**Comment by pedrogrigorio** [comment]
> how do we do this in select component. Tried many things but none is working ;(

Just use "focus:" instead of "focus-visible",  like this:

`<Select>
      <SelectTrigger className="w-[180px] focus:ring-offset-0 focus:ring-0">
        <SelectValue placeholder="Select a fruit" />
      </SelectTrigger>
      <SelectContent>
        <SelectGroup>
          <SelectLabel>Fruits</SelectLabel>
          <SelectItem value="apple">Apple</SelectItem>
          <SelectItem value="banana">Banana</SelectItem>
          <SelectItem value="blueberry">Blueberry</SelectItem>
          <SelectItem value="grapes">Grapes</SelectItem>
          <SelectItem value="pineapple">Pineapple</SelectItem>
        </SelectGroup>
      </SelectContent>
    </Select>`
    
    You can also verify what properties your component uses opening the file that shadcnui creates (like select.tsx).

**Comment by ParshvLimbad** [comment]
focus-visible:ring-[none] worked for me

**Comment by vekaev** [comment]
tabindex=-1

**Comment by sivakumar5335** [comment]
i want the bottom outline and placeholder to be colored

**Comment by ParshvLimbad** [comment]
@sivakumar5335 You can always refer to the documentation

https://v1.tailwindcss.com/docs/placeholder-color

https://tailwindcss.com/docs/outline-style

**Comment by radekm2000** [comment]
nothing above worked for me so i found a different solution on stackoverflow and it worked focus-visible:ring-0 focus-visible:ring-offset-0

**Comment by daniel-bogale** [comment]
```
<div
                            className={"flex h-10 items-center rounded-md border border-input bg-white pl-3 text-sm ring-offset-background focus-within:ring-1 focus-within:ring-ring focus-within:ring-offset-2"}
                        >
                            <SearchIcon className="mr-2 w-4 h-4" />
                            <Input
                                className="w-full p-2 placeholder:text-muted-foreground focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50 focus-visible:ring-transparent border-l-0 rounded-none rounded-r-lg"
                            />
                        </div>
```

![Uploading Screenshot (1).png…]()

**Comment by ParshvLimbad** [comment]
@radekm2000 yeah i used focus-visible:ring-[none]

**Comment by HT-35** [comment]
i try it and i successful
` focus-visible:ring-0`

**Comment by adeyemialameen04** [comment]
IS THERE A WAY TO REMOVE IT IN ALL COMPONENTS?

**Comment by radekm2000** [comment]
@adeyemialameen04  just overwrite the component's prop

**Comment by daveycodez** [comment]
How come this isn't the default like it is in the shadcn documentation examples? I'm very confused. Shouldn't installing shadcn/ui be identical to what their documentation shows?

**Comment by alexwohlbruck** [comment]
Would it be difficult to implement a universal configuration for this behavior? The focus ring is nice for accessibility, but imo it's too large and obvious. It would look nice with a smaller, toned down and animated focus ring. Applying these changes to all inputs is a bit of a pain.

**Comment by adeyemialameen04** [comment]
> Would it be difficult to implement a universal configuration for this behavior? The focus ring is nice for accessibility, but imo it's too large and obvious. It would look nice with a smaller, toned down and animated focus ring. Applying these changes to all inputs is a bit of a pain.

real

**Comment by cwingho** [comment]
> `focus-visible:ring-transparent` works better for me.

thx for saving my time!!!!!!!!!!!!!!!!

**Comment by javicrg** [comment]
nothing from the above worked for me, this was my solution using the UI's ring variable as it seemed a browser issue.

Just add: `focus:border-ring`

**Comment by nisharga** [comment]
```border-none focus-visible:ring-offset-0 focus-visible:ring-0```

worked for me

**Comment by Tajmirul** [comment]
@dan5py Is it good practice to edit a shadcn component? Someone might accidentally regenerate the component, and all the updates would be lost.

**Comment by GarfieldFluffJr** [comment]
For me, `focus-visible:ring-0` and `focus-within:ring-0` on the parent element didn't work, along with any other solutions posted. I just searched "ring" and inside `input-group.tsx` you can comment out all the code under "Focus state" which are defined like:
```"has-[[data-slot=input-group-control]:focus-visible]:border-ring has-[[data-slot=input-group-control]:focus-visible]:ring-ring/50 has-[[data-slot=input-group-control]:focus-visible]:ring-[3px]",```
which are likely overriding your styling and won't let you remove the focused ring directly in the element

**Comment by aanish27** [comment]
has-[[data-slot=input-group-control]:focus-visible]:ring-0
    has-[[data-slot=input-group-control]:focus-visible]:ring-transparent
    has-[[data-slot=input-group-control]:focus-visible]:border-transparent
