### ISSUE TITLE
BUG: Overlay is not shown in Sheet component if I set modal={false}

### ISSUE THREAD

**Issue by ensidialabs** [shadcn/ui#787]
When I put in Sheet.Root - modal={false}, the overlay does not appear.

**Comment by dan5py** [comment]
Hi @ensidialabs, this is not a bug. The `Sheet` component is based of the RadixUI dialog, and when modal it's set to `false` the Overlay doesn't appear by default, which makes sense since anything under the overlay shouldn't be used.

**Comment by desiprisg** [comment]
You can use a separate `<Sheet />` with just an overlay to achieve this:

```
<Sheet>
  <SheetOverlay />
</Sheet>
<Sheet modal={false}>
  ...
</Sheet>
```

Just make sure you use both as controlled with the same state.
