### ISSUE TITLE
typescript module not found error while running "npx shadcn-ui@latest init"

### ISSUE THREAD

**Issue by bloodgroup-cplusplus** [shadcn/ui#793]
while initializing shadcn-ui using the command "npx shadcn-ui@latest init" in nextjs using typescript an error is generated 
which says 
cons err= new Error(message);
Error: cannot find module '@ts-morph/common'

Installed ts-morph using yarn ("yarn global add ts-morph)  but the error still persists

**Comment by guotie** [comment]
same problem

**Comment by elite16op** [comment]
@guotie  @bloodgroup-cplusplus 
I just tried it and there is no such error getting introduced. I hope you did the setup carefully from the docs

**Comment by guotie** [comment]
my env:

```
node -v
v19.1.0

Mac os 13.4.1
```

**Comment by guotie** [comment]
use pnmp is ok

**Comment by bloodgroup-cplusplus** [comment]
Was following a yt video earlier , tried with the docs open side by side (as @guotie  mentioned) now it works ... maybe some version difference in the tools on my machine to the one used in the yt video ... anyways it works now. thanks  @elite16op  and @guotie

**Comment by JCalmCrasher** [comment]
For some reasons `npx` didn't work for. me, had to use `pnpm dlx`

**Comment by Dinal-Jayathilake** [comment]
I had the same problem too. However, this seems to only happen when you don't specify the version and just use "npx shadcn-ui@latest init". I tried "npx shadcn-ui@0.3.0 init" instead and this works. Not sure as to why though.

P.S. - 0.3.0 is the latest version as of writing this.

**Comment by Hopejrajoku** [comment]
If you face this problem, Instead of  '' npx shadcn-ui@latest init '' , do npx shadcn-ui@0.8.0 init make sure to add the latest version  manually, v0.8.0 happens to be the latest at the time of this comment.
