### ISSUE TITLE
TypeError: Cannot destructure property 'getFieldState' of '(0 , react_hook_form__WEBPACK_IMPORTED_MODULE_4__.useFormContext)(...)' as it is null.

### ISSUE THREAD

**Issue by Dank-del** [shadcn/ui#800]
![image](https://github.com/shadcn/ui/assets/63096193/e0b82c82-c03b-44c2-ad01-484c319a8600)

# My `package.json`
```json 
{
  "name": "next-template",
  "version": "0.0.2",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "lint:fix": "next lint --fix",
    "preview": "next build && next start",
    "typecheck": "tsc --noEmit",
    "format:write": "prettier --write \"**/*.{ts,tsx,mdx}\" --cache",
    "format:check": "prettier --check \"**/*.{ts,tsx,mdx}\" --cache"
  },
  "dependencies": {
    "@auth/prisma-adapter": "^1.0.0",
    "@hookform/resolvers": "^3.1.1",
    "@prisma/client": "^4.16.1",
    "@radix-ui/react-alert-dialog": "^1.0.4",
    "@radix-ui/react-avatar": "^1.0.3",
    "@radix-ui/react-dropdown-menu": "^2.0.5",
    "@radix-ui/react-label": "^2.0.2",
    "@radix-ui/react-slot": "^1.0.2",
    "autoresponsive-react": "^1.2.3",
    "class-variance-authority": "^0.4.0",
    "clsx": "^1.2.1",
    "lucide-react": "0.105.0-alpha.4",
    "next": "^13.4.4",
    "next-auth": "0.0.0-pr.6777.c5550344",
    "next-themes": "^0.2.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.45.1",
    "sharp": "^0.31.3",
    "tailwind-merge": "^1.12.0",
    "tailwindcss-animate": "^1.0.5",
    "zod": "^3.21.4"
  },
  "devDependencies": {
    "@ianvs/prettier-plugin-sort-imports": "^3.7.2",
    "@types/node": "^17.0.45",
    "@types/react": "^18.2.7",
    "@types/react-dom": "^18.2.4",
    "@typescript-eslint/parser": "^5.59.7",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.41.0",
    "eslint-config-next": "13.0.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-tailwindcss": "^3.12.0",
    "postcss": "^8.4.24",
    "prettier": "^2.8.8",
    "prisma": "^4.16.1",
    "tailwindcss": "^3.3.2",
    "typescript": "^4.9.5"
  }
}
```

**Comment by Dank-del** [comment]
nevermind, fixed it with [this](https://react-hook-form.com/docs/formprovider)

**Comment by evanlong0926** [comment]
I had that problem too. How exactly do you fix it?

**Comment by Dank-del** [comment]
> I had that problem too. How exactly do you fix it?

Wrapping it with `<Form></Form>`

**Comment by evanlong0926** [comment]
It's taken care of. Thank you~

**Comment by manuganji** [comment]
My mistake was that my editor auto imported `Form` component from `react-hook-form` when it should have been imported from `@/components/ui/form`. Hope this helps somebody.

**Comment by adarshaacharya** [comment]
@manuganji I'm sure you've used `shadcn/ui` the imports got conflicted for me as well :D

**Comment by MusabDev** [comment]
> My mistake was that my editor auto imported `Form` component from `react-hook-form` when it should have been imported from `@/components/ui/form`. Hope this helps somebody.

Same thing happened here :)

**Comment by ApurvaBr11** [comment]
check whether from where have u imported the <Form></Form>
if from react-hook-form , there u go that's the issue .. instead  , import it from @/components/ui/form (shadcn one)

**Comment by gilgonzalez** [comment]
> My mistake was that my editor auto imported `Form` component from `react-hook-form` when it should have been imported from `@/components/ui/form`. Hope this helps somebody.

Had the exactly same mistake, thank you very much!

**Comment by swarajbachu** [comment]
> My mistake was that my editor auto imported `Form` component from `react-hook-form` when it should have been imported from `@/components/ui/form`. Hope this helps somebody.

daamn, you got it right dude

**Comment by Leiloukou** [comment]
Thank you. I had the exact same thing!

Just change

```typescript
import {
    FormField,
    FormItem,
    FormLabel,
    FormControl,
    FormDescription,
    FormMessage,
} from "@/components/ui/form";
import { Form, useForm } from "react-hook-form";
```

To

```typescript
import {
    Form,
    FormField,
    FormItem,
    FormLabel,
    FormControl,
    FormDescription,
    FormMessage,
} from "@/components/ui/form";
import { useForm } from "react-hook-form";
```

**Comment by TA9IO** [comment]
happend to me my auto import imported `Form `form `"react-router-dom"`
![image](https://github.com/shadcn-ui/ui/assets/93702837/151a123c-ed14-4b83-97f4-751d05080312)
just  make sure `Form `is imported from `"@/components/ui/form"`
![image](https://github.com/shadcn-ui/ui/assets/93702837/3e0bbb1b-e257-45c4-a1a6-2c0ed653687d)

**Comment by mruus** [comment]
> happend to me my auto import imported `Form `form `"react-router-dom"` ![image](https://user-images.githubusercontent.com/93702837/284587437-151a123c-ed14-4b83-97f4-751d05080312.png) just make sure `Form `is imported from `"@/components/ui/form"` ![image](https://user-images.githubusercontent.com/93702837/284587805-3e0bbb1b-e257-45c4-a1a6-2c0ed653687d.png)

You saved the day, Thanks Buddy

**Comment by ramanand-rv** [comment]
> My mistake was that my editor auto imported `Form` component from `react-hook-form` when it should have been imported from `@/components/ui/form`. Hope this helps somebody.

Thanks bro, my editor ditched me the same way...

**Comment by nandramihnea** [comment]
> My mistake was that my editor auto imported `Form` component from `react-hook-form` when it should have been imported from `@/components/ui/form`. Hope this helps somebody.

you're the real MVP!

**Comment by WemersonD3V** [comment]
thanks everyone.

**Comment by anthonyg56** [comment]
> My mistake was that my editor auto imported `Form` component from `react-hook-form` when it should have been imported from `@/components/ui/form`. Hope this helps somebody.

Worked like a charm!

**Comment by FindMalek** [comment]
> My mistake was that my editor auto imported `Form` component from `react-hook-form` when it should have been imported from `@/components/ui/form`. Hope this helps somebody.

Same thing here! 
(It's from prettier auto imports)

**Comment by sumcodez** [comment]
> > My mistake was that my editor auto imported `Form` component from `react-hook-form` when it should have been imported from `@/components/ui/form`. Hope this helps somebody.
> 
> Same thing happened here :)

Thanks brother

**Comment by fagbenjaenoch** [comment]
> My mistake was that my editor auto imported `Form` component from `react-hook-form` when it should have been imported from `@/components/ui/form`. Hope this helps somebody.

Yeah it did 👌

**Comment by Khaleeq01** [comment]
Cannot destructure property 'selectedItems' of '(0 , _components_Hooks_useRestaurant_js__WEBPACK_IMPORTED_MODULE_3__.default)(...)' as it is undefined.
// App.js

import style from "./App.module.css";
import { Form } from "react-bootstrap";
import NavBar from "./components/Navbar/Navbar";
import CardItem from "./components/RestaurantCard/Card";
import useRestaurantContext from "./components/Hooks/useRestaurant.js";

function App() {


	const { selectedItems, setSelectedItems, setLocation, setRating } =
		useRestaurantContext();

	const options = [
		{ value: "North Indian", label: "North Indian" },
		{ value: "South Indian", label: "South Indian" },
		{ value: "Chinese", label: "Chinese" },
		{ value: "Desserts", label: "Desserts" },
		{ value: "Italian", label: "Italian" },
		{ value: "Oriental", label: "Oriental" },
		{ value: "Pastas", label: "Pastas" },
		{ value: "Pizzas", label: "Pizzas" },
		{ value: "Japanese", label: "Japanese" },
		{ value: "Sushi", label: "Sushi" },
		{ value: "Barbecue", label: "Barbecue" },
		{ value: "Steak", label: "Steak" },
		{ value: "Seafood", label: "Seafood" },
	];

	const handleCheckboxChange = (value) => {

		if (selectedItems.includes(value)) {

			setSelectedItems(selectedItems.filter((item) => item !== value));
		} else {

			setSelectedItems([...selectedItems, value]);
		}

		console.log("elements", selectedItems);
	};

	return (
		<div className="App">
			<NavBar />
			<div>
				<div className={style.headers}>
					<div className={style.locationContainer}>
						<Form.Select
							aria-label="Location"
							onChange={(e) => {
								setLocation(e.target.value);
							}}
						>
							<option hidden>Select Location</option>
							<option value="Hyderabad">Hyderabad</option>
							<option value="Banglore">Banglore</option>
							<option value="Mumbai">Mumbai</option>
							<option value="Delhi">Delhi</option>
							<option value="Pune">Pune</option>
							<option value="Chennai">Chennai</option>
						</Form.Select>
					</div>
					<div className={style.cuisinesContainer}>
						<Form>
							<Form.Label>Select Cuisines:</Form.Label>
							{options.map((option) => (
								<Form.Check
									key={option.value}
									type="checkbox"
									id={option.value}
									label={option.label}
									checked={selectedItems?.includes(option.value)}
									onChange={() => handleCheckboxChange(option.value)}
								/>
							))}
						</Form>
					</div>
					<div className={style.ratingContainer}>
						<Form.Select
							aria-label="Default select example"
							onChange={(e) => {
								setRating(e.target.value);
							}}
						>
							<option hidden>Select Rating</option>
							<option value="3">3 above</option>
							<option value="4">4 above</option>
						</Form.Select>
					</div>
				</div>
			</div>
			<div className={style.restaurants}>
				<h3>Restaurants</h3>
				<CardItem />
			</div>
		</div>
	);
}

export default App;
this is my app.js file code someone help me

**Comment by maik-emanoel** [comment]
> Cannot destructure property 'selectedItems' of '(0 , _components_Hooks_useRestaurant_js__WEBPACK_IMPORTED_MODULE_3__.default)(...)' as it is undefined. // App.js
> 
> import style from "./App.module.css"; import { Form } from "react-bootstrap"; import NavBar from "./components/Navbar/Navbar"; import CardItem from "./components/RestaurantCard/Card"; import useRestaurantContext from "./components/Hooks/useRestaurant.js";
> 
> function App() {
> 
> ```
> const { selectedItems, setSelectedItems, setLocation, setRating } =
> 	useRestaurantContext();
> 
> const options = [
> 	{ value: "North Indian", label: "North Indian" },
> 	{ value: "South Indian", label: "South Indian" },
> 	{ value: "Chinese", label: "Chinese" },
> 	{ value: "Desserts", label: "Desserts" },
> 	{ value: "Italian", label: "Italian" },
> 	{ value: "Oriental", label: "Oriental" },
> 	{ value: "Pastas", label: "Pastas" },
> 	{ value: "Pizzas", label: "Pizzas" },
> 	{ value: "Japanese", label: "Japanese" },
> 	{ value: "Sushi", label: "Sushi" },
> 	{ value: "Barbecue", label: "Barbecue" },
> 	{ value: "Steak", label: "Steak" },
> 	{ value: "Seafood", label: "Seafood" },
> ];
> 
> const handleCheckboxChange = (value) => {
> 
> 	if (selectedItems.includes(value)) {
> 
> 		setSelectedItems(selectedItems.filter((item) => item !== value));
> 	} else {
> 
> 		setSelectedItems([...selectedItems, value]);
> 	}
> 
> 	console.log("elements", selectedItems);
> };
> 
> return (
> 	<div className="App">
> 		<NavBar />
> 		<div>
> 			<div className={style.headers}>
> 				<div className={style.locationContainer}>
> 					<Form.Select
> 						aria-label="Location"
> 						onChange={(e) => {
> 							setLocation(e.target.value);
> 						}}
> 					>
> 						<option hidden>Select Location</option>
> 						<option value="Hyderabad">Hyderabad</option>
> 						<option value="Banglore">Banglore</option>
> 						<option value="Mumbai">Mumbai</option>
> 						<option value="Delhi">Delhi</option>
> 						<option value="Pune">Pune</option>
> 						<option value="Chennai">Chennai</option>
> 					</Form.Select>
> 				</div>
> 				<div className={style.cuisinesContainer}>
> 					<Form>
> 						<Form.Label>Select Cuisines:</Form.Label>
> 						{options.map((option) => (
> 							<Form.Check
> 								key={option.value}
> 								type="checkbox"
> 								id={option.value}
> 								label={option.label}
> 								checked={selectedItems?.includes(option.value)}
> 								onChange={() => handleCheckboxChange(option.value)}
> 							/>
> 						))}
> 					</Form>
> 				</div>
> 				<div className={style.ratingContainer}>
> 					<Form.Select
> 						aria-label="Default select example"
> 						onChange={(e) => {
> 							setRating(e.target.value);
> 						}}
> 					>
> 						<option hidden>Select Rating</option>
> 						<option value="3">3 above</option>
> 						<option value="4">4 above</option>
> 					</Form.Select>
> 				</div>
> 			</div>
> 		</div>
> 		<div className={style.restaurants}>
> 			<h3>Restaurants</h3>
> 			<CardItem />
> 		</div>
> 	</div>
> );
> ```
> 
> }
> 
> export default App; this is my app.js file code someone help me

Are you using shadcn? If yes, you should import the Form component from `@/components/ui/form`

**Comment by Khaleeq01** [comment]
> > Cannot destructure property 'selectedItems' of '(0 , _components_Hooks_useRestaurant_js__WEBPACK_IMPORTED_MODULE_3__.default)(...)' as it is undefined. // App.js
> > import style from "./App.module.css"; import { Form } from "react-bootstrap"; import NavBar from "./components/Navbar/Navbar"; import CardItem from "./components/RestaurantCard/Card"; import useRestaurantContext from "./components/Hooks/useRestaurant.js";
> > function App() {
> > ```
> > const { selectedItems, setSelectedItems, setLocation, setRating } =
> > 	useRestaurantContext();
> > 
> > const options = [
> > 	{ value: "North Indian", label: "North Indian" },
> > 	{ value: "South Indian", label: "South Indian" },
> > 	{ value: "Chinese", label: "Chinese" },
> > 	{ value: "Desserts", label: "Desserts" },
> > 	{ value: "Italian", label: "Italian" },
> > 	{ value: "Oriental", label: "Oriental" },
> > 	{ value: "Pastas", label: "Pastas" },
> > 	{ value: "Pizzas", label: "Pizzas" },
> > 	{ value: "Japanese", label: "Japanese" },
> > 	{ value: "Sushi", label: "Sushi" },
> > 	{ value: "Barbecue", label: "Barbecue" },
> > 	{ value: "Steak", label: "Steak" },
> > 	{ value: "Seafood", label: "Seafood" },
> > ];
> > 
> > const handleCheckboxChange = (value) => {
> > 
> > 	if (selectedItems.includes(value)) {
> > 
> > 		setSelectedItems(selectedItems.filter((item) => item !== value));
> > 	} else {
> > 
> > 		setSelectedItems([...selectedItems, value]);
> > 	}
> > 
> > 	console.log("elements", selectedItems);
> > };
> > 
> > return (
> > 	<div className="App">
> > 		<NavBar />
> > 		<div>
> > 			<div className={style.headers}>
> > 				<div className={style.locationContainer}>
> > 					<Form.Select
> > 						aria-label="Location"
> > 						onChange={(e) => {
> > 							setLocation(e.target.value);
> > 						}}
> > 					>
> > 						<option hidden>Select Location</option>
> > 						<option value="Hyderabad">Hyderabad</option>
> > 						<option value="Banglore">Banglore</option>
> > 						<option value="Mumbai">Mumbai</option>
> > 						<option value="Delhi">Delhi</option>
> > 						<option value="Pune">Pune</option>
> > 						<option value="Chennai">Chennai</option>
> > 					</Form.Select>
> > 				</div>
> > 				<div className={style.cuisinesContainer}>
> > 					<Form>
> > 						<Form.Label>Select Cuisines:</Form.Label>
> > 						{options.map((option) => (
> > 							<Form.Check
> > 								key={option.value}
> > 								type="checkbox"
> > 								id={option.value}
> > 								label={option.label}
> > 								checked={selectedItems?.includes(option.value)}
> > 								onChange={() => handleCheckboxChange(option.value)}
> > 							/>
> > 						))}
> > 					</Form>
> > 				</div>
> > 				<div className={style.ratingContainer}>
> > 					<Form.Select
> > 						aria-label="Default select example"
> > 						onChange={(e) => {
> > 							setRating(e.target.value);
> > 						}}
> > 					>
> > 						<option hidden>Select Rating</option>
> > 						<option value="3">3 above</option>
> > 						<option value="4">4 above</option>
> > 					</Form.Select>
> > 				</div>
> > 			</div>
> > 		</div>
> > 		<div className={style.restaurants}>
> > 			<h3>Restaurants</h3>
> > 			<CardItem />
> > 		</div>
> > 	</div>
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > export default App; this is my app.js file code someone help me
> 
> Are you using shadcn? If yes, you should import the Form component from `@/components/ui/form`

No i am not using shadcn

**Comment by mukultrustworthy** [comment]
getting the same error, even after importing it from shadcn/ui Form.

![Screenshot 2024-05-24 at 9 20 07 AM](https://github.com/shadcn-ui/ui/assets/166636785/a7047afd-907d-4367-915e-60b0c64bf184)

![Screenshot 2024-05-24 at 9 20 42 AM](https://github.com/shadcn-ui/ui/assets/166636785/288b449c-ba16-4011-956f-cb7f24e246e0)

**Comment by FernandoGmz2001** [comment]
> My mistake was that my editor auto imported `Form` component from `react-hook-form` when it should have been imported from `@/components/ui/form`. Hope this helps somebody.

It happened to me too!

**Comment by qm-h** [comment]
> My mistake was that my editor auto imported `Form` component from `react-hook-form` when it should have been imported from `@/components/ui/form`. Hope this helps somebody.

Woaw Thank you bro 🤣

**Comment by rendi12345678** [comment]
> My mistake was that my editor auto imported `Form` component from `react-hook-form` when it should have been imported from `@/components/ui/form`. Hope this helps somebody.

lol

**Comment by arifshariati** [comment]
reasonable suggestions however, just to keep in mind, if using shadcn form component then your component must be wrapped with `<Form {...form}>` where form comes from `const form = useForm({
    resolver: zodResolver(schema),
    defaultValues: config.defaultValues,
  });
`

**Comment by volfadar** [comment]
> My mistake was that my editor auto imported `Form` component from `react-hook-form` when it should have been imported from `@/components/ui/form`. Hope this helps somebody.

Hahaha, I can’t stop laughing at myself!

**Comment by zJUNAIDz** [comment]
> > I had that problem too. How exactly do you fix it?
> 
> Wrapping it with `<Form></Form>` Reference: [My Project](https://github.com/Dank-del/idea-hub/blob/ef125eb454a3e4b742e0beeb20ff39a76f8781ec/components/create-idea-modal.tsx#L58)

```<Form></Form>``` no logner works. Use  ```<FormProvider></FormProvider>``` now

**Comment by arifshariati** [comment]
> > > I had that problem too. How exactly do you fix it?
> > 
> > 
> > Wrapping it with `<Form></Form>` Reference: [My Project](https://github.com/Dank-del/idea-hub/blob/ef125eb454a3e4b742e0beeb20ff39a76f8781ec/components/create-idea-modal.tsx#L58)
> 
> `<Form></Form>` no logner works. Use `<FormProvider></FormProvider>` now

Double check if you are passing params `{...form}`

**Comment by thinhbg2812-2** [comment]
Use <FormProvider> instead of <Form>  at 2024 work for me

**Comment by maggiflux** [comment]
> My mistake was that my editor auto imported `Form` component from `react-hook-form` when it should have been imported from `@/components/ui/form`. Hope this helps somebody.

It helped me. Than you <3

**Comment by utkbkts** [comment]
This problem is caused by importing the form in react-hook-form. You need to import the form from ui/form.

import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "../ui/form"; = true

import { useForm,Form } from "react-hook-form"; = false

**Comment by AyushBadola22** [comment]
> My mistake was that my editor auto imported `Form` component from `react-hook-form` when it should have been imported from `@/components/ui/form`. Hope this helps somebody.

same thing happened here, thanks for the help

**Comment by arcpac** [comment]
make sure you have this imports

import { Form } from "@/components/ui/form";
import { useForm } from "react-hook-form";
