### ISSUE TITLE
Custom color with opacity modifiers doesn't appear to work

### ISSUE THREAD

**Issue by carcer** [shadcn/ui#805]
Currently, there are two requirements that need to be addressed:

1. **Adding custom color**: We need to add a custom color. The modifications have already been made in the CSS code as follows:

global.css

```css
/* Added */
--success: 164, 95%, 43%;
--success-foreground: 164, 95%, 23%;
```

tailwind.config.js

```ts
success: "hsl(var(--success))",
"success-foreground": "hsl(var(--success-foreground))",
```

2. **Creating a button variant using the new custom color**: We need to create a button variant that utilizes the new custom color defined above. The code snippet for the button variant is as follows:

button.tsx

```ts
success: "bg-success text-success-foreground hover:bg-success/90",
```

However, we have encountered an issue where the Tailwind CSS opacity modifier does not seem to work for both the new custom color and the modified color.

**Expected Behavior:**

- The custom color with opacity modifier should be applied correctly in the CSS code.
- The button variant utilizing the new custom color should display the expected background color, text color, and hover effect.
- The Tailwind CSS opacity modifier should work as expected for both the new custom color and the modified color.

**Steps to Reproduce:**

1. Apply the provided CSS code modifications to add the custom color .
2. Implement the button variant code using the new custom color.
3. Apply Tailwind CSS opacity modifiers to the new custom color.

**Additional Information:**

- This issue prevents us from properly implementing the desired custom color and opacity modifiers in our application's UI.
- Any insights or suggestions regarding a workaround, alternative approaches to achieve the desired functionality would be greatly appreciated.

**Environment:**

- Framework/Libraries: Tailwind CSS, NextJs
- Tailwind Version: 3.3.2
- NextJs Version: 13.4.7
- Browser: Firefox
- Operating System: Manjaro Linux 5.15.114-2-MANJARO

**Example Repository:**

An example repository demonstrating the issue can be found at: [https://github.com/carcer/psychic-adventure](https://github.com/carcer/psychic-adventure)

**Comment by dan5py** [comment]
Hi @carcer, in order to use the opacity modifier, you need to define new colors like this in your `tailwind.config.js`:
```diff
- success: "hsl(var(--success))"
+ success: "hsl(var(--success) / <alpha-value> )"
```

I suggest you to use the new hsl format in your css file:
```diff
- --success: 164, 95%, 43%;
+ --success: 164 95% 43%;
```

Making these changes should do the work. Let me know.

**Comment by carcer** [comment]
@dan5py Great, appears to have been mostly a PEBKAC issue!  Everything works as expected, thanks you every much for your time!

**Comment by nextglabs** [comment]
The `<alpha-value>` isn't required in the `tailwind.config.ts` file. What's causing the problem is the use of commas between the HSL values.
```diff
/* global.css */
- --success: 164, 95%, 43%;
+ --success: 164 95% 43%;
- --success-foreground: 164, 95%, 23%;
+ --success-foreground: 164 95% 23%;
```

**Comment by YogiDhingani27** [comment]
@nextglabs 
How can i use custom color with opacity for hex color codes?

**Comment by dan5py** [comment]
[This SO question](https://stackoverflow.com/questions/74521806/how-to-add-custom-opacity-values-to-colors-in-tailwind-css-themes) is about the use of rgb values, not sure if you can do it with hex too.

**Comment by nextglabs** [comment]
> @nextglabs 
> 
> How can i use custom color with opacity for hex color codes?

I don't think it's possible. You need to use RGBA values for that. I suggest using a HEX to RGBA converter that you can easily find with a quick Google search 👍🏻

**Comment by kingrea** [comment]
> The `<alpha-value>` isn't required in the `tailwind.config.ts` file. What's causing the problem is the use of commas between the HSL values.
> 
> ```diff
> /* global.css */
> - --success: 164, 95%, 43%;
> + --success: 164 95% 43%;
> - --success-foreground: 164, 95%, 23%;
> + --success-foreground: 164 95% 23%;
> ```

Legend, saved my soul. Thought I was damned for a moment there.

**Comment by vixalien** [comment]
> The <alpha-value> isn't required in the tailwind.config.ts file. What's causing the problem is the use of commas between the HSL values.
> 
> ```patch
> /* global.css */
> - --success: 164, 95%, 43%;
> + --success: 164 95% 43%;
> - --success-foreground: 164, 95%, 23%;
> + --success-foreground: 164 95% 23%;
> ```

This doesn't work for me, and I still need to add the `<alpha-value>`

**Comment by bilguun1130** [comment]
how about using oklch values in my global.css it is  
```
 --primary: oklch(0.8148 0.0819 225.7537);
  --primary-foreground: oklch(0.3348 0.0526 161.6917); 
```
and in my tailwind config    
   
```
primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        }, 
```
and in my button i have a 
`className='bg-primary text-primary-foreground hover:bg-primary/90'` 
and it does not seem to apply the opacity effect but if i change the hover to different color it works. It is just the opacity thats the problem.

**Comment by okejminja** [comment]
> how about using oklch values in my global.css it is
> 
> ```
>  --primary: oklch(0.8148 0.0819 225.7537);
>   --primary-foreground: oklch(0.3348 0.0526 161.6917); 
> ```
> 
> and in my tailwind config
> 
> ```
> primary: {
>           DEFAULT: 'var(--primary)',
>           foreground: 'var(--primary-foreground)',
>         }, 
> ```
> 
> and in my button i have a `className='bg-primary text-primary-foreground hover:bg-primary/90'` and it does not seem to apply the opacity effect but if i change the hover to different color it works. It is just the opacity thats the problem.

Did you figure the opacity with OKLCH? I have a similar config to yours
