### ISSUE TITLE
Color picker GUI for picking the theme/colors?

### ISSUE THREAD

**Issue by dBianchii** [shadcn/ui#819]
I was thinking about constructing some kind of GUI that interacts with the user's defined css file to alter each hsl values.
Kind of like this website: https://palettemaker.com/app. Here you can select each color with a swatch picker as well as choose from pre-defined themes.

With this GUI, one could select the said pallete for dark/white theme and hit an 'apply' button that would alter the contents of the globals.css file.

You could then see the changes live on your website, since saving the .css file automatically applies the changes to the project while it is running

**Comment by dan5py** [comment]
Hi @dBianchii, the theme customizer is alredy planned. It will be available directly in the docs. 🚀

**Comment by AlexMNet** [comment]
> Hi @dBianchii, the theme customizer is alredy planned. It will be available directly in the docs. 🚀

This is going to be so helpful! Is there an estimated timeline as to when this will be available?
