### ISSUE TITLE
Input doesn’t work (sometimes)

### ISSUE THREAD

**Issue by paambaati** [shadcn/ui#83]
Attaching a video to better explain this, but sometimes, input fields don’t display what’s being entered, on mobile.

https://user-images.githubusercontent.com/5381764/218708262-ecc898da-cd02-4fb6-949b-4e0a6cb22540.MOV

**Comment by Snopkowski** [comment]
Fixed here #103

**Comment by shadcn** [comment]
Merged. Thanks.
