### ISSUE TITLE
Sheet content does not accept className styles

### ISSUE THREAD

**Issue by shamar-morrison** [shadcn/ui#837]
I have the following component which uses the sheet component and I am setting custom styles on the sheet content and sheet overlay but the styles aren't taking effect. 

I'm not sure if you can edit the sheet overlay styles using classes but according to the docs you should be able to do it for the sheet content.

```jsx
function QuizItemsSheet(props: Props) {
  return (
    <Sheet>
      <SheetTrigger>
        <Icons.addItem
          width={25}
          className='mx-4 group-hover:stroke-slate-300'
        />
      </SheetTrigger>
      <SheetOverlay className='bg-transparent backdrop-blur-none' /> {/*<-- These classes are not being applied*/}
      <SheetContent className='w-[12000px]'> {/*<-- This class is not being applied*/}
        <SheetHeader>
          <SheetTitle>New Items</SheetTitle>
          <SheetDescription>Add New quiz items from here</SheetDescription>
        </SheetHeader>
      </SheetContent>
    </Sheet>
  )
}
```

docs: https://ui.shadcn.com/docs/components/sheet

**Comment by dan5py** [comment]
Hi @shamar-morrison. The `SheetContent` component has the `sm:max-w-sm` classname so if you want to set a size beyond that you have to add this class `sm:max-w-none` to it. The `SheetOverlay` is not exported by default as it's already added to the `Sheet` component, so your implementation is adding another overlay and not customizing the existing one. You can however edit the overlay in the `sheet.tsx` file or remove it completely.
