### ISSUE TITLE
shadcn-ui cli stuck on monorepo using nx.

### ISSUE THREAD

**Issue by matheralvs** [shadcn/ui#841]
I'm using the shadcn-ui components in my monorepo (using nx to manage it), however, when trying to initialize, with `npx shadcn-ui@latest init`, using nx:run-commands inside the ui folder, the CLI simply hangs. Would it be a problem with the CLI itself or with the nx manager? I'm trying to integrate into the ui lib, however I keep having this initialization problem.

The application is found [here](https://github.com/matheralvs/nxmonorepo-shadcn-ui).

Tests:

- I tried to init in another project to simulate as if it were given in the current project, it even worked, but the part of adding components was also stuck;

**Comment by ruru-m07** [comment]
@matheralvs how u fix it?

**Comment by matheralvs** [comment]
@ruru-m07 An alternative to this problem can be found at #537

**Comment by ruru-m07** [comment]
@matheralvs thanks 😊
