### ISSUE TITLE
Sheet with anchor links

### ISSUE THREAD

**Issue by gosvoh** [shadcn/ui#844]
Problem exists on the latest version if shadch ui. Page resets to the top when you click on a link to an anchor on the same page.

Current behavior:

https://github.com/shadcn/ui/assets/8506620/f123c27d-3035-47a7-a84a-66aa3d5dfd19

Expected behavior:

https://github.com/shadcn/ui/assets/8506620/627ce5bf-777d-4280-85a3-1aabfe2b3322

**Comment by dan5py** [comment]
Hi @gosvoh, this is a problem related to the `RadixUI` dialog primitive. May I ask what did you changed to get the expected behavior?

**Comment by gosvoh** [comment]
> Hi @gosvoh, this is a problem related to the `RadixUI` dialog primitive. May I ask what did you changed to get the expected behavior?

Unfortunately I used a video editor because I have no idea how to fix it

**Comment by joaom00** [comment]
Seems to be the autofocus on the trigger when the sheet closes. You can try `onCloseAutoFocus={event => event.preventDefault()}` in `SheetContent`

**Comment by gosvoh** [comment]
> Seems to be the autofocus on the trigger when the sheet closes. You can try `onCloseAutoFocus={event => event.preventDefault()}` in `SheetContent`

That solved the problem, thank you! I think it'll break the built-in accessibility features, but I'll work on that

**Comment by joaom00** [comment]
Yeah, you need to move the focus to something in the targeted section

**Comment by raishudesu** [comment]
> Seems to be the autofocus on the trigger when the sheet closes. You can try `onCloseAutoFocus={event => event.preventDefault()}` in `SheetContent`

I encountered this issue and I've been looking for ways to solve it. Thank you so much for this!

**Comment by ijohnpaul2000** [comment]
> Seems to be the autofocus on the trigger when the sheet closes. You can try `onCloseAutoFocus={event => event.preventDefault()}` in `SheetContent`

Can you further explain this behavior since it fixed my issue as well?
