### ISSUE TITLE
ElementRef not found

### ISSUE THREAD

**Issue by DevKoenv** [shadcn/ui#853]
Some components that use the React.ElementRef cause errors, (elements like avatar or dialog)
React version: ``18.2.0``

Just clean installed the Next.js project and shadcn

Errors:
``'React' has no exported member named 'ElementRef'. Did you mean 'CElement'?``

Code:
```javascript
const DialogDescription = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Description>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Description>
>(({ className, ...props }, ref) => (
  <DialogPrimitive.Description
    ref={ref}
    className={cn("text-sm text-muted-foreground", className)}
    {...props}
  />
))
DialogDescription.displayName = DialogPrimitive.Description.displayName
```

It isn't only that code, its everywhere the React.ElementRef gets used. 
Anyone have an idea on how to fix this?
If any more information is necessary I'm glad to help

**Comment by dan5py** [comment]
Hi @DevKoenv, can you try to reinstall `@types/react` ?
