### ISSUE TITLE
Manual installation getting error "border-border` class does not exist"

### ISSUE THREAD

**Issue by onattech** [shadcn/ui#855]
Hi, 
Thank you for the great work. I am trying the manual setup for a Docusaurus project. I am getting the following error.

`` The `border-border` class does not exist. If `border-border` is a custom class, make sure it is defined within a `@layer` directive. ``

I had to turn off preflight to avoid interference with Docusaurus' default styling.

**Comment by codePassion-dot** [comment]
I think this should be reopen because if you disable the preflight you're losing all the browser resetting and tweaks we used to do manually in the global css file

**Comment by onattech** [comment]
I closed this issue because I opened another one to better explain the issue. Didn't really get any attention. Feel free to comment there so maybe we grap some attention.
Here's the other issue https://github.com/shadcn/ui/issues/856
