### ISSUE TITLE
Documentation Correction

### ISSUE THREAD

**Issue by yassinmoussamih** [shadcn/ui#861]
**Error in documentation page [Installation-NextJS](https://ui.shadcn.com/docs/installation/next)**
This import is incorrect it should be ```import { Button } from @/components/ui/button```

![image](https://github.com/shadcn/ui/assets/79911341/fc1fcefa-192c-48e5-bf44-603b96e0cf92)

**Comment by dan5py** [comment]
Hi @yassinmoussamih, #839 fixes the incorrect import in the installation guides.
