### ISSUE TITLE
Performance issue when opening `search documentation` on `ui.shadcn.com`

### ISSUE THREAD

**Issue by TechTheAwesome** [shadcn/ui#862]
SYSTEM INFO
- Linux / Fedora 
- Firefox

DESCRIPTION
Opening the popup pannel takes more than a second, and hovering between each search items is laggy.

**Comment by dan5py** [comment]
Hi @TechTheAwesome, do you have Hardware Acceleration disabled in your browser?

**Comment by TechTheAwesome** [comment]
Oh... I wouldn't have expect simple animation and blur would take such a performance hit when disabling hardware acceleration... 
:sweat_smile: well thanks for your help again dan, sorry if I am bothering you with what turned out to be trivial issues.

**Comment by dan5py** [comment]
No worries, I’m here to help.
