### ISSUE TITLE
SearchBar content seems blurry 

### ISSUE THREAD

**Issue by abbbringu** [shadcn/ui#864]
I explored the [documentation](https://ui.shadcn.com/docs), pressed the **search bar**, and discovered the content was blurry. 
This happened in my case when the screen size is **over** sm (small) both on edge and chrome. 

_(The image below shows which component. The image is not an accurate representation of the problem)_
<img src="https://i.ibb.co/zhk82SW/Screenshot-2023-07-06-at-20-23-11.png" width="800" />
If this is only a problem on my side, I would greatly appreciate a response. Thank you for taking the time to read this, and have a great day. 👋

**Comment by dan5py** [comment]
Hi @abbbringu, this is a duplicate of #711.
