### ISSUE TITLE
Multiple Slider thumb

### ISSUE THREAD

**Issue by Ghoral** [shadcn/ui#871]
Hi,
How can I add multiple `SliderPrimitive.Thumb` in slider and slide from both sides?

Thank you.

**Comment by dan5py** [comment]
Hi @Ghoral, you can simply duplicate the `SliderPrimitive.Thumb` component in the `slider.tsx`. Remember to update the default value to an array with two values:

```tsx
```

**Comment by Ghoral** [comment]
Thankyou..works perferctly fine

**Comment by JunaidShaikh2498** [comment]
Hey can you please explain what the classname in cn function is?

**Comment by Klerith** [comment]
> Hey can you please explain what the classname in cn function is?

This cn function merges CSS class names using clsx and combines them with Tailwind CSS utility classes using twMerge. It's commonly used in React projects to simplify the process of combining class names.

**Comment by cupid20103** [comment]
Great! @dan5py
