### ISSUE TITLE
Button inside SheetTrigger hydration error

### ISSUE THREAD

**Issue by jasan-s** [shadcn/ui#874]
>Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.
Warning: Expected server HTML to contain a matching < button > in < button >.

**Comment by dan5py** [comment]
Hi @jasan-s, did you add the `asChild` prop to the `SheeTrigger` component?

**Comment by jasan-s** [comment]
That fixed it

**Comment by ivan2214** [comment]
That fixed it

**Comment by Kejooorek** [comment]
yes, it works :D
