### ISSUE TITLE
How to get access of useFormField inside Input Component?

### ISSUE THREAD

**Issue by abhiskg** [shadcn/ui#890]
### I want to change the border color of the input field when there is an error in the form.  
I need the error state from useFormField
`const { error} = useFormField();`

How can I get it here?

```
    <FormField
      control={form.control}
      name={name}
      render={({ field }) => (
        <FormItem>
          {label && (
            <FormLabel className="text-base font-medium">{label}</FormLabel>
          )}
          <FormControl>
            <Input
              placeholder={placeholder}
              type={type ? type : 'text'}
              {...field}
            />
          </FormControl>
          <FormMessage />
        </FormItem>
      )}
    />
```

**Comment by pedrovrima** [comment]
See if the code in this PR helps you:
https://github.com/shadcn/ui/pull/754

**Comment by abhiskg** [comment]
> See if the code in this PR helps you: #754

Thanks, It works. Hope your PR gets merged soon.

**Comment by abhiskg** [comment]
> See if the code in this PR helps you: #754

In this PR you can add `focus-visible:ring-destructive`
