### ISSUE TITLE
[FEATURE REQUEST] Nuxt 3 compatibility

### ISSUE THREAD

**Issue by ddahan** [shadcn/ui#899]
Hi, any chance that this amazing <s>library</s> collection of components, can be used with Nuxt 3?

**Comment by evanlong0926** [comment]
It's up to `radix-ui`.

**Comment by ddahan** [comment]
Oh thanks. As I found an issue for that open 2 years ago, I think it won't be possible.

**Comment by ddahan** [comment]
My bad, there is a current initiative for this: https://github.com/radix-vue/radix-vue

**Comment by evanlong0926** [comment]
It's a good choice for the Nuxt3.

**Comment by miztizm** [comment]
shadcn-ui is compatible with Nuxt 3? I can't find any answers. Thanks.
