### ISSUE TITLE
Close calendar

### ISSUE THREAD

**Issue by Ghoral** [shadcn/ui#901]
Hi,
We can open the calendar but unable to to close it when date is selected. How can we close the calendar when date is selected.

Thank you

**Comment by alexjoedt** [comment]
Hi Ghoral,
actually, if you using the [Date Picker](https://ui.shadcn.com/docs/components/date-picker) you can close the calendar when you click the DatePicker Button again or anywhere else except on the calendar.

Moreover you can add the `PopoverClose` Component from `@radix-ui/react-popover` lise so:

```tsx
    <Popover>
      <PopoverTrigger asChild>
        <Button
          variant={"outline"}
          className={cn(
            "w-[300px] justify-start text-left font-normal text-primary",
            !value && "text-muted-foreground"
          )}
        >
          <CalendarIcon className="mr-2 h-4 w-4" />
          {value ? format(value, "dd.MM.yy") : <span>{label ? label : "Pick a date"}</span>}
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-auto p-0">
        <div  className="flex m-1">
          <div className="flex-1"></div>
          <PopoverClose>
            <CloseIcon size={24} className="text-primary/60 hover:text-destructive" />
          </PopoverClose>
        </div>

        <Calendar
          mode="single"
          selected={value}
          onSelect={handleSelectDate}
          initialFocus
        />
      </PopoverContent>
    </Popover>
```

I hope that helps.

**Comment by Ghoral** [comment]
Thank you that helped

**Comment by liuhe2020** [comment]
Any idea how to close the modal on select when using it inside a form?
`onSelect={field.onChange}`
How do I manually add the close function here?

**Comment by FranckL01** [comment]
Not sure this is the right way but it works: 
- Add "const PopoverClose = PopoverPrimitive.PopoverClose" to  your popover ui file + export
- Import it in your DatePicker component and wrap the Calendar:
```
<PopoverClose>
               <Calendar
                  mode="single"
                  selected={date}
                  onSelect={setDate}
                  initialFocus
               />
            </PopoverClose> 
```

**Comment by liuhe2020** [comment]
Thank @FranckL01 for trying, good effort but not quite. It prompted me to have another go at it and I figured it out. 

So what you did was wraping the popover content inside a popover close 'button' so anywhere you click on the content which is the calendar, will close the popover, this includes not only clicking on the dates, but also any other button or white space on the calendar UI.

I went back to read the Radix doc again and I already know that we can control the popover state by 

`const [isCalendarOpen, setIsCalendarOpen] = useState(false);

<Popover open={isCalendarOpen} onOpenChange={setIsCalendarOpen}>`

The last bit that I was stuck on was `onSelect={field.onChange}`, I knew that I had to pass the setState in here to close the popover but I didn't know how, so I played with it a bit more and it turned out to be quite obvious and I was just dumb.

Here is the solution
`onSelect={(e) => {
 field.onChange(e);
 setIsCalendarOpen(false);
}}`

And here is my component
`
 <FormField
            control={form.control}
            name='date'
            render={({ field }) => (
              <FormItem className='flex flex-col'>
                <FormLabel>Date</FormLabel>
                <Popover open={isCalendarOpen} onOpenChange={setIsCalendarOpen}>
                  <PopoverTrigger asChild>
                    <FormControl>
                      <Button variant={'outline'} className={cn('justify-start text-left font-normal', !field.value && 'text-muted-foreground')}>
                        <CalendarIcon className='mr-2 h-4 w-4' />
                        {field.value ? format(field.value, 'd MMMM yyyy') : <span>Pick a date</span>}
                      </Button>
                    </FormControl>
                  </PopoverTrigger>
                  <PopoverContent className='w-auto p-0' align='start'>
                    <Calendar
                      mode='single'
                      selected={field.value}
                      onSelect={(e) => {
                        field.onChange(e);
                        setIsCalendarOpen(false);
                      }}
                      disabled={(date) => date > new Date() || date < new Date('1900-01-01')}
                      initialFocus
                      captionLayout='dropdown-buttons'
                      fromDate={new Date(new Date().getFullYear() - 100, new Date().getMonth(), new Date().getDate())}
                      toDate={new Date()}
                      classNames={{
                        day_selected:
                          'bg-indigo-500 text-primary-foreground hover:bg-primary hover:text-primary-foreground focus:bg-indigo-500 focus:text-primary-foreground',
                      }}
                    />
                  </PopoverContent>
                </Popover>
                <FormMessage />
              </FormItem>
            )}
          />
`

**Comment by FranckL01** [comment]
Nice, thanks for the update !

**Comment by Adam-Collier** [comment]
If it's helpful for anyone here, the way I've approached it is like the below:
```
export function DatePicker({ selected, onSelect }) {
  const [isPopoverOpen, setIsPopoverOpen] = React.useState(false)

  const handleOnSelect: SelectSingleEventHandler = (date) => {
    onSelect?.(date)
    setIsPopoverOpen(false)
  }

  return (
    <Popover open={isPopoverOpen} onOpenChange={setIsPopoverOpen}>
      <PopoverTrigger asChild>
        <Button
          variant={'outline'}
          className={cn('w-[240px] justify-start text-left font-normal', !selected && 'text-muted-foreground')}
        >
          <CalendarIcon className="mr-2 h-4 w-4" />
          {selected ? format(selected, 'PPP') : <span>Pick a date</span>}
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-auto p-0" align="start">
        <Calendar mode="single" selected={selected} onSelect={handleOnSelect} initialFocus />
      </PopoverContent>
    </Popover>
  )
}
```
and then using it like so:
```
<FormItem className="flex flex-col">
    <FormLabel>DatePicker</FormLabel>
    <FormControl>
    <DatePicker
        selected={field.value}
        onSelect={(value: string) => {
        field.onChange(value)
        }}
    />
    </FormControl>
    <FormMessage />
</FormItem>
```

**Comment by sergey-sviridov** [comment]
@liuhe2020, thank you very much!

**Comment by mtnoronha** [comment]
Hi guys, in my opinion using state like @Adam-Collier is the best way to solve this issue because the `PopoverClose` approach closes the calendar even if you click on the arrows to navigate the months. 

And thank you Adam, btw, you rock.

**Comment by liuhe2020** [comment]
> Hi guys, in my opinion using state like @Adam-Collier is the best way to solve this issue because the `PopoverClose` approach closes the calendar even if you click on the arrows to navigate the months.
> 
> And thank you Adam, btw, you rock.

I have to agree, I notice that too as I wasn't testing it properly in my original build.

**Comment by nimeshmaharjan1** [comment]
so i have implemented the year selection too but the issue here is that if i have selected something like 5th March 1984 and the close the calendar and open it again it shows the today date month and year can anyone help me on this?

` <FormField
            control={form.control}
            name="delivery_required_date"
            render={({ field }) => (
              <FormItem className="flex gap-1 flex-col">
                <FormLabel>
                  Required By <span className="text-destructive">*</span>
                </FormLabel>
                <Popover>
                  <PopoverTrigger asChild>
                    <FormControl>
                      <Button
                        disabled={isFinalized}
                        variant={'outline'}
                        className={cn(
                          'w-44 text-left block font-normal text-foreground disabled:opacity-100',
                          !field.value && 'text-muted-foreground'
                        )}
                      >
                        {field.value ? (
                          format(field.value, 'MMM do, yyyy')
                        ) : (
                          <span>Pick a date</span>
                        )}
                        {/* <CalendarIcon className="ml-auto h-4 w-4 opacity-50" /> */}
                      </Button>
                    </FormControl>
                  </PopoverTrigger>
                  <PopoverContent className="w-auto p-0" align="start">
                    <Calendar
                      mode="single"
                      selected={field.value}
                      onSelect={(e) => {
                        if (e) {
                          field.onChange(e);
                        }
                      }}
                      //For year selection
                      captionLayout="dropdown-buttons"
                      fromYear={1940}
                      toYear={new Date().getFullYear()}
                    />
                  </PopoverContent>
                </Popover>
                <FormMessage />
              </FormItem>
            )}
          />`

**Comment by nimeshmaharjan1** [comment]
> @nimeshmaharjan1  I've done something like this on the trigger:
> 
> ```JSX
> export function DatePicker({
>   date,
>   onSelect,
>   className,
>   required,
> }: DatePickerProps) {
>   const [isPopoverOpen, setIsPopoverOpen] = React.useState(false);
> 
>   const handleOnSelect: SelectSingleEventHandler = (date) => {
>     onSelect?.(date);
>     setIsPopoverOpen(false);
>   };
> 
> // ...
>       <PopoverTrigger asChild>
>         <Button
>           variant={'outline'}
>           className={cn(
>             'justify-start text-left font-normal',
>             !date && 'text-muted-foreground',
>             className,
>           )}
>         >
>           <CalendarIcon className="mr-2 h-4 w-4" />
>           {date ? (
>             format(date, DATE_FORMAT_FOR_DISPLAY, { locale: ptBR })
>           ) : (
>             <span>Escolha uma data</span>
>           )}
>         </Button>
>       </PopoverTrigger>
> 
> ```

Thank you but I meant when the selected date is 3rd March 2010 when I open the calendar it doesn't redirect to that particular date and instead shows the default today date

**Comment by mtnoronha** [comment]
> ted date is 3rd March 2010 when I open the calendar it doesn't redirect to that particular date and instead shows the default today date

Ohhh ok, sorry about that. I think you just need to set `defaultMonth={date}`

**Comment by Priyansu67** [comment]
The problem with wrapping the whole calendar component with `PopoverClose` is that it will close for every click inside the component, so even if you are clicking on next or prev button it will trigger close. The calendar component internally uses `DayPicker` from [react-day-picker](https://react-day-picker.js.org/) which allows us to modify it's inner [components](https://react-day-picker.js.org/advanced-guides/custom-components), using this we can wrap the days with a `PopoverClose`.

Use this instead:

```
<DayPicker
   components={{
         DayContent: (props) => {
            return <PopoverClose>{props.date.getDate()}</PopoverClose>;
        },
      }} 
 />
```

**Comment by 9mm** [comment]
It seems extremely weird to me this isnt built in. What datepicker ever should remain open by default and require these insane hacks to simply close on select.....

**Comment by sergesteban** [comment]
> Thank @FranckL01 for trying, good effort but not quite. It prompted me to have another go at it and I figured it out.
> 
> So what you did was wraping the popover content inside a popover close 'button' so anywhere you click on the content which is the calendar, will close the popover, this includes not only clicking on the dates, but also any other button or white space on the calendar UI.
> 
> I went back to read the Radix doc again and I already know that we can control the popover state by
> 
> `const [isCalendarOpen, setIsCalendarOpen] = useState(false);` `<Popover open={isCalendarOpen} onOpenChange={setIsCalendarOpen}>`
> 
> The last bit that I was stuck on was `onSelect={field.onChange}`, I knew that I had to pass the setState in here to close the popover but I didn't know how, so I played with it a bit more and it turned out to be quite obvious and I was just dumb.
> 
> Here is the solution `onSelect={(e) => { field.onChange(e); setIsCalendarOpen(false); }}`

it worked for me. thanks

**Comment by luispazcode** [comment]
> Thank @FranckL01 for trying, good effort but not quite. It prompted me to have another go at it and I figured it out.
> 
> So what you did was wraping the popover content inside a popover close 'button' so anywhere you click on the content which is the calendar, will close the popover, this includes not only clicking on the dates, but also any other button or white space on the calendar UI.
> 
> I went back to read the Radix doc again and I already know that we can control the popover state by
> 
> `const [isCalendarOpen, setIsCalendarOpen] = useState(false);` `<Popover open={isCalendarOpen} onOpenChange={setIsCalendarOpen}>`
> 
> The last bit that I was stuck on was `onSelect={field.onChange}`, I knew that I had to pass the setState in here to close the popover but I didn't know how, so I played with it a bit more and it turned out to be quite obvious and I was just dumb.
> 
> Here is the solution `onSelect={(e) => { field.onChange(e); setIsCalendarOpen(false); }}`

It's worked for me, thank you man. You saved me!!

**Comment by jaggerharness** [comment]
Another solution to the problem if you don't feel like having to manage the state is to use the useRef hook. My implementation looks something like this:

```typescript
const popOverRef = useRef<HTMLButtonElement | null>(null);

<PopoverContent className="z-50 w-auto p-0" align="start">
  <PopoverClose ref={popOverRef} />
  <Calendar
    className="pointer-events-auto"
    mode="single"
    selected={field.value}
    onSelect={(e) => {
      field.onChange(e);
      popOverRef.current?.click();
    }}
    disabled={(date) =>
      date < new Date(new Date().setHours(0, 0, 0, 0))
    }
  />
</PopoverContent>
```

I'm not sure if there are any downsides to this approach but it seems to be working fine for me.

**Comment by sahand-sn** [comment]
> ```ts
> onSelect={(e) => {
>       field.onChange(e);
>       popOverRef.current?.click(); // closes popover
>     }}
> ```

exactly what i was looking for. thanks!

**Comment by Hombre2014** [comment]
> Not sure this is the right way but it works:
> 
> * Add "const PopoverClose = PopoverPrimitive.PopoverClose" to  your popover ui file + export
> * Import it in your DatePicker component and wrap the Calendar:
> 
> ```
> <PopoverClose>
>    <Calendar
>       mode="single"
>       selected={date}
>       onSelect={setDate}
>       initialFocus
>    />
> </PopoverClose> 
> ```

Thanks @FranckL01 
The problem with this pretty simple solution is that it closes the component not only when you select a date, but also when you click on '<' or '>', with the intention to select the previous or the next month and you do not want to close the calendar, because you did not choose a date, but the component is gone. So, it works only when you can select a date within the open month.

**Comment by jayPreak** [comment]
> Another solution to the problem if you don't feel like having to manage the state is to use the useRef hook. My implementation looks something like this:
> 
> ```ts
> const popOverRef = useRef<HTMLButtonElement | null>(null);
> 
> <PopoverContent className="z-50 w-auto p-0" align="start">
>   <PopoverClose ref={popOverRef} />
>   <Calendar
>     className="pointer-events-auto"
>     mode="single"
>     selected={field.value}
>     onSelect={(e) => {
>       field.onChange(e);
>       popOverRef.current?.click(); // closes popover
>     }}
>     disabled={(date) =>
>       date < new Date(new Date().setHours(0, 0, 0, 0))
>     }
>   />
> </PopoverContent>
> ```
> 
> I'm not sure if there are any downsides to this approach but it seems to be working fine for me.

Works really well, thanks!

**Comment by kibrukuture** [comment]
> Another solution to the problem if you don't feel like having to manage the state is to use the useRef hook. My implementation looks something like this:
> 
> ```ts
> const popOverRef = useRef<HTMLButtonElement | null>(null);
> 
> <PopoverContent className="z-50 w-auto p-0" align="start">
>   <PopoverClose ref={popOverRef} />
>   <Calendar
>     className="pointer-events-auto"
>     mode="single"
>     selected={field.value}
>     onSelect={(e) => {
>       field.onChange(e);
>       popOverRef.current?.click(); // closes popover
>     }}
>     disabled={(date) =>
>       date < new Date(new Date().setHours(0, 0, 0, 0))
>     }
>   />
> </PopoverContent>
> ```
> 
> I'm not sure if there are any downsides to this approach but it seems to be working fine for me.

works like charm. thanks mate.

**Comment by internetdrew** [comment]
This helped mucho!

**Comment by sovetski** [comment]
Any proper and official solution in 2025? I checked all solutions above but I think it is something that shadcn have to implement natively, instead of 1000 custom solutions...

**Comment by jayPreak** [comment]
> Any proper and official solution in 2025? I checked all solutions above but I think it is something that shadcn have to implement natively, instead of 1000 custom solutions...

https://github.com/shadcn-ui/ui/issues/901#issuecomment-2351135245

This still works in 2025 for me
