### ISSUE TITLE
ScrollArea doesn't work in Dialog

### ISSUE THREAD

**Issue by neo773** [shadcn/ui#922]
When using `ScrollArea` inside `Dialog` gesture scrolling doesn't work only way to navigate is by grabbing the scroll indicator

https://github.com/shadcn/ui/assets/62795688/ea1abc45-19f7-4969-812e-5b376e1a3f9a

To reproduce this bug
`index.ts`
```tsx
import { Button } from "@/components/ui/button"
import { ComboBox } from "@/components/ui/combo-box"
import { Dialog, DialogContent, DialogTrigger } from "@/components/ui/dialog"

const Demo = () => {
    const languages = [
        { label: "English", value: "en" },
        { label: "French", value: "fr" },
        { label: "German", value: "de" },
        { label: "Spanish", value: "es" },
        { label: "Portuguese", value: "pt" },
        { label: "Russian", value: "ru" },
        { label: "Japanese", value: "ja" },
        { label: "Korean", value: "ko" },
        { label: "Chinese", value: "zh" },
        { label: "Italian", value: "it" },
        { label: "Dutch", value: "nl" },
        { label: "Swedish", value: "sv" },
        { label: "Greek", value: "el" },
        { label: "Czech", value: "cs" },
        { label: "Polish", value: "pl" },
        { label: "Hungarian", value: "hu" },
        { label: "Turkish", value: "tr" },
        { label: "Arabic", value: "ar" },
        { label: "Hebrew", value: "he" },
        { label: "Hindi", value: "hi" }
    ] as const;
    
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline">Test</Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[400px] px-0">
        <ComboBox
          options={languages.map((country) => {
            return {
              value: country.value,
              label: `${country.label}`,
            }
          })}
          placeholder={"Search Country"}
          defaultValue={"en"}
          onValueChange={() => {}}
        />
      </DialogContent>
    </Dialog>
  )
}

export default Demo

```

`ComboBox.ts`
```tsx

import { cn } from "../../lib/utils"
import { Button } from "./button"
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
} from "./command"
import { Popover, PopoverContent, PopoverTrigger } from "./popover"
import { ScrollArea } from "./scroll-area"
import { Check, ChevronsUpDown } from "lucide-react"
import * as React from "react"

interface Item {
  value: string
  label: string
}

interface ComboBoxProps {
  options: Item[]
  defaultValue?: string
  placeholder: string
  className?: string
  onValueChange: (value: string) => void
}

export const ComboBox: React.FC<ComboBoxProps> = ({
  options,
  defaultValue = "",
  placeholder,
  className,
  onValueChange,
}) => {
  const [open, setOpen] = React.useState(false)

  const handleSelect = (currentValue: string) => {
    setOpen(false)
    onValueChange(currentValue)
  }

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          role="ComboBox"
          aria-expanded={open}
          className={cn("w-[350px] justify-between", className)}
        >
          {defaultValue
            ? options.find((option) => option.value === defaultValue)?.label
            : placeholder}
          <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-[350px] p-0">
        <Command>
          <CommandInput
            placeholder={`Search ${placeholder.toLowerCase()}...`}
          />
          <ScrollArea className="h-[200px]">
            <CommandEmpty>No {placeholder.toLowerCase()} found.</CommandEmpty>
            <CommandGroup>
              {options.map((option) => (
                <CommandItem
                  key={option.value}
                  onSelect={() => handleSelect(option.value)}
                >
                  <Check
                    className={cn(
                      "mr-2 h-4 w-4",
                      defaultValue === option.value
                        ? "opacity-100"
                        : "opacity-0"
                    )}
                  />
                  {option.label}
                </CommandItem>
              ))}
            </CommandGroup>
          </ScrollArea>
        </Command>
      </PopoverContent>
    </Popover>
  )
}

```

**Comment by neo773** [comment]
> You can make a couple of things:
> 
> 1. Not render the `Portal` component in popover (Maybe you have `z-index` issues)
> 2. Set `modal={false}` on Dialog (The overlay will no be rendered)
> 3. Wrap `Dialog.Content` with `Dialog.Overlay` (You can not set `modal={false}` because the overlay will not be rendered)

The 3rd option worked, Thanks.

**Comment by Anish-Karthik** [comment]
could you post the working code

**Comment by KaramveerSinghSidhu** [comment]
I am having the same issue. 
`<FormField
          control={form.control}
          name="timezone"
          render={({ field }) => (
            <FormItem className="flex flex-col">
              <FormLabel>Timezone</FormLabel>
              <Popover>
                <PopoverTrigger asChild>
                  <FormControl>
                    <Button
                      variant="outline"
                      role="combobox"
                      className={cn(
                        "w-[200px] justify-between",
                        !field.value && "text-muted-foreground"
                      )}
                    >
                      {field.value
                        ? TimeZones.find((timezone) => timezone === field.value)
                        : "Select timezone"}
                      <CaretSortIcon className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                    </Button>
                  </FormControl>
                </PopoverTrigger>
                <PopoverContent className="w-[200px] p-0">
                  <Command>
                    <CommandInput placeholder="Search timezone..." />
                    <CommandEmpty>No timezone found.</CommandEmpty>
                    <ScrollArea className="h-60">
                      <CommandGroup>
                        {TimeZones.map((timezone) => (
                          <CommandItem
                            value={timezone}
                            key={timezone}
                            onSelect={() => {
                              form.setValue("timezone", timezone);
                            }}
                          >
                            <CheckIcon
                              className={cn(
                                "mr-2 h-4 w-4",
                                timezone === field.value
                                  ? "opacity-100"
                                  : "opacity-0"
                              )}
                            />
                            {timezone}
                          </CommandItem>
                        ))}
                      </CommandGroup>
                    </ScrollArea>
                  </Command>
                </PopoverContent>
              </Popover>
              <FormMessage />
            </FormItem>
          )}
        />`

**Comment by aleciavogel** [comment]
In order to make the `ScrollArea` work inside of a `Dialog`, I ended up having to add a `container` prop to my `PopoverContent`, like so:

```typescript
interface PopoverContentProps {
  container?: HTMLElement
}

const PopoverContent = React.forwardRef<
  React.ElementRef<typeof PopoverPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof PopoverPrimitive.Content> & PopoverContentProps
>(({ className, container, align = 'center', sideOffset = 4, ...props }, ref) => (
  <PopoverPrimitive.Portal container={container}>
    <PopoverPrimitive.Content
      ref={ref}
      align={align}
      sideOffset={sideOffset}
      className={cn(
      ...
```

Then I wrapped all `<CommandItem />`'s inside of a `ScrollArea` with a `className` of `h-[300px]` so that the search will remain at the top while I can scroll through all of the options.

Finally, in the component where I define the `Dialog` that wraps everything, I defined a `dialogRef`, like so:

```typescript
  const dialogRef = React.useRef<HTMLDivElement>(null)

  return (
    <Dialog defaultOpen>
      <DialogContent
        ref={dialogRef}
        ...
```

I also had to add the `dialogRef` to my `ComboBox` props.

```typescript
interface ComboboxProps {
  // All my other props are defined above here...
  dialogRef?: React.RefObject<HTMLElement>
}

const Combobox: FC<ComboboxProps> = ({
  dialogRef,
  ...
```

Lastly, add your `dialogRef` to the `PopoverContent` inside of the `ComboBox`:

```typescript
<PopoverContent
  container={dialogRef?.current === null ? undefined : dialogRef?.current}
  className="w-[350px] p-0"
>
```

So now you should be able to use your `ComboBox` and the `ScrollArea` should do its magic:

```typescript
<Combobox dialogRef={dialogRef} />
```

Hope this helps!

**Comment by desiboli** [comment]
> I am having the same issue.
> 
> ```
> <FormField
>           control={form.control}
>           name="timezone"
>           render={({ field }) => (
>             <FormItem className="flex flex-col">
>               <FormLabel>Timezone</FormLabel>
>               <Popover>
>                 <PopoverTrigger asChild>
>                   <FormControl>
>                     <Button
>                       variant="outline"
>                       role="combobox"
>                       className={cn(
>                         "w-[200px] justify-between",
>                         !field.value && "text-muted-foreground"
>                       )}
>                     >
>                       {field.value
>                         ? TimeZones.find((timezone) => timezone === field.value)
>                         : "Select timezone"}
>                       <CaretSortIcon className="ml-2 h-4 w-4 shrink-0 opacity-50" />
>                     </Button>
>                   </FormControl>
>                 </PopoverTrigger>
>                 <PopoverContent className="w-[200px] p-0">
>                   <Command>
>                     <CommandInput placeholder="Search timezone..." />
>                     <CommandEmpty>No timezone found.</CommandEmpty>
>                     <ScrollArea className="h-60">
>                       <CommandGroup>
>                         {TimeZones.map((timezone) => (
>                           <CommandItem
>                             value={timezone}
>                             key={timezone}
>                             onSelect={() => {
>                               form.setValue("timezone", timezone);
>                             }}
>                           >
>                             <CheckIcon
>                               className={cn(
>                                 "mr-2 h-4 w-4",
>                                 timezone === field.value
>                                   ? "opacity-100"
>                                   : "opacity-0"
>                               )}
>                             />
>                             {timezone}
>                           </CommandItem>
>                         ))}
>                       </CommandGroup>
>                     </ScrollArea>
>                   </Command>
>                 </PopoverContent>
>               </Popover>
>               <FormMessage />
>             </FormItem>
>           )}
>         />
> ```

Instead of ScrollArea, use the CommandList component like so:

```typescript
<Command>
                    <CommandInput placeholder="Search language..." />
                    <CommandList>
                      <CommandEmpty>No language found.</CommandEmpty>
                      <CommandGroup>
                        {countryOptions.map((country) => {
                          console.log("COUNTRY>>>>", country)
                          return (
                            <CommandItem
                              value={country.label}
                              key={country.value}
                              onSelect={() => {
                                form.setValue("country", country.value)
                              }}
                            >
                              <CheckIcon
                                className={cn(
                                  "mr-2 h-4 w-4",
                                  country.value === field.value
                                    ? "opacity-100"
                                    : "opacity-0"
                                )}
                              />
                              {country.label}
                            </CommandItem>
                          )
                        })}
                      </CommandGroup>
                    </CommandList>
                  </Command>
```

**Comment by KaramveerSinghSidhu** [comment]
@desiboli still not working. 

        <FormField
          control={form.control}
          name="timezone"
          render={({ field }) => (
            <FormItem className="flex flex-col">
              <FormLabel>Timezone</FormLabel>
              <Popover>
                <PopoverTrigger asChild>
                  <FormControl>
                    <Button
                      variant="outline"
                      role="combobox"
                      className={cn(
                        "w-[200px] justify-between",
                        !field.value && "text-muted-foreground"
                      )}
                    >
                      {field.value
                        ? TimeZones.find((timezone) => timezone === field.value)
                        : "Select timezone"}
                      <CaretSortIcon className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                    </Button>
                  </FormControl>
                </PopoverTrigger>
                <PopoverContent className="w-[200px] p-0">
                  <Command>
                    <CommandInput placeholder="Search language..." />
                    <CommandList>
                      <CommandEmpty>No language found.</CommandEmpty>
                      <CommandGroup>
                        {TimeZones.map((timezone) => {
                          return (
                            <CommandItem
                              value={timezone}
                              key={timezone}
                              onSelect={() => {
                                form.setValue("timezone", timezone);
                              }}
                            >
                              <CheckIcon
                                className={cn(
                                  "mr-2 h-4 w-4",
                                  timezone === field.value
                                    ? "opacity-100"
                                    : "opacity-0"
                                )}
                              />
                              {timezone}
                            </CommandItem>
                          );
                        })}
                      </CommandGroup>
                    </CommandList>
                  </Command>
                </PopoverContent>
              </Popover>
              <FormMessage />
            </FormItem>

**Comment by 7hourspg** [comment]
Set "modal={true}" in popover like this✔
` <Popover open={open} modal={true}>`
Thanks 😎

**Comment by max-programming** [comment]
Isn't there a straightforward way to show a scroll bar on a `Dialog` if it contains too much content or is too big for the screen to fit?

**Comment by JoelInman-Dev** [comment]
I had this issue with the DropdownMenu component.
In the managed to get this working by simply setting max-h- and overflow-scroll as tailwind classes on the DropdownMenuContent element, also tried it with the PopOverContent and it works, so i would assume this would also work on dialog and commandList

**Comment by projetos-sidnei** [comment]
I was trying to use Shadcnui's ScrollArea, but with popover and dialog it wasn't working, it didn't generate the vertical bar, what helped me was indicating the ref in the Scroll within the ComandList, maybe it will work for someone else, remembering that they didn't want the bar system scrolling.
my code modification:
const CommandList = React.forwardRef<
  React.ElementRef<typeof CommandPrimitive.List>,
  React.ComponentPropsWithoutRef<typeof CommandPrimitive.List>
  >(({ className, ...props }, ref) => (
    <ScrollArea ref={ref}>
    <CommandPrimitive.List
      ref={ref}
      className={cn('h-[400px] overflow-hidden overflow-x-hidden', className)}
      {...props}
      />
      <ScrollBar orientation='vertical'/>
    </ScrollArea>
));

**Comment by Mahesh-Abeykoon** [comment]
> Set `modal={true}` in popover like this ` <Popover open={open} modal={true}>` ✔ Thanks 😎

Really appreciate! Using `modal={true}` inside the `Popover `component fixed the issue with the dropdown not scrolling. ✔

**Comment by jeslenbucci** [comment]
I was able to get the ScrollArea to work with the Dialog by setting a max height to the DialogContent component and then using the ScrollArea component nested within.

```
<Dialog
      open={isOpen}
      onOpenChange={setIsOpen}
    >
      <DialogContent className='h-full max-h-[96%] p-4'>
        <ScrollArea className='p-4'>
          <DialogHeader>
            <DialogTitle asChild>
              <h2>{title}</h2>
            </DialogTitle>
            <DialogDescription>{description}</DialogDescription>
          </DialogHeader>

          {children}

          <DialogFooter className=''>
            <div className='flex justify-center gap-x-2'>
              <DialogClose asChild>
                <Button
                  variant='outline'
                  className='w-full'
                >
                  Cancel
                </Button>
              </DialogClose>
              <Button
                className='w-full'
              >
                confirm
              </Button>
            </div>
          </DialogFooter>
        </ScrollArea>
      </DialogContent>
    </Dialog>
```

**Comment by 3li7u** [comment]
> You can make a couple of things:
> 
> 1. Not render the `Portal` component in popover (Maybe you have `z-index` issues)
> 2. Set `modal={false}` on Dialog (The overlay will no be rendered)
> 3. Wrap `Dialog.Content` with `Dialog.Overlay` (You can not set `modal={false}` because the overlay will not be rendered)

@joaom00   The third one solves the problem for me but I still have another issue
when I press tab to jumb to the next input the focus move to the dialog instade of the next input
![image](https://github.com/user-attachments/assets/99448932-8f6f-440d-afa4-45f6911db1dd)

**Comment by MentalGear** [comment]
Would be nice if the dialog content would be scrollable by default since that is what's expected. Takes quite a bit of extra frustration to figure out how to make it work:

```svelte
<!--  -->
<Dialog.Root>
    <Dialog.Trigger>
        <slot name="OpenButton" />
    </Dialog.Trigger>

    <Dialog.Content class="!p-0">
        <!-- scroll area needed to make Dialog's content scrollable -->
        <ScrollArea>
            <Dialog.Header>
                <div class="stickyDialogBars top-0">
                    <Dialog.Title>
                        <slot name="Title" />
                    </Dialog.Title>
                </div>

                <div class="p-4">
                    <Dialog.Description>
                        <slot name="Content" />
                    </Dialog.Description>
                </div>
            </Dialog.Header>

            <div class="stickyDialogBars bottom-0">
                <Dialog.Close class="">
                    <Button>Back</Button>
                </Dialog.Close>
            </div>
        </ScrollArea>
        <!--  -->
    </Dialog.Content>
</Dialog.Root>

<style lang="sass">
    
    .stickyDialogBars
        @apply sticky flex place-content-center py-4
        @apply bg-background bg-opacity-90

    // hide close icon on top right corner for m
</style>
```

**Comment by Evavic44** [comment]
It seems this issue also happens with custom scroll components. In my case, I was not using the `ScrollArea` component but @7hourspg's solution worked regardless.

```jsx
<Popover modal={true}>
  <PopoverTrigger>Open</PopoverTrigger>
  <PopoverContent
    className="flex flex-col gap-4 w-60 h-60 overflow-y-scroll p-2"
    align="start"
  >
    {content.map((c) => (
      <button key={c.id} className="w-full">
        {c.title}
      </button>
    ))}
  </PopoverContent>
</Popover>
```

**Comment by andreidionisie** [comment]
> Set `modal={true}` in popover like this ` <Popover open={open} modal={true}>` ✔ Thanks 😎

This makes another side-effect. Dialog closes and reopens when you click outside of popover.

**Comment by Tshiring** [comment]
> > Set `modal={true}` in popover like this ` <Popover open={open} modal={true}>` ✔ Thanks 😎
> 
> This makes another side-effect. Dialog closes and reopens when you click outside of popover.

works fine for me

**Comment by Tshiring** [comment]
` <Popover open={open} onOpenChange={setOpen} modal={true}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          role="combobox"
          aria-expanded={open}
          className="w-full justify-between"
        >
          <span className="min-w-[16ch] truncate text-left text-gray-gray1">
            {defaultValue || 'Select Timezone'}
          </span>
          <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
        </Button>
      </PopoverTrigger>
      {!disabled && (
        <PopoverContent
          className={cn('p-0', isAccountSetupPage && 'w-[--radix-popover-trigger-width]')}
          align="start"
        >
          <Command>
            <CommandInput placeholder="Search Timezone" className="h-9" />

            {isLoading ? (
              <div className="flex items-center justify-center p-4">
                <Loader />
              </div>
            ) : (
              <>
                <CommandEmpty>No Result found.</CommandEmpty>
                <CommandGroup>
                  <CommandList className="h-48">
                    {filteredData.map((filteredData) => (
                      <CommandItem
                        key={filteredData.label}
                        value={filteredData.label}
                        onSelect={() => handleSelectTimezone(filteredData.label)}
                        className=" cursor-pointer text-sm "
                      >
                        <Check
                          className={cn(
                            'absolute right-2 mr-2 h-4 w-4',
                            defaultValue === filteredData.label ? 'opacity-100 ' : 'opacity-0  '
                          )}
                        />
                        {filteredData.label}
                      </CommandItem>
                    ))}
                  </CommandList>
                </CommandGroup>
              </>
            )}
          </Command>
        </PopoverContent>
      )}
    </Popover>`
    setting modal to true in Popover works for me thanks!

**Comment by samislam** [comment]
> Set `modal={true}` in popover like this ` <Popover open={open} modal={true}>` ✔ Thanks 😎

This works thanks

**Comment by mohammadtokee** [comment]
> Set `modal={true}` in popover like this ` <Popover open={open} modal={true}>` ✔ Thanks 😎

This works thanks

https://github.com/user-attachments/assets/1d6679c0-1051-4629-9f4e-5bcca9146c8d

**Comment by rubixvi** [comment]
```
"use client"

import * as React from "react"
import * as DialogPrimitive from "@radix-ui/react-dialog"
import { X } from "lucide-react"

import { cn } from "@/lib/utils"

const Dialog = DialogPrimitive.Root

const DialogTrigger = DialogPrimitive.Trigger

const DialogPortal = DialogPrimitive.Portal

const DialogClose = DialogPrimitive.Close

const DialogOverlay = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Overlay>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Overlay>
>(({ className, ...props }, ref) => (
  <DialogPrimitive.Overlay
    ref={ref}
    className={cn(
      "fixed inset-0 z-50 bg-black/80  data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0",
      className
    )}
    {...props}
  />
))
DialogOverlay.displayName = DialogPrimitive.Overlay.displayName

const DialogContent = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Content> & {
    showClose?: boolean
  }
>(({ className, showClose = true, children, ...props }, ref) => (
  <DialogPortal>
    <DialogOverlay />
    <DialogPrimitive.Content
      ref={ref}
      className={cn(
        "fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border bg-background p-6 shadow-lg duration-200 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 sm:rounded-lg max-h-[85vh] overflow-y-auto",
        className
      )}
      onWheel={(e) => e.stopPropagation()}
      {...props}
    >
      {children}
      {showClose && (
        <DialogPrimitive.Close className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-accent data-[state=open]:text-muted-foreground">
          <X className="h-4 w-4" />
          <span className="sr-only">Close</span>
        </DialogPrimitive.Close>
      )}
    </DialogPrimitive.Content>
  </DialogPortal>
))
DialogContent.displayName = DialogPrimitive.Content.displayName

const DialogHeader = ({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) => (
  <div
    className={cn(
      "flex flex-col space-y-1.5 text-center sm:text-left",
      className
    )}
    {...props}
  />
)
DialogHeader.displayName = "DialogHeader"

const DialogFooter = ({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) => (
  <div
    className={cn(
      "flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2",
      className
    )}
    {...props}
  />
)
DialogFooter.displayName = "DialogFooter"

const DialogTitle = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Title>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Title>
>(({ className, ...props }, ref) => (
  <DialogPrimitive.Title
    ref={ref}
    className={cn(
      "text-lg font-semibold leading-none tracking-tight",
      className
    )}
    {...props}
  />
))
DialogTitle.displayName = DialogPrimitive.Title.displayName

const DialogDescription = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Description>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Description>
>(({ className, ...props }, ref) => (
  <DialogPrimitive.Description
    ref={ref}
    className={cn("text-sm text-muted-foreground", className)}
    {...props}
  />
))
DialogDescription.displayName = DialogPrimitive.Description.displayName

export {
  Dialog,
  DialogPortal,
  DialogOverlay,
  DialogClose,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogFooter,
  DialogTitle,
  DialogDescription,
}

```

Here's a solution to use the <ScrollArea> inside of shadcnui.

PS. I made this into a new dialogue component, so the original one still maintains its function and can be reused for my other components. But this will disable any scroll propagation, so using the scroll wheel for the scroll area component will work.

**Comment by jawad11231** [comment]
change the code in popover.tsx to be like this

 const Popover = React.forwardRef<
  React.ElementRef<typeof PopoverPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof PopoverPrimitive.Root>
>(({ ...props }, ref) => <PopoverPrimitive.Root modal={true} {...props} />);
Popover.displayName = PopoverPrimitive.Root.displayName;

**Comment by sudheer-salavadi** [comment]
> You can make a couple of things:
> 
> 1. Not render the `Portal` component in popover (Maybe you have `z-index` issues)
> 2. Set `modal={false}` on Dialog (The overlay will no be rendered)
> 3. Wrap `Dialog.Content` with `Dialog.Overlay` (You can not set `modal={false}` because the overlay will not be rendered)

This should inject the background overlay.

`<Dialog open={isModalOpen} onOpenChange={setIsModalOpen} modal={false}>
      {isModalOpen && (
        <div className="fixed inset-0 bg-black/50 z-20 animate-fade-in" />
      )}`

**Comment by gaisdav** [comment]
> Set `modal={true}` in popover like this ` <Popover open={open} modal={true}>` ✔ Thanks 😎

Legend!

**Comment by LazyFatArrow** [comment]
Had the same issue, I was trying to set `modal={true}` on the Dialog itself which didn't work. If you are using `Command` you have to set it on the `Popover` that you wrap the `Command` with.
