### ISSUE TITLE
Dark mode not working in App directory

### ISSUE THREAD

**Issue by Heb-l** [shadcn/ui#926]
Hey @shadcn, really enjoying working with the UI project, thanks. 

I'm having trouble getting the dark mode to work in Next 13.4.7 in the App dir.

I've followed the guide on this page: https://ui.shadcn.com/docs/dark-mode

// app/layout.tsx
`import Header from "@/components/header";
import '../styles/globals.css';
import { ThemeProvider } from '@/components/theme-provider';

export default function RootLayout({ children }) {
    return (
            <html lang="en">
            <body>
            <Header/>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                {children}
            </ThemeProvider>
            </body>
            </html>
    )
}`

// app/components/theme-provider.tsx
`"use client";

import * as React from "react"
import { ThemeProvider as NextThemesProvider } from "next-themes"
import { type ThemeProviderProps } from "next-themes/dist/types"

export function ThemeProvider({ children, ...props }: ThemeProviderProps) {
    return <NextThemesProvider {...props}>{children}</NextThemesProvider>
}`

// app/theme-switcher
`"use client";

import * as React from "react"
import { Moon, Sun } from "lucide-react"
import { useTheme } from "next-themes"

import { Button } from "@/components/ui/button"
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"

export function ModeToggle() {
    const { theme, setTheme } = useTheme();

    return (
        <DropdownMenu>
            The current theme is: {theme}
            <DropdownMenuTrigger asChild>
                <Button variant="outline" size="icon">
                    <Sun className="h-[1.2rem] w-[1.2rem] rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
                    <Moon className="absolute h-[1.2rem] w-[1.2rem] rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
                    <span className="sr-only">Toggle theme</span>
                </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
                <DropdownMenuItem onClick={() => setTheme("light")}>
                    Light
                </DropdownMenuItem>
                <DropdownMenuItem onClick={() => setTheme("dark")}>
                    Dark
                </DropdownMenuItem>
                <DropdownMenuItem onClick={() => setTheme("system")}>
                    System
                </DropdownMenuItem>
            </DropdownMenuContent>
        </DropdownMenu>
    )
}`

![Uploading image.png…]()

Most likely something I'm doing wrong, any chance you can spot it? Thanks!

**Comment by Heb-l** [comment]
[shadcn_dark_mode.zip](https://github.com/shadcn/ui/files/12041662/shadcn_dark_mode.zip)

**Comment by Heb-l** [comment]
Getting the following console error:
```
app-index.js:32 Warning: Extra attributes from the server: class,style
    at html
    at RedirectErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/redirect-boundary.js:73:9)
    at RedirectBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/redirect-boundary.js:81:11)
    at NotFoundErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/not-found-boundary.js:51:9)
    at NotFoundBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/not-found-boundary.js:59:11)
    at ReactDevOverlay (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:66:9)
    at HotReload (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:276:11)
    at Router (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/app-router.js:92:11)
    at ErrorBoundaryHandler (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:77:9)
    at ErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:101:11)
    at AppRouter (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/app-router.js:392:13)
    at ServerRoot (webpack-internal:///(app-client)/./node_modules/next/dist/client/app-index.js:163:11)
    at RSCComponent
    at Root (webpack-internal:///(app-client)/./node_modules/next/dist/client/app-index.js:180:11)
```

**Comment by Heb-l** [comment]
I needed to include the <Header /> which contained the <ModeToggle /> inside the <ThemeProvider> component.

```
//layout.tsx
import { ThemeProvider } from '@/components/theme-provider';
import Header from "@/components/header";
import '../styles/globals.css';
export default function RootLayout({ children }) {
    return (
            <html suppressHydrationWarning lang="en">
            <head />
            <body>
            <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
                <Header/>
                {children}
            </ThemeProvider>
            </body>
            </html>
    )
}
```

Instead of: 
```
//layout.tsx
import { ThemeProvider } from '@/components/theme-provider';
import Header from "@/components/header";
import '../styles/globals.css';
export default function RootLayout({ children }) {
    return (
            <html suppressHydrationWarning lang="en">
            <head />
            <body>
            <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
                <Header/>
                {children}
            </ThemeProvider>
            </body>
            </html>
    )
}
```

Makes perfect sense now I see what it's doing!

**Comment by dpz3579** [comment]
> Getting the following console error:
> 
> ```
> app-index.js:32 Warning: Extra attributes from the server: class,style
>     at html
>     at RedirectErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/redirect-boundary.js:73:9)
>     at RedirectBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/redirect-boundary.js:81:11)
>     at NotFoundErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/not-found-boundary.js:51:9)
>     at NotFoundBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/not-found-boundary.js:59:11)
>     at ReactDevOverlay (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:66:9)
>     at HotReload (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:276:11)
>     at Router (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/app-router.js:92:11)
>     at ErrorBoundaryHandler (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:77:9)
>     at ErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:101:11)
>     at AppRouter (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/app-router.js:392:13)
>     at ServerRoot (webpack-internal:///(app-client)/./node_modules/next/dist/client/app-index.js:163:11)
>     at RSCComponent
>     at Root (webpack-internal:///(app-client)/./node_modules/next/dist/client/app-index.js:180:11)
> ```

Hey. 
How did you resolve this issue ?

I'm facing the same one.

**Comment by Toufik1247** [comment]
just follow what explained in this post :
https://github.com/shadcn-ui/ui/issues/926#issuecomment-1634597958

**Comment by Toufik1247** [comment]
> > Getting the following console error:
> > ```
> > app-index.js:32 Warning: Extra attributes from the server: class,style
> >     at html
> >     at RedirectErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/redirect-boundary.js:73:9)
> >     at RedirectBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/redirect-boundary.js:81:11)
> >     at NotFoundErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/not-found-boundary.js:51:9)
> >     at NotFoundBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/not-found-boundary.js:59:11)
> >     at ReactDevOverlay (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:66:9)
> >     at HotReload (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:276:11)
> >     at Router (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/app-router.js:92:11)
> >     at ErrorBoundaryHandler (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:77:9)
> >     at ErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:101:11)
> >     at AppRouter (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/app-router.js:392:13)
> >     at ServerRoot (webpack-internal:///(app-client)/./node_modules/next/dist/client/app-index.js:163:11)
> >     at RSCComponent
> >     at Root (webpack-internal:///(app-client)/./node_modules/next/dist/client/app-index.js:180:11)
> > ```
> 
> Hey. How did you resolve this issue ?
> 
> I'm facing the same one.

just follow what explained in this post :
https://github.com/shadcn-ui/ui/issues/926#issuecomment-1634597958

**Comment by maatouk-j1** [comment]
Hello,

I'm also facing the same error in Next.js 13.4.13-canary.5.

I set up the Theme Provider and it's working perfectly fine. The only issue is that I'm getting the same error shared above in my console.

Layout.tsx:

`import "./css/style.css";
import { Inter } from "next/font/google";
import PageIllustration from "@/components/page-illustration";
import Header from "@/components/header";
import AOS from "@/components/utils/aos";
import { ThemeProvider } from "@/components/utils/theme-provider";
import { Toaster } from "@/components/ui/toaster";

const fontInter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Flopping Nuts",
  description: "Crypto Poker Website",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${fontInter.variable} font-inter antialiased tracking-tight`}
      >
        <AOS />
        <PageIllustration />

        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="flex flex-col min-h-screen overflow-hidden">
            <Header />
            {children}
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
`

**Comment by dpz3579** [comment]
> Hello,
> 
> I'm also facing the same error in Next.js 13.4.13-canary.5.
> 
> I set up the Theme Provider and it's working perfectly fine. The only issue is that I'm getting the same error shared above in my console.
> 
> Also, including the Header component inside the Theme Provider doesn't resolve the issue.

Try using "`suppressHydrationWarning`" in html tag.
It solved for me, looks like there's this issue in NextJS 13.

in your `layout.tsx`
`<html suppressHydrationWarning lang="en">`

**Comment by maatouk-j1** [comment]
This way I'm only suppressing the warnings and not fixing the issue, correct ?

**Comment by JamesSingleton** [comment]
> suppressHydrationWarning

Correct... I am also facing this issue and I already have my SiteHeader which has the ModeToggle inside the theme provider

```tsx
export default function RootLayout(
  { children }: { children: React.ReactNode },
) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="relative flex min-h-screen flex-col">
            <SiteHeader />
            <main className="flex-1">{children}</main>
            <Footer />
          </div>
          <TailwindIndicator />
        </ThemeProvider>
      </body>
    </html>
  )
}
```

Yes adding `suppressHydrationWarning` gets rid of the error but I feel like I shouldn't have to add that?

**Comment by maatouk-j1** [comment]
You can add this:

`<html lang="en" className="light" style={{ colorScheme: "light" }}>`

**Comment by mpcen** [comment]
This should be reopened as it's still an issue

**Comment by yigithancolak** [comment]
Facing the same issue. Moving header component is not a good solution for every body.

**Comment by palmithor** [comment]
I faced the exact same problem and it was due to the fact that my tailwind config `content` was not capturing the location of the shadcn components.

**Comment by LyMc** [comment]
I had a similar issue, where the .dark rules were striped from globals.css by tailwind because I haven't used dark class anywhere in my code. Forcing it on html element fixed this issue for me.

**Comment by morganfeeney** [comment]
It turns out that next-themes recommend adding `suppressHydrationWarning`: https://github.com/pacocoursey/next-themes?tab=readme-ov-file#with-app

> Note! If you do not add [suppressHydrationWarning](https://reactjs.org/docs/dom-elements.html#suppresshydrationwarning:~:text=It%20only%20works%20one%20level%20deep) to your <html> you will get warnings because next-themes updates that element. This property only applies one level deep, so it won't block hydration warnings on other elements.

YOLO 🤷‍♂️

**Comment by Code-DJ** [comment]
@LyMc adding this to the layout page also fixes it.

```js
export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
}
```

@morganfeeney you can avoid adding `suppressHydrationWarning` by doing this: https://github.com/pacocoursey/next-themes?tab=readme-ov-file#avoid-hydration-mismatch

Be sure to add the mounted logic to both provider and switcher.

**Comment by ardiansyaherwin** [comment]
> @LyMc adding this to the layout page also fixes it.
> 
> ```js
> export const viewport: Viewport = {
>   themeColor: [
>     { media: "(prefers-color-scheme: light)", color: "white" },
>     { media: "(prefers-color-scheme: dark)", color: "black" },
>   ],
> }
> ```
> 
> @morganfeeney you can avoid adding `suppressHydrationWarning` by doing this: https://github.com/pacocoursey/next-themes?tab=readme-ov-file#avoid-hydration-mismatch
> 
> Be sure to add the mounted logic to both provider and switcher.

If you're doing this, it will make all child components are converted to client component.

**Comment by CyberClarence** [comment]
for me it was `darkMode: "class"` was missing in my tailwind config file
```ts
import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class", <-- add this
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/ui/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("tailwindcss-animate")],
};
export default config;

```

**Comment by Code-DJ** [comment]
> If you're doing this, it will make all child components are converted to client component.

Why would it make all child components client?

**Comment by ardiansyaherwin** [comment]
> > If you're doing this, it will make all child components are converted to client component.
> 
> Why would it make all child components client?

because of returning the children based on state hook. at least that's what happen on my local, or maybe it's just me

**Comment by muhammadali-pro** [comment]
> > > If you're doing this, it will make all child components are converted to client component.
> > 
> > 
> > Why would it make all child components client?
> 
> because of returning the children based on state hook. at least that's what happen on my local, or maybe it's just me

**Just a clarification**. 
Making parent component a client side component does not mean all child components will become client side components. so you can use client components as parent and it will not make child components as client components.
