### ISSUE TITLE
Why migrate away from the `<RootComponent.SubComponent>` API?

### ISSUE THREAD

**Issue by corysimmons** [shadcn/ui#93]
Just curious.

**Comment by shadcn** [comment]
This was the result of several decisions I made when I started working on the components.

1️⃣ The first component I started with was `Checkbox`. 

I wanted to write `<Checkbox />` and not `<Checkbox.Root><Checkbox.Indicator /></Checkbox.Root>`. 

So I abstracted the Root and Indicator inside a `<Checkbox />` components.

```tsx
// @file components/checkbox.tsx
import * as CheckboxPrimitive from "@radix-ui/react-checkbox"

const Checkbox = (({ className, ...props }, ref) => (
  <CheckboxPrimitive.Root>
    <CheckboxPrimitive.Indicator>
      <Check className="h-4 w-4" />
    </CheckboxPrimitive.Indicator>
  </CheckboxPrimitive.Root>
))

export { Checkbox }
```

But then the following looked wrong.

```tsx
import * as Checkbox from "components/checkbox"

<Checkbox.Checkbox />
``` 

So I went with `import { Checkbox } from "components/checkbox"`.

2️⃣ `RootComponent.SubComponent` does not work inside MDX (mdx-bundler and Contentlayer).

3️⃣ Searching around, I found that WorkOS has a similar API for handling component export/import.

So based on the following, I went with `import { FooBar, FooBaz } from "components/foo"`.

PS: You can still use the dot notation if you want: `import * as DropdownMenu from "components/dropdown-menu"`

**Comment by corysimmons** [comment]
Thanks for taking the time to answer. That makes sense.
